export type CategorySlug = "calculadoras" | "conversores" | "texto" | "fechas" | "seguridad";
export interface Category { slug: CategorySlug; name: string; title: string; description: string; intro: string; }
export interface FaqItem { q: string; a: string; }
export interface Tool { slug: string; name: string; title: string; description: string; summary: string; category: CategorySlug; keywords: string[]; about: string[]; steps: string[]; faq: FaqItem[]; }

export const CATEGORIES: Category[] = [
  { slug:"calculadoras", name:"Calculadoras", title:"Calculadoras online gratis | UtiliHub", description:"Calculadoras online gratuitas y sin registro: aritmética, porcentajes y regla de tres. Funcionan en el navegador y sin enviar datos.", intro:"Herramientas de cálculo para operaciones cotidianas. Todas se ejecutan en tu navegador, así que responden al instante y no necesitan conexión una vez cargada la página." },
  { slug:"conversores", name:"Conversores", title:"Conversores de unidades online | UtiliHub", description:"Convierte longitud, peso y temperatura con factores de conversión estándar. Conversores rápidos, gratuitos y sin registro.", intro:"Conversores basados en factores del Sistema Internacional y en equivalencias imperiales oficiales. Introduce un valor y obtén el resultado mientras escribes." },
  { slug:"texto", name:"Texto", title:"Herramientas de texto online | UtiliHub", description:"Analiza y trabaja con texto en el navegador: contador de palabras, caracteres, frases y tiempo estimado de lectura.", intro:"Utilidades para escribir y revisar textos. El contenido que pegas nunca sale de tu dispositivo porque el procesamiento ocurre en el navegador." },
  { slug:"fechas", name:"Fechas", title:"Calculadoras de fechas online | UtiliHub", description:"Calcula la diferencia entre dos fechas en días, semanas, meses y años, incluyendo días laborables.", intro:"Herramientas para trabajar con calendarios: diferencias entre fechas, plazos y conteo de días laborables." },
  { slug:"seguridad", name:"Seguridad", title:"Herramientas de seguridad online | UtiliHub", description:"Genera contraseñas seguras en tu propio navegador con la API criptográfica del sistema. Sin envío de datos.", intro:"Utilidades de seguridad que se ejecutan localmente. Nada de lo que generas se transmite ni se almacena en un servidor." },
];

export const TOOLS: Tool[] = [
  { slug:"calculadora", name:"Calculadora", title:"Calculadora online gratis | UtiliHub", description:"Calculadora online con teclado, historial y operaciones básicas. Gratis, sin registro y funciona directamente en tu navegador.", summary:"Suma, resta, multiplica y divide con teclado e historial.", category:"calculadoras", keywords:["calculadora online","calculadora gratis","calculadora básica"], about:["Esta calculadora resuelve operaciones aritméticas básicas: suma, resta, multiplicación, división y porcentaje. Puedes usar el teclado físico o los botones en pantalla, y el historial de la sesión te permite revisar los últimos resultados.","El cálculo se hace íntegramente en el navegador con aritmética de coma flotante de doble precisión."], steps:["Escribe el primer número con el teclado o los botones.","Elige la operación (+, −, ×, ÷ o %).","Introduce el segundo número y pulsa «=» o Enter.","Usa «C» para limpiar y «⌫» para borrar el último dígito."], faq:[{q:"¿Necesito registrarme o instalar algo?",a:"No. La calculadora funciona en la propia página web y no requiere cuenta, instalación ni permisos."},{q:"¿Puedo usar el teclado del ordenador?",a:"Sí. Los números, los operadores, Enter, Escape y Retroceso están soportados."}] },
  { slug:"calculadora-de-porcentajes", name:"Calculadora de porcentajes", title:"Calculadora de porcentajes online | UtiliHub", description:"Calcula el porcentaje de una cantidad, qué porcentaje representa un número y el aumento o descuento entre dos valores.", summary:"Porcentaje de una cantidad, proporción y variación porcentual.", category:"calculadoras", keywords:["calcular porcentaje","porcentaje de un número","variación porcentual"], about:["Un porcentaje expresa una parte por cada cien unidades del total. Calcular el 15 % de 240 equivale a multiplicar 240 por 15 y dividir entre 100, es decir, 36.","Esta herramienta cubre los tres planteamientos más habituales: obtener el porcentaje de una cantidad, averiguar qué porcentaje representa un número respecto a otro y medir la variación entre un valor inicial y uno final."], steps:["Selecciona el tipo de cálculo que necesitas.","Rellena los dos campos numéricos.","El resultado y la fórmula aplicada se muestran al instante."], faq:[{q:"¿Cómo se calcula un descuento?",a:"Usa la variación porcentual entre el precio original y el precio final: un resultado negativo indica el descuento aplicado."},{q:"¿Cómo quito el IVA de un precio?",a:"Divide el precio con impuestos entre 1 más el tipo en tanto por uno. Con un 21 %, sería precio ÷ 1,21."},{q:"¿Acepta decimales?",a:"Sí, puedes escribir decimales con punto o con coma."}] },
  { slug:"regla-de-tres", name:"Regla de tres", title:"Regla de tres online: directa e inversa | UtiliHub", description:"Resuelve reglas de tres simples directas e inversas paso a paso. Introduce tres valores conocidos y obtén la incógnita.", summary:"Proporciones directas e inversas con el desarrollo del cálculo.", category:"calculadoras", keywords:["regla de tres","regla de tres inversa","proporciones"], about:["La regla de tres simple resuelve proporciones: si conoces tres valores relacionados, puedes deducir el cuarto. En la variante directa, x = b × c ÷ a. En la inversa ocurre lo contrario, x = a × b ÷ c."], steps:["Elige entre proporción directa o inversa.","Introduce los valores A, B y C.","Lee el valor X y la fórmula utilizada."], faq:[{q:"¿Cuándo uso la regla de tres inversa?",a:"Cuando al aumentar una magnitud la otra disminuye proporcionalmente, como más operarios y menos días de trabajo."},{q:"¿Puedo usar decimales?",a:"Sí. Se admiten valores decimales."}] },
  { slug:"calculadora-de-fechas", name:"Diferencia entre fechas", title:"Calcular diferencia entre dos fechas | UtiliHub", description:"Calcula cuántos días, semanas, meses y años hay entre dos fechas, con el total de días laborables y fines de semana.", summary:"Días, semanas, meses, años y días laborables entre dos fechas.", category:"fechas", keywords:["diferencia entre fechas","calcular días entre fechas","días laborables"], about:["La herramienta calcula el intervalo entre dos fechas del calendario gregoriano teniendo en cuenta los años bisiestos.","Además se indican los días laborables (de lunes a viernes) y los días de fin de semana del intervalo. Los festivos locales no se descuentan porque varían según el país y la región."], steps:["Selecciona la fecha de inicio.","Selecciona la fecha de fin.","Consulta el desglose de días, semanas, meses y laborables."], faq:[{q:"¿Se incluye el último día?",a:"El cálculo devuelve la diferencia entre ambas fechas. Si necesitas contar también el día final, súmale uno al total de días."},{q:"¿Descuenta festivos?",a:"No. Solo distingue entre días laborables de lunes a viernes y fines de semana."},{q:"¿Tiene en cuenta los años bisiestos?",a:"Sí, el cálculo usa el calendario real, incluidos los 29 de febrero."}] },
  { slug:"contador-de-palabras", name:"Contador de palabras", title:"Contador de palabras y caracteres online | UtiliHub", description:"Cuenta palabras, caracteres con y sin espacios, frases, párrafos y tiempo estimado de lectura mientras escribes.", summary:"Palabras, caracteres, frases, párrafos y tiempo de lectura.", category:"texto", keywords:["contador de palabras","contador de caracteres","tiempo de lectura"], about:["Cuenta en tiempo real las palabras, los caracteres (con y sin espacios), las frases y los párrafos de cualquier texto. Es útil para trabajos académicos, publicaciones y textos con restricciones de caracteres.","El tiempo estimado de lectura se calcula con una velocidad de referencia de 200 palabras por minuto."], steps:["Escribe o pega tu texto en el área de edición.","Las métricas se actualizan mientras escribes.","Copia el texto o límpialo con un solo clic."], faq:[{q:"¿Se envía mi texto a algún servidor?",a:"No. El análisis ocurre en tu navegador y el contenido no se transmite ni se guarda."},{q:"¿Cómo se cuenta una palabra?",a:"Se considera palabra cualquier secuencia de caracteres separada por espacios o saltos de línea."}] },
  { slug:"generador-de-contrasenas", name:"Generador de contraseñas", title:"Generador de contraseñas seguras | UtiliHub", description:"Crea contraseñas aleatorias de hasta 64 caracteres con la API criptográfica del navegador. Sin envío de datos ni registro.", summary:"Contraseñas aleatorias configurables con estimación de entropía.", category:"seguridad", keywords:["generador de contraseñas","contraseña segura","contraseña aleatoria"], about:["Las contraseñas se generan con crypto.getRandomValues(), la fuente de aleatoriedad criptográfica que incorporan los navegadores modernos. La generación es local: la contraseña no se envía a ningún servidor.","Junto a cada contraseña se muestra su entropía aproximada en bits."], steps:["Ajusta la longitud con el control deslizante.","Activa o desactiva mayúsculas, minúsculas, números y símbolos.","Pulsa «Generar» y copia la contraseña al portapapeles."], faq:[{q:"¿Se guarda la contraseña generada?",a:"No. Se crea en la memoria de tu navegador y desaparece al recargar la página."},{q:"¿Qué longitud conviene usar?",a:"Longitudes mayores aumentan el margen de seguridad."},{q:"¿Puedo evitar caracteres ambiguos?",a:"Sí, hay una opción para excluir caracteres fáciles de confundir."}] },
  { slug:"conversor-de-temperatura", name:"Conversor de temperatura", title:"Conversor de temperatura: °C, °F y K | UtiliHub", description:"Convierte grados Celsius, Fahrenheit y Kelvin al instante, con las fórmulas de conversión visibles.", summary:"Celsius, Fahrenheit y Kelvin con las fórmulas aplicadas.", category:"conversores", keywords:["convertir celsius a fahrenheit","conversor temperatura","kelvin"], about:["Convierte entre Celsius, Fahrenheit y Kelvin con fórmulas estándar. Al escribir en cualquiera de los tres campos, los otros dos se recalculan automáticamente."], steps:["Escribe la temperatura en la escala que conozcas.","Los otros dos campos se actualizan de forma automática.","Consulta la fórmula aplicada bajo el conversor."], faq:[{q:"¿Cuánto es 100 °F en grados Celsius?",a:"(100 − 32) × 5/9 ≈ 37,78 °C."},{q:"¿Existen temperaturas negativas en Kelvin?",a:"No. El cero kelvin es el cero absoluto."}] },
  { slug:"conversor-de-longitud", name:"Conversor de longitud", title:"Conversor de longitud: metros, pies, millas | UtiliHub", description:"Convierte metros, kilómetros, centímetros, pulgadas, pies, yardas y millas con factores exactos.", summary:"Sistema métrico e imperial: de milímetros a millas.", category:"conversores", keywords:["convertir metros a pies","conversor de longitud","pulgadas a centímetros"], about:["Convierte entre unidades métricas e imperiales usando factores definidos internacionalmente."], steps:["Introduce la cantidad que quieres convertir.","Elige la unidad de origen y la de destino.","Consulta el resultado y la tabla de equivalencias rápidas."], faq:[{q:"¿Cuántos centímetros tiene una pulgada?",a:"Exactamente 2,54 centímetros por definición internacional."},{q:"¿Un pie cuántos metros son?",a:"Un pie equivale a 0,3048 metros exactos."}] },
  { slug:"conversor-de-peso", name:"Conversor de peso", title:"Conversor de peso: kg, libras y onzas | UtiliHub", description:"Convierte kilogramos, gramos, toneladas, libras, onzas y stones con factores de conversión estándar.", summary:"Kilogramos, gramos, libras, onzas, stones y toneladas.", category:"conversores", keywords:["convertir kg a libras","conversor de peso","onzas a gramos"], about:["Convierte unidades de masa usando el kilogramo como unidad base. En el uso cotidiano se habla de peso, aunque físicamente estas unidades miden masa."], steps:["Escribe la cantidad de origen.","Selecciona la unidad de partida y la de llegada.","Copia el resultado o revisa las equivalencias frecuentes."], faq:[{q:"¿Cuántas libras es un kilo?",a:"Un kilogramo equivale aproximadamente a 2,20462 libras."},{q:"¿Qué es un stone?",a:"Una unidad británica equivalente a 14 libras."}] },
  { slug:"conversor-de-unidades", name:"Conversor de unidades", title:"Conversor de unidades todo en uno | UtiliHub", description:"Convierte longitud, peso, temperatura, volumen, superficie y tiempo desde una sola herramienta, sin registro.", summary:"Longitud, peso, temperatura, volumen, superficie y tiempo.", category:"conversores", keywords:["conversor de unidades","convertir unidades","conversor online"], about:["Un único conversor para las magnitudes de uso más frecuente: longitud, masa, temperatura, volumen, superficie y tiempo. Cada magnitud utiliza factores estándar."], steps:["Elige la magnitud que quieres convertir.","Introduce el valor y selecciona las unidades.","El resultado aparece de forma inmediata."], faq:[{q:"¿Qué magnitudes están disponibles?",a:"Longitud, masa, temperatura, volumen, superficie y tiempo."},{q:"¿Los factores son exactos?",a:"Se emplean factores definidos internacionalmente; el resultado se redondea solo al mostrarlo."}] }
];

export const toolBySlug = (slug: string) => TOOLS.find(t => t.slug === slug);
export const categoryBySlug = (slug: string) => CATEGORIES.find(c => c.slug === slug);
export const toolsByCategory = (slug: CategorySlug) => TOOLS.filter(t => t.category === slug);