export type CategorySlug = "calculadoras" | "conversores" | "texto" | "fechas" | "seguridad";
export interface Category { slug: CategorySlug; name: string; title: string; description: string; intro: string; }
export interface FaqItem { q: string; a: string; }
export interface Tool { slug: string; name: string; title: string; description: string; summary: string; category: CategorySlug; keywords: string[]; about: string[]; steps: string[]; faq: FaqItem[]; }

export const CATEGORIES: Category[] = [
  { slug:"calculadoras", name:"Calculators", title:"Free online calculators | UtiliHub", description:"Free online calculators with no signup: arithmetic, percentages, and rule of three. They run in the browser without sending data.", intro:"Calculation tools for everyday operations. All run in your browser, so they respond instantly and do not need a connection once the page is loaded." },
  { slug:"conversores", name:"Converters", title:"Online unit converters | UtiliHub", description:"Convert length, weight, and temperature with standard conversion factors. Fast, free converters with no signup.", intro:"Converters based on International System factors and official imperial equivalences. Enter a value and get the result as you type." },
  { slug:"texto", name:"Text", title:"Online text tools | UtiliHub", description:"Analyze and work with text in the browser: word count, characters, sentences, and estimated reading time.", intro:"Utilities for writing and reviewing text. The content you paste never leaves your device because processing happens in the browser." },
  { slug:"fechas", name:"Dates", title:"Online date calculators | UtiliHub", description:"Calculate the difference between two dates in days, weeks, months, and years, including business days.", intro:"Tools for working with calendars: date differences, deadlines, and business-day counts." },
  { slug:"seguridad", name:"Security", title:"Online security tools | UtiliHub", description:"Generate secure passwords in your own browser with the system cryptographic API. No data upload.", intro:"Security utilities that run locally. Nothing you generate is transmitted or stored on a server." },
];

export const TOOLS: Tool[] = [
  { slug:"calculadora", name:"Calculator", title:"Free online calculator | UtiliHub", description:"Online calculator with keyboard, history, and basic operations. Free, no signup, and runs directly in your browser.", summary:"Add, subtract, multiply, and divide with keyboard and history.", category:"calculadoras", keywords:["online calculator","free calculator","basic calculator"], about:["This calculator solves basic arithmetic operations: addition, subtraction, multiplication, division, and percentage. You can use the physical keyboard or on-screen buttons, and the session history lets you review recent results.","Calculation is done entirely in the browser with double-precision floating-point arithmetic."], steps:["Enter the first number with the keyboard or buttons.","Choose the operation (+, −, ×, ÷, or %).","Enter the second number and press «=» or Enter.","Use «C» to clear and «⌫» to delete the last digit."], faq:[{q:"Do I need to sign up or install anything?",a:"No. The calculator works on the web page itself and requires no account, install, or permissions."},{q:"Can I use the computer keyboard?",a:"Yes. Numbers, operators, Enter, Escape, and Backspace are supported."}] },
  { slug:"calculadora-de-porcentajes", name:"Percentage calculator", title:"Online percentage calculator | UtiliHub", description:"Calculate the percentage of an amount, what percentage a number represents, and the increase or discount between two values.", summary:"Percentage of an amount, proportion, and percentage change.", category:"calculadoras", keywords:["calculate percentage","percentage of a number","percentage change"], about:["A percentage expresses a part per hundred of the total. Calculating 15% of 240 means multiplying 240 by 15 and dividing by 100, which is 36.","This tool covers the three most common cases: getting a percentage of an amount, finding what percentage one number is of another, and measuring the change between an initial and a final value."], steps:["Select the type of calculation you need.","Fill in the two numeric fields.","The result and applied formula appear instantly."], faq:[{q:"How do I calculate a discount?",a:"Use the percentage change between the original price and the final price: a negative result indicates the discount applied."},{q:"How do I remove tax from a price?",a:"Divide the tax-inclusive price by 1 plus the rate as a fraction. With 21%, that is price ÷ 1.21."},{q:"Does it accept decimals?",a:"Yes, you can enter decimals with a period or a comma."}] },
  { slug:"regla-de-tres", name:"Rule of three", title:"Online rule of three: direct and inverse | UtiliHub", description:"Solve simple direct and inverse rules of three step by step. Enter three known values and get the unknown.", summary:"Direct and inverse proportions with the calculation breakdown.", category:"calculadoras", keywords:["rule of three","inverse rule of three","proportions"], about:["The simple rule of three solves proportions: if you know three related values, you can deduce the fourth. In the direct form, x = b × c ÷ a. In the inverse form, x = a × b ÷ c."], steps:["Choose direct or inverse proportion.","Enter values A, B, and C.","Read value X and the formula used."], faq:[{q:"When do I use the inverse rule of three?",a:"When increasing one quantity decreases the other proportionally, such as more workers and fewer days of work."},{q:"Can I use decimals?",a:"Yes. Decimal values are supported."}] },
  { slug:"calculadora-de-fechas", name:"Date difference", title:"Calculate the difference between two dates | UtiliHub", description:"Calculate how many days, weeks, months, and years there are between two dates, including total business days and weekends.", summary:"Days, weeks, months, years, and business days between two dates.", category:"fechas", keywords:["difference between dates","calculate days between dates","business days"], about:["The tool calculates the interval between two Gregorian calendar dates, accounting for leap years.","It also shows business days (Monday to Friday) and weekend days in the interval. Local holidays are not subtracted because they vary by country and region."], steps:["Select the start date.","Select the end date.","Review the breakdown of days, weeks, months, and business days."], faq:[{q:"Is the last day included?",a:"The calculation returns the difference between both dates. If you also need to count the end day, add one to the total days."},{q:"Does it subtract holidays?",a:"No. It only distinguishes weekdays Monday–Friday from weekends."},{q:"Does it account for leap years?",a:"Yes, the calculation uses the real calendar, including February 29."}] },
  { slug:"contador-de-palabras", name:"Word counter", title:"Online word and character counter | UtiliHub", description:"Count words, characters with and without spaces, sentences, paragraphs, and estimated reading time as you type.", summary:"Words, characters, sentences, paragraphs, and reading time.", category:"texto", keywords:["word counter","character counter","reading time"], about:["It counts words, characters (with and without spaces), sentences, and paragraphs of any text in real time. Useful for academic work, publications, and character-limited text.","Estimated reading time is calculated at a reference speed of 200 words per minute."], steps:["Type or paste your text in the editing area.","Metrics update as you type.","Copy the text or clear it with one click."], faq:[{q:"Is my text sent to a server?",a:"No. Analysis happens in your browser and the content is not transmitted or stored."},{q:"How is a word counted?",a:"A word is any sequence of characters separated by spaces or line breaks."}] },
  { slug:"generador-de-contrasenas", name:"Password generator", title:"Secure password generator | UtiliHub", description:"Create random passwords of up to 64 characters with the browser cryptographic API. No data upload or signup.", summary:"Configurable random passwords with entropy estimate.", category:"seguridad", keywords:["password generator","secure password","random password"], about:["Passwords are generated with crypto.getRandomValues(), the cryptographic randomness source built into modern browsers. Generation is local: the password is not sent to any server.","Each password shows its approximate entropy in bits."], steps:["Adjust the length with the slider.","Enable or disable uppercase, lowercase, numbers, and symbols.","Click «Generate» and copy the password to the clipboard."], faq:[{q:"Is the generated password stored?",a:"No. It is created in your browser memory and disappears when you reload the page."},{q:"What length should I use?",a:"Longer lengths increase the security margin."},{q:"Can I avoid ambiguous characters?",a:"Yes, there is an option to exclude easily confused characters."}] },
  { slug:"conversor-de-temperatura", name:"Temperature converter", title:"Temperature converter: °C, °F, and K | UtiliHub", description:"Convert Celsius, Fahrenheit, and Kelvin instantly, with the conversion formulas visible.", summary:"Celsius, Fahrenheit, and Kelvin with the applied formulas.", category:"conversores", keywords:["convert celsius to fahrenheit","temperature converter","kelvin"], about:["Convert between Celsius, Fahrenheit, and Kelvin with standard formulas. When you type in any of the three fields, the other two recalculate automatically."], steps:["Enter the temperature in the scale you know.","The other two fields update automatically.","See the applied formula under the converter."], faq:[{q:"What is 100 °F in Celsius?",a:"(100 − 32) × 5/9 ≈ 37.78 °C."},{q:"Are there negative temperatures in Kelvin?",a:"No. Zero kelvin is absolute zero."}] },
  { slug:"conversor-de-longitud", name:"Length converter", title:"Length converter: meters, feet, miles | UtiliHub", description:"Convert meters, kilometers, centimeters, inches, feet, yards, and miles with exact factors.", summary:"Metric and imperial: from millimeters to miles.", category:"conversores", keywords:["convert meters to feet","length converter","inches to centimeters"], about:["Convert between metric and imperial units using internationally defined factors."], steps:["Enter the amount you want to convert.","Choose the source and destination units.","Check the result and the quick equivalences table."], faq:[{q:"How many centimeters are in an inch?",a:"Exactly 2.54 centimeters by international definition."},{q:"How many meters is a foot?",a:"One foot equals exactly 0.3048 meters."}] },
  { slug:"conversor-de-peso", name:"Weight converter", title:"Weight converter: kg, pounds, and ounces | UtiliHub", description:"Convert kilograms, grams, tonnes, pounds, ounces, and stones with standard conversion factors.", summary:"Kilograms, grams, pounds, ounces, stones, and tonnes.", category:"conversores", keywords:["convert kg to pounds","weight converter","ounces to grams"], about:["Convert mass units using the kilogram as the base unit. In everyday use people say weight, although these units physically measure mass."], steps:["Enter the source amount.","Select the from and to units.","Copy the result or review common equivalences."], faq:[{q:"How many pounds is a kilo?",a:"One kilogram is approximately 2.20462 pounds."},{q:"What is a stone?",a:"A British unit equal to 14 pounds."}] },
  { slug:"conversor-de-unidades", name:"Unit converter", title:"All-in-one unit converter | UtiliHub", description:"Convert length, weight, temperature, volume, area, and time from a single tool, with no signup.", summary:"Length, weight, temperature, volume, area, and time.", category:"conversores", keywords:["unit converter","convert units","online converter"], about:["A single converter for the most common quantities: length, mass, temperature, volume, area, and time. Each quantity uses standard factors."], steps:["Choose the quantity you want to convert.","Enter the value and select the units.","The result appears immediately."], faq:[{q:"Which quantities are available?",a:"Length, mass, temperature, volume, area, and time."},{q:"Are the factors exact?",a:"Internationally defined factors are used; the result is only rounded for display."}] }
];

export const toolBySlug = (slug: string) => TOOLS.find(t => t.slug === slug);
export const categoryBySlug = (slug: string) => CATEGORIES.find(c => c.slug === slug);
export const toolsByCategory = (slug: CategorySlug) => TOOLS.filter(t => t.category === slug);
