export type UnitDef={id:string;name:string;symbol:string;factor:number};
export type Magnitude={id:string;name:string;base:string;units:UnitDef[]};
export const LENGTH_UNITS:UnitDef[]=[{id:"mm",name:"Millimeter",symbol:"mm",factor:.001},{id:"cm",name:"Centimeter",symbol:"cm",factor:.01},{id:"m",name:"Meter",symbol:"m",factor:1},{id:"km",name:"Kilometer",symbol:"km",factor:1000},{id:"in",name:"Inch",symbol:"in",factor:.0254},{id:"ft",name:"Foot",symbol:"ft",factor:.3048},{id:"yd",name:"Yard",symbol:"yd",factor:.9144},{id:"mi",name:"Mile",symbol:"mi",factor:1609.344},{id:"nmi",name:"Nautical mile",symbol:"nmi",factor:1852}];
export const MASS_UNITS:UnitDef[]=[{id:"mg",name:"Milligram",symbol:"mg",factor:.000001},{id:"g",name:"Gram",symbol:"g",factor:.001},{id:"kg",name:"Kilogram",symbol:"kg",factor:1},{id:"t",name:"Tonne",symbol:"t",factor:1000},{id:"oz",name:"Ounce",symbol:"oz",factor:.028349523125},{id:"lb",name:"Pound",symbol:"lb",factor:.45359237},{id:"st",name:"Stone",symbol:"st",factor:6.35029318}];
export const VOLUME_UNITS:UnitDef[]=[{id:"ml",name:"Milliliter",symbol:"ml",factor:.001},{id:"l",name:"Liter",symbol:"l",factor:1},{id:"m3",name:"Cubic meter",symbol:"m³",factor:1000},{id:"cup",name:"Cup (US)",symbol:"cup",factor:.2365882365},{id:"pt",name:"Pint (US)",symbol:"pt",factor:.473176473},{id:"gal",name:"Gallon (US)",symbol:"gal",factor:3.785411784}];
export const AREA_UNITS:UnitDef[]=[{id:"cm2",name:"Square centimeter",symbol:"cm²",factor:.0001},{id:"m2",name:"Square meter",symbol:"m²",factor:1},{id:"ha",name:"Hectare",symbol:"ha",factor:10000},{id:"km2",name:"Square kilometer",symbol:"km²",factor:1000000},{id:"ft2",name:"Square foot",symbol:"ft²",factor:.09290304},{id:"ac",name:"Acre",symbol:"ac",factor:4046.8564224}];
export const TIME_UNITS:UnitDef[]=[{id:"s",name:"Second",symbol:"s",factor:1},{id:"min",name:"Minute",symbol:"min",factor:60},{id:"h",name:"Hour",symbol:"h",factor:3600},{id:"d",name:"Day",symbol:"d",factor:86400},{id:"wk",name:"Week",symbol:"wk",factor:604800}];
export const MAGNITUDES:Magnitude[]=[{id:"length",name:"Length",base:"m",units:LENGTH_UNITS},{id:"mass",name:"Mass",base:"kg",units:MASS_UNITS},{id:"volume",name:"Volume",base:"l",units:VOLUME_UNITS},{id:"area",name:"Area",base:"m²",units:AREA_UNITS},{id:"time",name:"Time",base:"s",units:TIME_UNITS}];
export function convert(value:number,from:UnitDef,to:UnitDef){return value*from.factor/to.factor;}
export function formatNumber(value:number,maxDigits=6){if(!Number.isFinite(value))return "—";if(value!==0&&Math.abs(value)<.000001)return value.toExponential(4);return new Intl.NumberFormat("en-US",{maximumFractionDigits:maxDigits}).format(value);}
export function parseNumber(input:string){const normalized=input.replace(/\s/g,"").replace(",",".");if(normalized===""||normalized==="-")return NaN;return Number(normalized);}
