export interface UnitDef { id:string; name:string; symbol:string; factor:number; }
export interface Magnitude { id:string; name:string; base:string; units:UnitDef[]; }
export const LENGTH_UNITS:UnitDef[]=[{id:"mm",name:"Milímetro",symbol:"mm",factor:.001},{id:"cm",name:"Centímetro",symbol:"cm",factor:.01},{id:"m",name:"Metro",symbol:"m",factor:1},{id:"km",name:"Kilómetro",symbol:"km",factor:1000},{id:"in",name:"Pulgada",symbol:"in",factor:.0254},{id:"ft",name:"Pie",symbol:"ft",factor:.3048},{id:"yd",name:"Yarda",symbol:"yd",factor:.9144},{id:"mi",name:"Milla",symbol:"mi",factor:1609.344},{id:"nmi",name:"Milla náutica",symbol:"nmi",factor:1852}];
export const MASS_UNITS:UnitDef[]=[{id:"mg",name:"Miligramo",symbol:"mg",factor:.000001},{id:"g",name:"Gramo",symbol:"g",factor:.001},{id:"kg",name:"Kilogramo",symbol:"kg",factor:1},{id:"t",name:"Tonelada",symbol:"t",factor:1000},{id:"oz",name:"Onza",symbol:"oz",factor:.028349523125},{id:"lb",name:"Libra",symbol:"lb",factor:.45359237},{id:"st",name:"Stone",symbol:"st",factor:6.35029318}];
export const VOLUME_UNITS:UnitDef[]=[{id:"ml",name:"Mililitro",symbol:"ml",factor:.001},{id:"l",name:"Litro",symbol:"l",factor:1},{id:"m3",name:"Metro cúbico",symbol:"m³",factor:1000},{id:"cup",name:"Taza (US)",symbol:"cup",factor:.2365882365},{id:"pt",name:"Pinta (US)",symbol:"pt",factor:.473176473},{id:"gal",name:"Galón (US)",symbol:"gal",factor:3.785411784}];
export const AREA_UNITS:UnitDef[]=[{id:"cm2",name:"Centímetro cuadrado",symbol:"cm²",factor:.0001},{id:"m2",name:"Metro cuadrado",symbol:"m²",factor:1},{id:"ha",name:"Hectárea",symbol:"ha",factor:10000},{id:"km2",name:"Kilómetro cuadrado",symbol:"km²",factor:1000000},{id:"ft2",name:"Pie cuadrado",symbol:"ft²",factor:.09290304},{id:"ac",name:"Acre",symbol:"ac",factor:4046.8564224}];
export const TIME_UNITS:UnitDef[]=[{id:"s",name:"Segundo",symbol:"s",factor:1},{id:"min",name:"Minuto",symbol:"min",factor:60},{id:"h",name:"Hora",symbol:"h",factor:3600},{id:"d",name:"Día",symbol:"d",factor:86400},{id:"wk",name:"Semana",symbol:"sem",factor:604800}];
export const MAGNITUDES:Magnitude[]=[{id:"length",name:"Longitud",base:"m",units:LENGTH_UNITS},{id:"mass",name:"Masa / peso",base:"kg",units:MASS_UNITS},{id:"volume",name:"Volumen",base:"l",units:VOLUME_UNITS},{id:"area",name:"Superficie",base:"m²",units:AREA_UNITS},{id:"time",name:"Tiempo",base:"s",units:TIME_UNITS}];
export function convert(value:number,from:UnitDef,to:UnitDef){return value*from.factor/to.factor;}
export function formatNumber(value:number,maxDigits=6){if(!Number.isFinite(value))return "—";if(value!==0&&Math.abs(value)<.000001)return value.toExponential(4);return new Intl.NumberFormat("es-ES",{maximumFractionDigits:maxDigits}).format(value);}
export function parseNumber(input:string){const normalized=input.replace(/\s/g,"").replace(",",".");if(normalized===""||normalized==="-")return NaN;return Number(normalized);}