import type {GeneralCategory} from "./types";
export const GENERAL_CATEGORIES:GeneralCategory[]=[
{slug:"matematicas",name:"Matemáticas",title:"Herramientas matemáticas online | UtiliHub",description:"Calculadoras matemáticas y estadísticas gratuitas.",intro:"Operaciones, estadística, probabilidad y conversiones numéricas en el navegador."},
{slug:"texto",name:"Texto",title:"Herramientas de texto online | UtiliHub",description:"Utilidades para limpiar, transformar y analizar texto.",intro:"Procesa texto localmente: cuenta, transforma, compara y limpia contenido."},
{slug:"desarrollo",name:"Desarrollo",title:"Herramientas para desarrolladores | UtiliHub",description:"JSON, Base64, URL, HTML, hashes, UUID y utilidades web.",intro:"Herramientas rápidas para desarrollo web y datos, ejecutadas en el navegador."},
{slug:"conversiones",name:"Conversores",title:"Conversores online | UtiliHub",description:"Conversores de unidades, números, color y datos.",intro:"Convierte magnitudes, bases numéricas, colores y formatos comunes."},
{slug:"fechas",name:"Fecha y tiempo",title:"Herramientas de fecha y tiempo | UtiliHub",description:"Calcula intervalos, plazos, edades y tiempos.",intro:"Utilidades para calendarios, fechas, horas y zonas horarias."},
{slug:"generadores",name:"Generadores",title:"Generadores online | UtiliHub",description:"Generadores aleatorios y utilidades creativas gratuitas.",intro:"Genera UUID, números, colores, nombres, slugs y datos de prueba."},
{slug:"diseno",name:"Diseño y color",title:"Herramientas de diseño y color | UtiliHub",description:"Color, contraste, gradientes y CSS.",intro:"Pequeñas herramientas para diseñadores y desarrolladores frontend."},
{slug:"seguridad",name:"Seguridad",title:"Herramientas de seguridad | UtiliHub",description:"Codificación, hashes y utilidades de seguridad locales.",intro:"Herramientas que priorizan procesamiento local y no requieren registro."},
{slug:"ciencia",name:"Ciencia",title:"Calculadoras científicas | UtiliHub",description:"Física, electricidad, densidad, energía y conversiones científicas.",intro:"Fórmulas científicas comunes con resultados inmediatos."},
{slug:"productividad",name:"Productividad",title:"Herramientas de productividad | UtiliHub",description:"Temporizadores, horas, prioridades y organización.",intro:"Utilidades sencillas para organizar tareas y tiempo."},
{slug:"educacion",name:"Educación",title:"Creadores de tests educativos | UtiliHub",description:"Creadores de tests para primaria, secundaria y universidad en 12 materias.",intro:"Crea cuestionarios por materia y tema, selecciona nivel y dificultad, y genera una evaluación lista para resolver."},
{slug:"archivos-documentos",name:"Archivos y documentos",title:"Herramientas para archivos y documentos online | UtiliHub",description:"Utilidades locales para archivos, documentos, texto, CSV, JSONL, Markdown y formatos comunes.",intro:"Procesa archivos y documentos directamente en el navegador, sin subirlos cuando la operación es local."},
{slug:"redes-internet",name:"Redes e Internet",title:"Herramientas de redes e Internet | UtiliHub",description:"Calculadoras IP, CIDR, URL, HTTP, puertos y utilidades web locales.",intro:"Analiza direcciones, URLs, protocolos y formatos de Internet sin realizar conexiones externas."},
{slug:"imagenes",name:"Imágenes",title:"Herramientas de imágenes online | UtiliHub",description:"Procesamiento y análisis de imágenes directamente en el navegador.",intro:"Redimensiona, transforma y analiza imágenes localmente con Canvas y APIs del navegador."},
{slug:"audio-video",name:"Audio y vídeo",title:"Herramientas de audio y vídeo | UtiliHub",description:"Calculadoras de bitrate, FPS, timecode, resolución y metadatos multimedia.",intro:"Calcula parámetros audiovisuales y lee metadatos básicos de archivos multimedia localmente."},
{slug:"geografia-mapas",name:"Geografía y mapas",title:"Herramientas de geografía y mapas | UtiliHub",description:"Coordenadas, distancias, rumbos, GeoJSON, Geohash y conversiones geográficas.",intro:"Calcula y transforma coordenadas geográficas sin necesidad de servicios de mapas externos."},
];
