import {makeTool} from "./types";
import {DEV_EXTRA_TOOLS} from "./dev-extra";
const d=(s:string,n:string,k:string,summary:string)=>makeTool(s,n,"desarrollo",k,summary);
export const DEV_TOOLS=[
 d("json-formatter","JSON Formatter","code","Formatea JSON para hacerlo legible."),d("json-validator","JSON Validator","code","Valida sintaxis JSON y muestra errores."),d("json-minifier","JSON Minifier","code","Minifica JSON eliminando espacios innecesarios."),d("json-a-csv","JSON a CSV","code","Convierte arrays JSON sencillos a CSV."),d("json-a-yaml","JSON a YAML","code","Convierte estructuras JSON simples a YAML."),
 d("base64-encode","Base64 Encode","encode","Codifica texto a Base64."),d("base64-decode","Base64 Decode","encode","Decodifica Base64 a texto."),d("url-encode","URL Encode","encode","Codifica componentes de URL."),d("url-decode","URL Decode","encode","Decodifica componentes de URL."),d("html-encode","HTML Encode","encode","Escapa caracteres especiales para HTML."),d("html-decode","HTML Decode","encode","Decodifica entidades HTML comunes."),
 d("uuid-generator","UUID Generator","generator","Genera UUID v4 con aleatoriedad del navegador."),d("random-id-generator","Generador de identificadores","generator","Genera un identificador aleatorio corto directamente en el navegador."),d("timestamp-generator","Timestamp Unix","date","Convierte fecha y hora a Unix timestamp."),d("timestamp-to-date","Timestamp a fecha","date","Convierte Unix timestamp a fecha legible."),d("http-status","HTTP Status Lookup","lookup","Consulta el significado de códigos HTTP."),d("mime-types","MIME Type Lookup","lookup","Consulta tipos MIME habituales."),d("regex-tester","Regex Tester","text","Prueba expresiones regulares contra texto local."),d("regex-escape","Regex Escape","text","Escapa caracteres especiales para expresiones regulares."),d("slug-generator","Slug Generator","text","Convierte títulos en slugs URL amigables."),d("html-minifier","HTML Minifier","code","Reduce HTML sencillo eliminando espacios superfluos."),d("css-minifier","CSS Minifier","code","Minifica CSS básico localmente."),d("javascript-minifier","JavaScript Minifier","code","Reduce espacios y comentarios simples de JavaScript."),
 ...DEV_EXTRA_TOOLS,
];
