import type { EducationDifficulty, EducationLevel } from "./education-engine";

type Q = { text: string; options: string[]; answer: string; levels: EducationLevel[]; difficulty: EducationDifficulty };
const q = (text: string, options: string[], answer: string, levels: EducationLevel[], difficulty: EducationDifficulty): Q => ({ text, options, answer, levels, difficulty });

export const EDUCATION_BANK_RELIEVE: Q[] = [
q("What is a plateau?", ["An elevated and relatively flat surface", "A depression that is always flooded", "An ocean current", "A layer of the atmosphere"], "An elevated and relatively flat surface", ["primaria"], "facil"),
q("What is a valley?", ["A low area between higher ground", "An underwater mountain", "An exclusively coastal plain", "An active volcano"], "A low area between higher ground", ["primaria"], "facil"),
q("Which external agent can erode a mountain?", ["Water", "Visible light", "Magnetic field", "Lunar gravity exclusively"], "Water", ["primaria"], "facil"),
q("Which landform usually has a high summit?", ["Mountain", "Delta", "Ocean basin", "Beach"], "Mountain", ["primaria"], "facil"),
q("What is a plain?", ["An extensive surface with gentle slopes", "A vertical rock wall", "A deep underwater depression", "A volcanic chimney"], "An extensive surface with gentle slopes", ["primaria"], "facil"),
q("Which process wears down and transports surface materials?", ["Erosion", "Photosynthesis", "Evaporation", "Combustion"], "Erosion", ["primaria"], "facil"),
q("Which agent can transport sediment via a river?", ["Water", "Sound", "Electricity", "Light"], "Water", ["primaria"], "facil"),
q("What is a volcano?", ["A structure through which magma or lava can exit", "A depression caused only by rain", "A marine current", "A permanent cloud"], "A structure through which magma or lava can exit", ["primaria"], "facil"),
q("Which process can form a river canyon over long periods?", ["Water erosion", "Freezing of the air", "Soil evaporation", "Solar reflection"], "Water erosion", ["secundaria"], "media"),
q("What is the main difference between a hill and a mountain?", ["A mountain usually has greater elevation and more marked relief", "A hill is always underwater", "Mountains never have slopes", "Hills are always volcanic"], "A mountain usually has greater elevation and more marked relief", ["secundaria"], "media"),
q("What is a glacier?", ["A large mass of ice that moves slowly", "Molten rock", "A saltwater river", "A tropical soil layer"], "A large mass of ice that moves slowly", ["secundaria"], "media"),
q("Which landform can result from sediment accumulation at a river mouth?", ["Delta", "Plateau", "Mountain range", "Crater"], "Delta", ["secundaria"], "media"),
q("Which process transports particles from an eroded area to another?", ["Sediment transport", "Atmospheric crystallization", "Photosynthesis", "Magnetization"], "Sediment transport", ["secundaria"], "media"),
q("Which agent can modify landforms through expansion and contraction of rocks due to temperature changes?", ["Temperature variation", "Starlight", "Sound", "Ocean salinity always"], "Temperature variation", ["secundaria"], "media"),
q("What is weathering?", ["Alteration or breakdown of rocks where they stand", "Exclusive plate movement", "Cloud formation", "Ocean motion"], "Alteration or breakdown of rocks where they stand", ["secundaria"], "media"),
q("What is one difference between weathering and erosion?", ["Weathering alters rock in place; erosion involves removal and transport", "Erosion occurs only inside the Earth", "Weathering always transports sediment", "They are identical processes"], "Weathering alters rock in place; erosion involves removal and transport", ["secundaria"], "media"),
q("Which erosional agent often acts more intensely in areas of heavy rain and steep slopes?", ["Runoff water", "Visible radiation", "Sound", "Electric field"], "Runoff water", ["secundaria"], "media"),
q("Which formation is associated with deposition of river-transported sediment at its mouth?", ["A delta", "An oceanic ridge", "A batholith", "A glacier"], "A delta", ["secundaria"], "media"),
q("What is a drainage basin?", ["The area whose waters drain into the same river system", "A mountain chain without rivers", "An exclusively marine zone", "A deep layer of the mantle"], "The area whose waters drain into the same river system", ["secundaria"], "media"),
q("What relationship exists between slope and surface runoff?", ["A steeper slope can favor faster runoff, depending on ground conditions", "Slope never affects water", "A steeper slope always stops runoff", "Runoff depends only on temperature"], "A steeper slope can favor faster runoff, depending on ground conditions", ["secundaria"], "media"),
q("Which landform forms by the uplift of large blocks of the Earth's crust?", ["A mountain range or mountain system", "A delta", "A beach", "Exclusively a dune"], "A mountain range or mountain system", ["secundaria"], "media"),
q("What is a depression in the land surface?", ["An area whose surface is lower than the surrounding areas", "An always volcanic elevation", "An air current", "A metamorphic rock"], "An area whose surface is lower than the surrounding areas", ["secundaria"], "media"),
q("How can wind modify landforms in arid regions?", ["By eroding, transporting, and depositing particles", "Freezing rivers", "Creating magma", "Stopping solar radiation"], "By eroding, transporting, and depositing particles", ["secundaria"], "media"),
q("Which formation can result from accumulation of wind-blown sand?", ["Dune", "Delta", "River canyon", "Fjord"], "Dune", ["secundaria"], "media"),
q("What is a fjord?", ["A glacial valley partially occupied by the sea", "A coastal dune", "A volcanic plain", "A desert plateau"], "A glacial valley partially occupied by the sea", ["secundaria"], "media"),
q("Which glacial process can excavate and widen valleys?", ["Erosion caused by the movement of ice", "Evaporation", "Combustion", "Photosynthesis"], "Erosion caused by the movement of ice", ["secundaria"], "media"),
q("Which geological factor can control landform shape over the long term?", ["Plate tectonics", "Daily rotation of the Sun", "Air composition only", "Sound pressure"], "Plate tectonics", ["universidad"], "dificil"),
q("What generally happens when one tectonic plate converges with another and one subducts?", ["One plate sinks under another and can help form trenches and volcanism", "Both disappear in the atmosphere", "A plain always forms without deformation", "The ocean ceases to have water"], "One plate sinks under another and can help form trenches and volcanism", ["universidad"], "dificil"),
q("Which geomorphic process dominates in a landscape where water carves channels and transports sediment?", ["Fluvial dynamics", "Wind dynamics exclusively", "Glacial activity exclusively", "Crystallization"], "Fluvial dynamics", ["universidad"], "dificil"),
q("What condition favors karst formation in soluble rocks such as limestone?", ["Water circulation that dissolves rock", "Total absence of water", "Melting of the crust", "Constant atmospheric pressure"], "Water circulation that dissolves rock", ["universidad"], "dificil"),
q("What is a river terrace?", ["A stepped surface representing former levels of a valley or channel", "A beach formed by wind", "A layer of magma", "An underwater dune"], "A stepped surface representing former levels of a valley or channel", ["universidad"], "dificil"),
q("What can river terraces at different heights indicate?", ["Changes in base level, tectonic uplift, or variations in discharge and climate", "That the river never moved", "That the area was always ice-covered", "That erosion never existed"], "Changes in base level, tectonic uplift, or variations in discharge and climate", ["universidad"], "dificil"),
q("Which process can generate coastal landforms through wave action and marine erosion?", ["Cliff retreat and formation of abrasion platforms", "Magma formation", "Crustal uplift by photosynthesis", "Freezing of the tropical ocean"], "Cliff retreat and formation of abrasion platforms", ["universidad"], "dificil"),
q("What largely controls slope stability against landslides?", ["The balance between resisting forces and forces that favor movement", "Only slope length", "Only the time of day", "Distance from the equator exclusively"], "The balance between resisting forces and forces that favor movement", ["universidad"], "dificil"),
q("Why can intense rainfall increase landslide risk on a slope?", ["Water can increase pore pressure and reduce the effective strength of the material", "Water always solidifies the soil", "Rain removes gravity", "Rain stops weathering"], "Water can increase pore pressure and reduce the effective strength of the material", ["universidad"], "dificil"),
q("Which principle explains that a river tends to deposit sediment when its transport capacity decreases?", ["When energy or transport capacity decreases, particles can settle", "Particles turn into magma", "Water loses mass automatically", "Landforms cease to exist"], "When energy or transport capacity decreases, particles can settle", ["universidad"], "dificil"),
q("What feature distinguishes structural relief from mainly erosional relief?", ["Structural relief is strongly controlled by the arrangement and resistance of the rocks", "Structural relief does not depend on rocks", "Erosional relief only appears under the sea", "There is no difference"], "Structural relief is strongly controlled by the arrangement and resistance of the rocks", ["universidad"], "dificil"),
q("What is isostasy in geomorphology?", ["Approximate gravitational balance between the lithosphere and underlying mantle", "Erosion produced by wind", "Groundwater circulation", "Dune formation"], "Approximate gravitational balance between the lithosphere and underlying mantle", ["universidad"], "dificil"),
q("How can the retreat of large ice masses modify landforms at a regional scale?", ["It can produce isostatic rebound as load on the lithosphere decreases", "It makes gravity disappear", "It turns all rocks into sediment", "It prevents any tectonic motion"], "It can produce isostatic rebound as load on the lithosphere decreases", ["universidad"], "dificil"),
q("What best describes a cycle of landscape erosion?", ["The evolution of landforms through uplift, weathering, erosion, transport, and sedimentation", "Daily repetition of climate", "Earth's rotation", "Exclusive formation of volcanoes"], "The evolution of landforms through uplift, weathering, erosion, transport, and sedimentation", ["universidad"], "dificil")
];

export default EDUCATION_BANK_RELIEVE;
