import type { EducationDifficulty, EducationLevel } from "./education-engine";

type Q={text:string;options:string[];answer:string;levels?:EducationLevel[];difficulty?:EducationDifficulty};
const q=(text:string,options:string[],answer:string,levels?:EducationLevel[],difficulty?:EducationDifficulty):Q=>({text,options,answer,levels,difficulty});

export const EDUCATION_BANK_B:Record<string,Q[]>={
 mapas:[q("What does a map scale represent?",["Ratio between map distance and real distance","Height of a mountain","Average temperature","Population density"],"Ratio between map distance and real distance"),q("Which imaginary line divides Earth into northern and southern hemispheres?",["Equator","Greenwich Meridian","Tropic of Cancer","Arctic Circle"],"Equator")],
 relieve:[q("What is a plateau?",["An elevated relatively flat surface","A deep valley","An ocean current","A type of cloud"],"An elevated relatively flat surface"),q("Which agent can shape the landforms?",["Erosion","Photosynthesis","Inflation","Monetary convection"],"Erosion")],
 clima:[q("What distinguishes climate from weather?",["Climate describes long-term patterns","Climate changes every minute","They are exactly the same","Weather is only measured with maps"],"Climate describes long-term patterns"),q("Which factor influences climate?",["Latitude","Spelling","Currency type","Language"],"Latitude")],
 poblacion:[q("Which indicator expresses births per population in a period?",["Birth rate","GDP","Interest rate","Mineral density"],"Birth rate"),q("What does population density measure?",["Inhabitants per unit of area","Exports per year","Average temperature","Absolute births"],"Inhabitants per unit of area")],
 "geografia-economica":[q("What does economic geography study?",["Spatial distribution of economic activities","Only landforms","Only languages","Only astronomy"],"Spatial distribution of economic activities"),q("Which sector includes agriculture and fishing?",["Primary","Secondary","Tertiary","Quaternary only"],"Primary")],
 vocabulario:[q("Which is an approximate synonym of 'rapid'?",["fast","slow","late","weak"],"fast"),q("What is the antonym of 'early'?",["late","fast","small","easy"],"late")],
 "gramatica-ingles":[q("Choose the correct sentence:",["She goes to school.","She go to school.","She going school.","She gone school."],"She goes to school."),q("Choose the correct past form of 'go':",["went","goed","goes","going"],"went")],
 reading:[q("What is the main idea of a text?",["The central message","The longest word","The last comma","The page number"],"The central message"),q("What does skimming mean?",["Reading quickly for the general idea","Memorizing every word","Translating only titles","Ignoring the text"],"Reading quickly for the general idea")],
 verbos:[q("What is the past of 'write'?",["wrote","writed","writtened","wroted"],"wrote"),q("What is the past participle of 'eat'?",["eaten","ate","eated","eating"],"eaten")],
 writing:[q("What helps structure a paragraph?",["A topic sentence and supporting details","Only random words","No punctuation","Mixing languages without purpose"],"A topic sentence and supporting details"),q("What is a draft?",["A preliminary version of a text","The final published book","A dictionary entry","A spelling rule"],"A preliminary version of a text")],
 algoritmos:[q("What is an algorithm?",["A finite sequence of steps to solve a problem","A type of virus","A computer brand","A programming language only"],"A finite sequence of steps to solve a problem"),q("What does a flowchart represent?",["The flow of a process or algorithm","Only hardware","Only passwords","Only databases"],"The flow of a process or algorithm")],
 programacion:[q("What is a variable in programming?",["A named storage for a value","A permanent constant only","A type of monitor","A network cable"],"A named storage for a value"),q("What is a loop used for?",["Repeating instructions","Deleting the code","Compiling the OS","Formatting a disk"],"Repeating instructions")],
 "bases-datos":[q("What is a database?",["An organized collection of data","A type of keyboard","A power supply","A programming paradigm only"],"An organized collection of data"),q("What does SQL mainly do?",["Query and manage relational data","Design logos","Edit photos","Stream audio"],"Query and manage relational data")],
 redes:[q("What does IP identify on a network?",["A device address","A file format","A font style","A battery type"],"A device address"),q("What is a router used for?",["Forwarding packets between networks","Printing documents","Cooling the CPU","Storing only images"],"Forwarding packets between networks")],
 "seguridad-digital":[q("What is a strong password characteristic?",["Length and mix of character types","Only the user's name","A single digit","A public shared phrase"],"Length and mix of character types"),q("What is phishing?",["Fraudulent attempt to obtain sensitive data","A backup method","A compression algorithm","A type of firewall only"],"Fraudulent attempt to obtain sensitive data")],
 microeconomia:[q("What does microeconomics study?",["Individual agents and markets","Only national GDP","Only global trade","Only fiscal policy"],"Individual agents and markets"),q("What happens to demand when price rises, other things equal?",["Quantity demanded falls","Quantity demanded always rises","Supply disappears","Taxes become zero"],"Quantity demanded falls")],
 macroeconomia:[q("What does macroeconomics study?",["The economy as a whole","Only one firm","Only one consumer","Only one product"],"The economy as a whole"),q("What is GDP?",["Value of goods and services produced in a period","A type of tax only","A stock index only","A currency exchange only"],"Value of goods and services produced in a period")],
 mercados:[q("What is a market?",["A place or system where buyers and sellers interact","Only a physical building","Only a stock exchange","Only online shops"],"A place or system where buyers and sellers interact"),q("What is equilibrium price?",["Price where quantity supplied equals quantity demanded","The highest possible price","The lowest wage","A fixed tax rate"],"Price where quantity supplied equals quantity demanded")],
 "finanzas-basicas":[q("What is interest?",["Cost of borrowing money or return on saving","A type of product","A labor tax only","A shipping fee only"],"Cost of borrowing money or return on saving"),q("What is a budget?",["A plan of income and expenses","A loan contract only","A stock option","A currency peg"],"A plan of income and expenses")],
 "economia-internacional":[q("What is an export?",["A good or service sold abroad","A domestic-only purchase","A local tax","A bank deposit"],"A good or service sold abroad"),q("What is an exchange rate?",["Price of one currency in terms of another","A local wage","A product barcode","A tariff only"],"Price of one currency in terms of another")],
 logica:[q("What is a valid argument?",["Conclusion follows from the premises","Any popular opinion","Any emotional claim","Any long text"],"Conclusion follows from the premises"),q("What is a contradiction?",["A statement that cannot be true","A synonym","A metaphor","A statistic"],"A statement that cannot be true")],
 etica:[q("What does ethics study?",["Moral principles and right action","Only grammar","Only physics formulas","Only map scales"],"Moral principles and right action"),q("What is a moral dilemma?",["A situation that poses conflict between values or duties","A math equation","A historical date","A chemical reaction"],"A situation that poses conflict between values or duties")],
 epistemologia:[q("What does epistemology study?",["Knowledge and its justification","Markets","Anatomy","Meteorology"],"Knowledge and its justification"),q("Which question is epistemological?",["How do we know that something is true?","How tall is a tree?","What is the temperature?","What is the price?"],"How do we know that something is true?")],
 "filosofia-politica":[q("What does political philosophy analyze?",["Power, the State, justice, and social organization","Only art","Only chemistry","Only grammar"],"Power, the State, justice, and social organization"),q("Which concept relates to the legitimacy of power?",["Authority","Photosynthesis","Density","Morphology"],"Authority")],
 "historia-filosofia":[q("Which period includes Socrates, Plato, and Aristotle?",["Ancient philosophy","Medieval philosophy","Contemporary philosophy","Postmodern philosophy"],"Ancient philosophy"),q("Who wrote 'The Republic'?",["Plato","Aristotle","Descartes","Kant"],"Plato")],
 materia:[q("Which is a state of matter?",["Solid","Gravity","Speed","Energy"],"Solid"),q("Which change goes from solid to liquid?",["Melting","Evaporation","Condensation","Sublimation"],"Melting")],
 "energia-naturales":[q("Which unit corresponds to energy?",["joule (J)","newton (N)","pascal (Pa)","ampere (A)"],"joule (J)"),q("Which source is renewable?",["Solar","Coal","Oil","Natural gas"],"Solar")],
 tierra:[q("What is Earth's solid outer layer called?",["Crust","Inner core","Outer core","Mantle"],"Crust"),q("Which movement produces day and night?",["Rotation","Revolution","Precession","Nutation"],"Rotation")],
 ambiente:[q("Which action helps reduce waste?",["Reduce and reuse","Increase disposables","Burn waste without control","Mix everything"],"Reduce and reuse"),q("Which gas is an important greenhouse gas?",["CO₂","O₂","N₂","He"],"CO₂")],
 "metodo-cientifico":[q("What is usually done after stating a hypothesis?",["Test it by observation or experiment","Turn it into a law immediately","Delete the data","Avoid controls"],"Test it by observation or experiment"),q("What is a control group for?",["Compare and evaluate the effect of a variable","Always increase sample size","Eliminate the hypothesis","Change the result"],"Compare and evaluate the effect of a variable")],
};
