import type { EducationDifficulty, EducationLevel } from "./education-engine";

type Q={text:string;options:string[];answer:string;levels?:EducationLevel[];difficulty?:EducationDifficulty};
const q=(text:string,options:string[],answer:string,levels?:EducationLevel[],difficulty?:EducationDifficulty):Q=>({text,options,answer,levels,difficulty});

export const EDUCATION_BANK_B:Record<string,Q[]>={
 mapas:[q("¿Qué representa una escala cartográfica?",["Relación entre distancia del mapa y distancia real","Altura de una montaña","Temperatura media","Densidad de población"],"Relación entre distancia del mapa y distancia real"),q("¿Qué línea imaginaria divide la Tierra en hemisferios norte y sur?",["Ecuador","Meridiano de Greenwich","Trópico de Cáncer","Círculo Polar Ártico"],"Ecuador")],
 relieve:[q("¿Qué es una meseta?",["Superficie elevada relativamente llana","Valle profundo","Corriente marina","Tipo de nube"],"Superficie elevada relativamente llana"),q("¿Qué agente puede modelar el relieve?",["Erosión","Fotosíntesis","Inflación","Convección monetaria"],"Erosión")],
 clima:[q("¿Qué diferencia al clima del tiempo atmosférico?",["El clima describe patrones de largo plazo","El clima cambia cada minuto","Son exactamente iguales","El tiempo solo se mide con mapas"],"El clima describe patrones de largo plazo"),q("¿Qué factor influye en el clima?",["Latitud","Ortografía","Tipo de moneda","Idioma"],"Latitud")],
 poblacion:[q("¿Qué indicador expresa nacimientos por población en un periodo?",["Tasa de natalidad","PIB","Tasa de interés","Densidad mineral"],"Tasa de natalidad"),q("¿Qué mide la densidad de población?",["Habitantes por unidad de superficie","Exportaciones por año","Temperatura media","Nacimientos absolutos"],"Habitantes por unidad de superficie")],
 "geografia-economica":[q("¿Qué estudia la geografía económica?",["Distribución espacial de actividades económicas","Solo accidentes geográficos","Solo idiomas","Solo astronomía"],"Distribución espacial de actividades económicas"),q("¿Qué sector incluye agricultura y pesca?",["Primario","Secundario","Terciario","Cuaternario exclusivamente"],"Primario")],
 vocabulario:[q("¿Cuál es un sinónimo aproximado de 'rapid'?",["fast","slow","late","weak"],"fast"),q("¿Cuál es el antónimo de 'early'?",["late","fast","small","easy"],"late")],
 "gramatica-ingles":[q("Choose the correct sentence:",["She goes to school.","She go to school.","She going school.","She gone school."],"She goes to school."),q("Choose the correct past form: 'They ___ yesterday.'",["went","go","goes","going"],"went")],
 reading:[q("In reading comprehension, what is the main idea?",["The central message","A random detail","The longest word","The title only"],"The central message"),q("What is an inference?",["A conclusion supported by clues","A copied word","A title","A punctuation mark"],"A conclusion supported by clues")],
 verbos:[q("What is the past tense of 'go'?",["went","goed","gone","going"],"went"),q("Which is a modal verb?",["can","table","quickly","house"],"can")],
 writing:[q("Which helps organize an English essay?",["A clear thesis and paragraphs","Random sentences","No punctuation","Only questions"],"A clear thesis and paragraphs"),q("What is a topic sentence?",["A sentence that states the paragraph's main idea","The final punctuation","A list of sources","A title only"],"A sentence that states the paragraph's main idea")],
 algoritmos:[q("¿Qué es un algoritmo?",["Secuencia finita de pasos para resolver un problema","Tipo de monitor","Base de datos física","Lenguaje natural"],"Secuencia finita de pasos para resolver un problema"),q("¿Qué propiedad implica que un algoritmo termine?",["Finitud","Ambigüedad","Aleatoriedad","Infinidad"],"Finitud")],
 programacion:[q("¿Qué estructura permite repetir instrucciones?",["Bucle","Variable","Comentario","Literal"],"Bucle"),q("¿Qué almacena normalmente una variable?",["Un valor que puede cambiar","Solo comentarios","El hardware","Una página web"],"Un valor que puede cambiar")],
 "bases-datos":[q("¿Qué identifica de forma única una fila en una tabla?",["Clave primaria","CSS","HTML","Una imagen"],"Clave primaria"),q("¿Qué lenguaje se usa habitualmente para consultar bases de datos relacionales?",["SQL","CSS","SVG","Markdown"],"SQL")],
 redes:[q("¿Qué protocolo se usa para resolver nombres de dominio?",["DNS","HTTP","FTP","SMTP"],"DNS"),q("¿Qué dirección identifica una interfaz de red?",["MAC","URL","HTML","CSS"],"MAC")],
 "seguridad-digital":[q("¿Qué práctica mejora la seguridad de una cuenta?",["Usar contraseñas únicas y MFA","Reutilizar una contraseña","Compartir códigos","Desactivar actualizaciones"],"Usar contraseñas únicas y MFA"),q("¿Qué es phishing?",["Un intento de engaño para obtener información","Un sistema de archivos","Una red local","Un algoritmo de compresión"],"Un intento de engaño para obtener información")],
 microeconomia:[q("¿Qué ocurre normalmente con la demanda si sube el precio, manteniendo lo demás constante?",["Tiende a disminuir","Siempre aumenta","No puede cambiar","Se vuelve infinita"],"Tiende a disminuir"),q("¿Qué representa el coste de oportunidad?",["El valor de la mejor alternativa sacrificada","Solo el precio monetario","Un impuesto","La inflación"],"El valor de la mejor alternativa sacrificada")],
 macroeconomia:[q("¿Qué mide el PIB?",["Valor de bienes y servicios finales producidos","Solo exportaciones","Solo deuda","Solo inflación"],"Valor de bienes y servicios finales producidos"),q("¿Qué suele ocurrir con el poder adquisitivo cuando sube la inflación y los ingresos no cambian?",["Disminuye","Aumenta siempre","No cambia","Se duplica"],"Disminuye")],
 mercados:[q("¿Qué es una acción?",["Una participación en el capital de una empresa","Un préstamo bancario","Un impuesto","Un bono del Estado siempre"],"Una participación en el capital de una empresa"),q("¿Qué mide una capitalización bursátil?",["Valor de mercado de las acciones de una empresa","Solo sus ventas","Solo su deuda","Su tasa de interés"],"Valor de mercado de las acciones de una empresa")],
 "finanzas-basicas":[q("¿Qué es el interés compuesto?",["Interés calculado también sobre intereses acumulados","Una comisión fija","Una tasa siempre negativa","Un impuesto"],"Interés calculado también sobre intereses acumulados"),q("¿Qué es el capital inicial?",["Cantidad invertida o prestada al comienzo","Interés final","Impuesto","Comisión bancaria"],"Cantidad invertida o prestada al comienzo")],
 "economia-internacional":[q("¿Qué mide una balanza comercial?",["Diferencia entre exportaciones e importaciones de bienes","Solo inflación","Solo desempleo","Solo deuda interna"],"Diferencia entre exportaciones e importaciones de bienes"),q("¿Qué es una exportación?",["Venta de bienes o servicios al exterior","Compra al exterior","Impuesto interno","Producción doméstica solamente"],"Venta de bienes o servicios al exterior")],
 logica:[q("Si todos A son B y todos B son C, ¿qué se deduce?",["Todos A son C","Ningún A es C","Todos C son A","No hay relación"],"Todos A son C"),q("¿Qué estudia la lógica formal?",["Estructuras de razonamiento válido","Solo emociones","Solo historia","Solo gramática"],"Estructuras de razonamiento válido")],
 etica:[q("¿Qué estudia la ética?",["Problemas sobre acción, valores y deberes","Composición de rocas","Movimiento planetario","Sintaxis"],"Problemas sobre acción, valores y deberes"),q("¿Qué es un dilema ético?",["Situación que plantea un conflicto entre valores o deberes","Una ecuación","Una fecha histórica","Una reacción química"],"Situación que plantea un conflicto entre valores o deberes")],
 epistemologia:[q("¿Qué estudia la epistemología?",["El conocimiento y su justificación","Los mercados","La anatomía","La meteorología"],"El conocimiento y su justificación"),q("¿Qué pregunta es epistemológica?",["¿Cómo sabemos que algo es verdadero?","¿Cuánto mide un árbol?","¿Qué temperatura hace?","¿Cuál es el precio?"],"¿Cómo sabemos que algo es verdadero?")],
 "filosofia-politica":[q("¿Qué analiza la filosofía política?",["Poder, Estado, justicia y organización social","Solo arte","Solo química","Solo gramática"],"Poder, Estado, justicia y organización social"),q("¿Qué concepto se relaciona con la legitimidad del poder?",["Autoridad","Fotosíntesis","Densidad","Morfología"],"Autoridad")],
 "historia-filosofia":[q("¿Qué periodo incluye a Sócrates, Platón y Aristóteles?",["Filosofía antigua","Filosofía medieval","Filosofía contemporánea","Filosofía posmoderna"],"Filosofía antigua"),q("¿Quién escribió 'La República'?",["Platón","Aristóteles","Descartes","Kant"],"Platón")],
 materia:[q("¿Cuál es un estado de la materia?",["Sólido","Gravedad","Velocidad","Energía"],"Sólido"),q("¿Qué cambio pasa de sólido a líquido?",["Fusión","Evaporación","Condensación","Sublimación"],"Fusión")],
 "energia-naturales":[q("¿Qué unidad corresponde a energía?",["joule (J)","newton (N)","pascal (Pa)","ampere (A)"],"joule (J)"),q("¿Qué fuente es renovable?",["Solar","Carbón","Petróleo","Gas natural"],"Solar")],
 tierra:[q("¿Qué capa sólida externa de la Tierra se llama corteza?",["Corteza","Núcleo interno","Núcleo externo","Manto"],"Corteza"),q("¿Qué movimiento produce el día y la noche?",["Rotación","Traslación","Precesión","Nutación"],"Rotación")],
 ambiente:[q("¿Qué acción ayuda a reducir residuos?",["Reducir y reutilizar","Aumentar descartables","Quemar residuos sin control","Mezclar todo"],"Reducir y reutilizar"),q("¿Qué gas es un importante gas de efecto invernadero?",["CO₂","O₂","N₂","He"],"CO₂")],
 "metodo-cientifico":[q("¿Qué suele hacerse después de formular una hipótesis?",["Ponerla a prueba mediante observación o experimento","Convertirla en ley inmediatamente","Eliminar los datos","Evitar controles"],"Ponerla a prueba mediante observación o experimento"),q("¿Para qué sirve un grupo de control?",["Comparar y evaluar el efecto de una variable","Aumentar siempre la muestra","Eliminar la hipótesis","Cambiar el resultado"],"Comparar y evaluar el efecto de una variable")],
};
