// Education bank source; GitHub Actions expands each topic to 20 unique questions after validation.
import type { EducationDifficulty, EducationLevel } from "./education-engine";

type Q={text:string;options:string[];answer:string;levels?:EducationLevel[];difficulty?:EducationDifficulty};
const q=(text:string,options:string[],answer:string,levels?:EducationLevel[],difficulty?:EducationDifficulty):Q=>({text,options,answer,levels,difficulty});

export const EDUCATION_BANK_A:Record<string,Q[]>={
 aritmetica:[q("¿Cuál es el resultado de 24 + 18?",["42","40","44","46"],"42"),q("¿Cuál es el resultado de 7 × 8?",["56","48","54","64"],"56")],
 algebra:[q("Si 3x = 21, ¿cuánto vale x?",["7","6","8","9"],"7"),q("¿Cuál es el resultado de x + 5 = 12?",["7","5","17","-7"],"7")],
 geometria:[q("¿Cuál es el área de un rectángulo de 8 cm × 5 cm?",["40 cm²","26 cm²","13 cm²","80 cm²"],"40 cm²"),q("¿Cuántos grados suman los ángulos interiores de un triángulo?",["180°","90°","270°","360°"],"180°")],
 calculo:[q("¿Cuál es la derivada de x²?",["2x","x","x²","2"],"2x"),q("¿Cuál es una primitiva de 2x?",["x²","2x²","x","2"],"x²")],
 estadistica:[q("¿Cuál es el promedio de 4, 6 y 8?",["6","5","7","18"],"6"),q("¿Qué medida representa el valor central de un conjunto ordenado?",["Mediana","Varianza","Rango","Frecuencia"],"Mediana")],
 gramatica:[q("¿Cuál de estas palabras es un sustantivo?",["montaña","rápidamente","correr","azul"],"montaña"),q("¿Qué función cumple normalmente un verbo?",["Expresar una acción o estado","Nombrar objetos","Conectar párrafos","Indicar únicamente lugares"],"Expresar una acción o estado")],
 ortografia:[q("¿Cuál está escrita correctamente?",["excepción","exepción","eccepción","exección"],"excepción"),q("¿Cuál palabra lleva tilde?",["camión","mesa","casa","pared"],"camión")],
 comprension:[q("¿Qué identifica mejor la idea principal de un texto?",["El mensaje central","El dato más largo","La última palabra","El número de párrafos"],"El mensaje central"),q("¿Qué permite una inferencia?",["Deducir información a partir de pistas del texto","Copiar una frase","Cambiar el título","Eliminar evidencias"],"Deducir información a partir de pistas del texto")],
 literatura:[q("¿Qué es una metáfora?",["Una comparación implícita","Una biografía","Una lista de fechas","Una regla ortográfica"],"Una comparación implícita"),q("¿Qué es el narrador?",["La voz que cuenta la historia","El autor siempre","El lector","El título"],"La voz que cuenta la historia")],
 redaccion:[q("¿Qué mejora la claridad de un texto argumentativo?",["Una tesis clara y argumentos ordenados","Repetir ideas","Eliminar conectores","Usar frases inconexas"],"Una tesis clara y argumentos ordenados"),q("¿Qué función tienen los conectores?",["Relacionar ideas","Eliminar párrafos","Cambiar el tema","Contar caracteres"],"Relacionar ideas")],
 mecanica:[q("Con 5 kg y 4 m/s², ¿qué fuerza resulta?",["20 N","9 N","1,25 N","25 N"],"20 N"),q("¿Cuál es la unidad SI de fuerza?",["newton (N)","joule (J)","watt (W)","pascal (Pa)"],"newton (N)")],
 "energia-fisica":[q("¿Cuál es la unidad SI de energía?",["joule (J)","newton (N)","pascal (Pa)","watt (W)"],"joule (J)"),q("¿Qué expresión corresponde a energía cinética clásica?",["½mv²","mgh","F/a","V/R"],"½mv²")],
 electricidad:[q("¿Qué unidad mide la corriente eléctrica?",["ampere (A)","volt (V)","ohm (Ω)","watt (W)"],"ampere (A)"),q("Según la ley de Ohm, V es igual a…",["I·R","I/R","R/I","I+R"],"I·R")],
 ondas:[q("¿Qué magnitud se mide en hertz (Hz)?",["Frecuencia","Energía","Masa","Presión"],"Frecuencia"),q("¿Qué relación básica existe entre velocidad, frecuencia y longitud de onda?",["v=fλ","v=f/λ","v=λ/f","v=f+λ"],"v=fλ")],
 "fisica-moderna":[q("¿Qué relación expresa E = mc²?",["Equivalencia entre masa y energía","Ley de Ohm","Ley de Hooke","Conservación de carga"],"Equivalencia entre masa y energía"),q("¿Qué partícula tiene carga negativa?",["Electrón","Protón","Neutrón","Fotón"],"Electrón")],
 atomos:[q("¿Qué partícula tiene carga negativa?",["Electrón","Protón","Neutrón","Núcleo"],"Electrón"),q("¿Dónde se encuentran protones y neutrones?",["En el núcleo","En la corteza electrónica","En los fotones","En los orbitales solamente"],"En el núcleo")],
 estequiometria:[q("¿Qué representa aproximadamente un mol?",["6,022×10²³ entidades","1 gramo","1 litro","100 entidades"],"6,022×10²³ entidades"),q("¿Qué ley permite relacionar cantidades de reactivos y productos mediante ecuaciones balanceadas?",["Estequiometría","Ley de Hooke","Ley de Ohm","Ley de Snell"],"Estequiometría")],
 organica:[q("¿Qué elemento es central en la química orgánica?",["Carbono","Helio","Sodio","Hierro"],"Carbono"),q("¿Qué grupo funcional caracteriza a un alcohol?",["-OH","-COOH","-NH₂","-CHO"],"-OH")],
 equilibrio:[q("En equilibrio químico, las velocidades directa e inversa son…",["Iguales","Ambas siempre cero","Una siempre cero","Infinitas"],"Iguales"),q("¿Qué principio predice el desplazamiento de un equilibrio ante una perturbación?",["Le Châtelier","Arquímedes","Pascal","Bernoulli"],"Le Châtelier")],
 "quimica-general":[q("¿Qué mide el pH?",["Acidez o basicidad","Masa atómica","Densidad","Temperatura"],"Acidez o basicidad"),q("¿Cuál es aproximadamente el pH de una disolución neutra a 25 °C?",["7","0","14","1"],"7")],
 celula:[q("¿Qué estructura contiene el material genético en una célula eucariota?",["Núcleo","Ribosoma","Membrana","Vacuola"],"Núcleo"),q("¿Qué orgánulo produce gran parte del ATP celular?",["Mitocondria","Ribosoma","Lisosoma","Golgi"],"Mitocondria")],
 genetica:[q("¿Qué molécula almacena la información genética?",["ADN","ATP","Glucosa","Lípido"],"ADN"),q("¿Qué es un alelo?",["Una variante de un gen","Una célula","Un tejido","Un orgánulo"],"Una variante de un gen")],
 evolucion:[q("¿Qué mecanismo puede producir adaptación poblacional?",["Selección natural","Osmosis","Fotosíntesis","Fermentación"],"Selección natural"),q("¿Qué proceso cambia las frecuencias de variantes genéticas a lo largo de generaciones?",["Evolución","Digestión","Respiración","Transcripción"],"Evolución")],
 ecologia:[q("¿Qué nivel incluye organismos y su entorno físico?",["Ecosistema","Célula","Órgano","Individuo"],"Ecosistema"),q("¿Qué relación alimentaria transfiere materia y energía entre organismos?",["Cadena trófica","Mitosis","Osmosis","Meiosis"],"Cadena trófica")],
 anatomia:[q("¿Qué órgano bombea sangre?",["Corazón","Pulmón","Hígado","Riñón"],"Corazón"),q("¿Qué sistema coordina respuestas mediante impulsos nerviosos?",["Sistema nervioso","Sistema digestivo","Sistema óseo","Sistema endocrino exclusivamente"],"Sistema nervioso")],
 antiguedad:[q("¿Qué civilización desarrolló la democracia ateniense?",["Grecia antigua","Roma medieval","Egipto moderno","China imperial"],"Grecia antigua"),q("¿Qué río fue fundamental para el desarrollo del antiguo Egipto?",["Nilo","Amazonas","Danubio","Támesis"],"Nilo")],
 "edad-media":[q("¿Qué sistema social caracterizó gran parte de la Europa medieval?",["Feudalismo","Fordismo","Socialismo","Industrialismo"],"Feudalismo"),q("¿Qué institución tuvo gran influencia en la Europa medieval?",["Iglesia cristiana","Bolsa moderna","ONU","Internet"],"Iglesia cristiana")],
 "edad-moderna":[q("¿Qué hecho se asocia convencionalmente con 1492?",["Llegada europea a América","Revolución francesa","Primera Guerra Mundial","Caída de Roma"],"Llegada europea a América"),q("¿Qué proceso transformó Europa mediante nuevos métodos de producción desde los siglos XVIII-XIX?",["Revolución Industrial","Renacimiento","Cruzadas","Neolítico"],"Revolución Industrial")],
 "edad-contemporanea":[q("¿En qué año comenzó la Revolución francesa?",["1789","1492","1810","1914"],"1789"),q("¿En qué año comenzó la Primera Guerra Mundial?",["1914","1939","1905","1945"],"1914")],
 "historia-argentina":[q("¿En qué año comenzó la Revolución de Mayo?",["1810","1816","1853","1880"],"1810"),q("¿En qué año se declaró la independencia argentina?",["1816","1810","1820","1853"],"1816")],
};
