import type { EducationDifficulty, EducationLevel } from "./education-engine";

type Q = { text: string; options: string[]; answer: string; levels: EducationLevel[]; difficulty: EducationDifficulty };
const q = (text: string, options: string[], answer: string, levels: EducationLevel[], difficulty: EducationDifficulty): Q => ({ text, options, answer, levels, difficulty });

export const EDUCATION_BANK_RELIEVE: Q[] = [
q("¿Qué es una meseta?", ["Una superficie elevada y relativamente llana", "Una depresión siempre inundada", "Una corriente oceánica", "Una capa de la atmósfera"], ["Una superficie elevada y relativamente llana"][0], ["primaria"], "facil"),
q("¿Qué es un valle?", ["Una zona baja entre elevaciones del terreno", "Una montaña submarina", "Una llanura costera exclusivamente", "Un volcán activo"], "Una zona baja entre elevaciones del terreno", ["primaria"], "facil"),
q("¿Qué agente externo puede erosionar una montaña?", ["El agua", "La luz visible", "El campo magnético", "La gravedad lunar exclusivamente"], "El agua", ["primaria"], "facil"),
q("¿Qué forma del relieve suele tener una cima elevada?", ["Montaña", "Delta", "Cuenca oceánica", "Playa"], "Montaña", ["primaria"], "facil"),
q("¿Qué es una llanura?", ["Una superficie extensa con pendientes suaves", "Una pared rocosa vertical", "Una depresión submarina profunda", "Una chimenea volcánica"], "Una superficie extensa con pendientes suaves", ["primaria"], "facil"),
q("¿Qué proceso desgasta y transporta materiales de la superficie?", ["Erosión", "Fotosíntesis", "Evaporación", "Combustión"], "Erosión", ["primaria"], "facil"),
q("¿Qué agente puede transportar sedimentos mediante un río?", ["El agua", "El sonido", "La electricidad", "La luz"], "El agua", ["primaria"], "facil"),
q("¿Qué es un volcán?", ["Una estructura por la que puede salir magma o lava", "Una depresión causada solo por lluvia", "Una corriente marina", "Una nube permanente"], "Una estructura por la que puede salir magma o lava", ["primaria"], "facil"),
q("¿Qué proceso puede formar un cañón fluvial durante largos periodos?", ["La erosión del agua", "La congelación del aire", "La evaporación del suelo", "La reflexión solar"], "La erosión del agua", ["secundaria"], "media"),
q("¿Qué diferencia principal hay entre una colina y una montaña?", ["La montaña suele presentar mayor elevación y relieve más marcado", "La colina siempre está bajo el agua", "La montaña nunca tiene pendientes", "La colina siempre es volcánica"], "La montaña suele presentar mayor elevación y relieve más marcado", ["secundaria"], "media"),
q("¿Qué es un glaciar?", ["Una gran masa de hielo que se desplaza lentamente", "Una roca fundida", "Un río de agua salada", "Una capa de suelo tropical"], "Una gran masa de hielo que se desplaza lentamente", ["secundaria"], "media"),
q("¿Qué relieve puede producir la acumulación de sedimentos en la desembocadura de un río?", ["Delta", "Meseta", "Cordillera", "Cráter"], "Delta", ["secundaria"], "media"),
q("¿Qué proceso transporta partículas desde una zona erosionada hacia otra?", ["Transporte de sedimentos", "Cristalización atmosférica", "Fotosíntesis", "Magnetización"], "Transporte de sedimentos", ["secundaria"], "media"),
q("¿Qué agente puede modificar el relieve mediante expansión y contracción de las rocas por cambios térmicos?", ["La variación de temperatura", "La luz de las estrellas", "El sonido", "La salinidad del océano siempre"], "La variación de temperatura", ["secundaria"], "media"),
q("¿Qué es la meteorización?", ["La alteración o desintegración de rocas en el lugar donde se encuentran", "El desplazamiento de placas exclusivamente", "La formación de nubes", "El movimiento de los océanos"], "La alteración o desintegración de rocas en el lugar donde se encuentran", ["secundaria"], "media"),
q("¿Cuál es una diferencia entre meteorización y erosión?", ["La meteorización altera la roca in situ; la erosión implica remoción y transporte", "La erosión ocurre solo en el interior terrestre", "La meteorización siempre transporta sedimentos", "Son procesos idénticos"], "La meteorización altera la roca in situ; la erosión implica remoción y transporte", ["secundaria"], "media"),
q("¿Qué agente erosivo suele actuar con mayor intensidad en zonas de fuertes lluvias y pendientes?", ["El agua de escorrentía", "La radiación visible", "El sonido", "El campo eléctrico"], "El agua de escorrentía", ["secundaria"], "media"),
q("¿Qué formación está asociada con el depósito de sedimentos transportados por un río en su desembocadura?", ["Un delta", "Una dorsal oceánica", "Un batolito", "Un glaciar"], "Un delta", ["secundaria"], "media"),
q("¿Qué es una cuenca hidrográfica?", ["El territorio cuyas aguas drenan hacia un mismo sistema fluvial", "Una cadena de montañas sin ríos", "Una zona exclusivamente marina", "Una capa profunda del manto"], "El territorio cuyas aguas drenan hacia un mismo sistema fluvial", ["secundaria"], "media"),
q("¿Qué relación existe entre pendiente y escorrentía superficial?", ["Una pendiente mayor puede favorecer una escorrentía más rápida, según las condiciones del terreno", "La pendiente nunca afecta al agua", "Una pendiente mayor detiene siempre la escorrentía", "La escorrentía depende solo de la temperatura"], "Una pendiente mayor puede favorecer una escorrentía más rápida, según las condiciones del terreno", ["secundaria"], "media"),
q("¿Qué relieve se forma por la elevación de grandes bloques de la corteza terrestre?", ["Una cordillera o sistema montañoso", "Un delta", "Una playa", "Una duna exclusivamente"], "Una cordillera o sistema montañoso", ["secundaria"], "media"),
q("¿Qué es una depresión del relieve?", ["Una zona cuya superficie está más baja que las áreas que la rodean", "Una elevación siempre volcánica", "Una corriente de aire", "Una roca metamórfica"], "Una zona cuya superficie está más baja que las áreas que la rodean", ["secundaria"], "media"),
q("¿Cómo puede el viento modificar el relieve en regiones áridas?", ["Erosionando, transportando y depositando partículas", "Congelando ríos", "Creando magma", "Deteniendo la radiación solar"], "Erosionando, transportando y depositando partículas", ["secundaria"], "media"),
q("¿Qué formación puede originarse por acumulación de arena transportada por el viento?", ["Duna", "Delta", "Cañón fluvial", "Fiordo"], "Duna", ["secundaria"], "media"),
q("¿Qué es un fiordo?", ["Un valle de origen glaciar parcialmente ocupado por el mar", "Una duna costera", "Una llanura volcánica", "Una meseta desértica"], "Un valle de origen glaciar parcialmente ocupado por el mar", ["secundaria"], "media"),
q("¿Qué proceso glaciar puede excavar y ensanchar valles?", ["La erosión causada por el movimiento del hielo", "La evaporación", "La combustión", "La fotosíntesis"], "La erosión causada por el movimiento del hielo", ["secundaria"], "media"),
q("¿Qué factor geológico puede controlar la forma del relieve a largo plazo?", ["La tectónica de placas", "La rotación diaria del Sol", "La composición del aire únicamente", "La presión sonora"], "La tectónica de placas", ["universidad"], "dificil"),
q("¿Qué ocurre en términos generales cuando una placa tectónica converge con otra y una de ellas subduce?", ["Una placa se introduce bajo otra y puede contribuir a formar fosas y volcanismo", "Ambas desaparecen en la atmósfera", "Se forma siempre una llanura sin deformación", "El océano deja de tener agua"], "Una placa se introduce bajo otra y puede contribuir a formar fosas y volcanismo", ["universidad"], "dificil"),
q("¿Qué proceso geomorfológico domina en un paisaje donde el agua excava cauces y transporta sedimentos?", ["La dinámica fluvial", "La dinámica eólica exclusivamente", "La actividad glacial exclusivamente", "La cristalización"], "La dinámica fluvial", ["universidad"], "dificil"),
q("¿Qué condición favorece la formación de karst en rocas solubles como la caliza?", ["La circulación de agua que disuelve la roca", "La ausencia total de agua", "La fusión de la corteza", "La presión atmosférica constante"], "La circulación de agua que disuelve la roca", ["universidad"], "dificil"),
q("¿Qué es una terraza fluvial?", ["Una superficie escalonada que representa antiguos niveles de un valle o cauce", "Una playa formada por viento", "Una capa de magma", "Una duna submarina"], "Una superficie escalonada que representa antiguos niveles de un valle o cauce", ["universidad"], "dificil"),
q("¿Qué puede indicar la presencia de terrazas fluviales a distintas alturas?", ["Cambios en el nivel de base, levantamiento tectónico o variaciones del caudal y clima", "Que el río nunca se desplazó", "Que la zona siempre estuvo cubierta por hielo", "Que no existió erosión"], "Cambios en el nivel de base, levantamiento tectónico o variaciones del caudal y clima", ["universidad"], "dificil"),
q("¿Qué proceso puede generar un relieve costero por acción conjunta del oleaje y la erosión marina?", ["Retroceso de acantilados y formación de plataformas de abrasión", "Formación de magma", "Elevación de la corteza por fotosíntesis", "Congelación del océano tropical"], "Retroceso de acantilados y formación de plataformas de abrasión", ["universidad"], "dificil"),
q("¿Qué controla en gran medida la estabilidad de una ladera frente a deslizamientos?", ["La relación entre fuerzas resistentes y fuerzas que favorecen el movimiento", "Solo la longitud de la ladera", "Solo la hora del día", "La distancia al ecuador exclusivamente"], "La relación entre fuerzas resistentes y fuerzas que favorecen el movimiento", ["universidad"], "dificil"),
q("¿Por qué una lluvia intensa puede aumentar el riesgo de deslizamiento en una ladera?", ["El agua puede aumentar la presión de poros y reducir la resistencia efectiva del material", "El agua siempre solidifica el suelo", "La lluvia elimina la gravedad", "La lluvia detiene la meteorización"], "El agua puede aumentar la presión de poros y reducir la resistencia efectiva del material", ["universidad"], "dificil"),
q("¿Qué principio explica que un río tienda a depositar sedimentos cuando disminuye su capacidad de transporte?", ["Al disminuir la energía o capacidad de transporte, las partículas pueden sedimentarse", "Las partículas se convierten en magma", "El agua pierde masa automáticamente", "El relieve deja de existir"], "Al disminuir la energía o capacidad de transporte, las partículas pueden sedimentarse", ["universidad"], "dificil"),
q("¿Qué característica distingue a un relieve estructural de uno principalmente erosivo?", ["El relieve estructural está fuertemente condicionado por la disposición y resistencia de las rocas", "El relieve estructural no depende de las rocas", "El relieve erosivo solo aparece bajo el mar", "No existe diferencia"], "El relieve estructural está fuertemente condicionado por la disposición y resistencia de las rocas", ["universidad"], "dificil"),
q("¿Qué es la isostasia en geomorfología?", ["El equilibrio gravitacional aproximado entre la litosfera y el manto subyacente", "La erosión producida por el viento", "La circulación de aguas subterráneas", "La formación de dunas"], "El equilibrio gravitacional aproximado entre la litosfera y el manto subyacente", ["universidad"], "dificil"),
q("¿Cómo puede la retirada de grandes masas de hielo modificar el relieve a escala regional?", ["Puede producir rebote isostático al disminuir la carga sobre la litosfera", "Hace que la gravedad desaparezca", "Convierte todas las rocas en sedimentos", "Impide cualquier movimiento tectónico"], "Puede producir rebote isostático al disminuir la carga sobre la litosfera", ["universidad"], "dificil"),
q("¿Qué describe mejor un ciclo de erosión del relieve?", ["La evolución de las formas del terreno mediante levantamiento, meteorización, erosión, transporte y sedimentación", "La repetición diaria del clima", "La rotación de la Tierra", "La formación exclusiva de volcanes"], "La evolución de las formas del terreno mediante levantamiento, meteorización, erosión, transporte y sedimentación", ["universidad"], "dificil")
];

export default EDUCATION_BANK_RELIEVE;
