import {makeTool} from "./types";
const m=(s:string,n:string,k:string,summary:string,c:string={})=>makeTool(s,n,"matematicas",k,summary,n.toLowerCase().split(/\s+/),c);
export const MATH_TOOLS=[
 m("porcentaje","Percentage","number","Calculate percentages, increases, discounts, and proportions."),
 m("regla-de-tres","Rule of three","number","Solve direct and inverse proportions."),
 m("promedio","Average","stats","Calculate the arithmetic mean of a list of numbers."),
 m("mediana","Median","stats","Get the median of a data set."),
 m("moda","Mode","stats","Find the most frequent value or values."),
 m("rango","Statistical range","stats","Calculate the difference between maximum and minimum."),
 m("varianza","Variance","stats","Calculate the variance of a sample or population."),
 m("desviacion-estandar","Standard deviation","stats","Calculate the standard deviation of numeric data."),
 m("percentil","Percentile","stats","Calculate percentiles of an ordered data set."),
 m("cuartiles","Quartiles","stats","Get Q1, median, and Q3 of a series."),
 m("z-score","Z-score","stats","Calculate the z-score of a value."),
 m("correlacion","Correlation","stats","Calculate the correlation coefficient of two series."),
 m("covarianza","Covariance","stats","Calculate the covariance between two variables."),
 m("probabilidad","Probability","number","Calculate basic probabilities between 0 and 1."),
 m("combinaciones","Combinations","number","Calculate combinations without repetition."),
 m("permutaciones","Permutations","number","Calculate permutations without repetition."),
 m("factorial","Factorial","number","Calculate the factorial of a non-negative integer."),
 m("potencias-y-raices","Powers and roots","number","Calculate powers and square roots."),
 m("logaritmos","Logarithms","number","Calculate logarithms in base 10 or natural."),
 m("notacion-cientifica","Scientific notation","number","Convert numbers to scientific notation."),
 m("mcd-mcm","GCD and LCM","number","Calculate greatest common divisor and least common multiple."),
 m("secuencias","Number sequences","number","Generate terms of arithmetic and geometric sequences."),
 m("bases-numericas","Number bases","number","Convert numbers between common bases."),
];
