import { makeTool } from "./types";
const i = (s: string, n: string, k: string, summary: string, category: "conversiones" | "generadores" = "conversiones") => makeTool(s, n, category, k, summary);
export const MEDIA_TOOLS = [
  i("redimensionar-imagen", "Redimensionar imagen", "image", "Cambia dimensiones de imágenes localmente."), i("comprimir-imagen", "Comprimir imagen", "image", "Reduce tamaño de imágenes en el navegador."), i("png-a-jpg", "PNG a JPG", "image", "Convierte imágenes PNG a JPG localmente."), i("jpg-a-png", "JPG a PNG", "image", "Convierte imágenes JPG a PNG localmente."), i("webp-a-jpg", "WebP a JPG", "image", "Convierte WebP a JPG localmente."), i("jpg-a-webp", "JPG a WebP", "image", "Convierte JPG a WebP localmente."), i("favicon", "Generador de favicon", "image", "Crea un favicon desde una imagen local.", "generadores"), i("recortar-imagen", "Recortar imagen", "image", "Recorta imágenes directamente en el navegador."), i("rotar-imagen", "Rotar imagen", "image", "Rota imágenes sin subirlas a un servidor."), i("escala-grises", "Escala de grises", "image", "Convierte imágenes a escala de grises localmente."), i("color-dominante", "Color dominante", "image", "Extrae un color aproximado de una imagen."),
  i("unir-pdf", "Unir PDF", "pdf", "Une documentos PDF localmente cuando el navegador lo permite."), i("dividir-pdf", "Dividir PDF", "pdf", "Extrae páginas seleccionadas de un PDF."), i("imagenes-a-pdf", "Imágenes a PDF", "pdf", "Combina imágenes en un PDF local."), i("pdf-a-imagenes", "PDF a imágenes", "pdf", "Renderiza páginas PDF como imágenes en el navegador."), i("rotar-pdf", "Rotar PDF", "pdf", "Rota páginas seleccionadas de un PDF."), i("reordenar-pdf", "Reordenar PDF", "pdf", "Reordena páginas de un PDF."), i("extraer-texto-pdf", "Extraer texto de PDF", "pdf", "Extrae texto cuando el documento contiene texto seleccionable."),
  makeTool("inspector-metadatos-pdf", "Inspector de metadatos PDF", "conversiones", "document", "Lee páginas, título, autor, asunto y tamaño de un PDF local.", ["pdf", "metadatos", "documentos"], { mode: "document", operation: "pdf-metadata" }),
  makeTool("comparador-de-textos", "Comparador de textos", "texto", "document", "Compara dos versiones línea por línea y muestra diferencias.", ["comparar textos", "diff", "documentos"], { mode: "document", operation: "text-diff" }),
  makeTool("inspector-csv", "Inspector de CSV", "conversiones", "document", "Detecta filas, columnas, cabeceras duplicadas y registros incompletos.", ["csv", "datos", "archivos"], { mode: "document", operation: "csv-inspector" }),
  makeTool("markdown-a-html", "Markdown a HTML", "conversiones", "document", "Convierte Markdown básico a HTML escapado y listo para copiar.", ["markdown", "html", "documentos"], { mode: "document", operation: "markdown-html" }),
  makeTool("nombres-de-archivos-en-lote", "Nombres de archivos en lote", "texto", "document", "Normaliza una lista de títulos y genera nombres numerados consistentes.", ["archivos", "nombres", "organización"], { mode: "document", operation: "file-name-batch" }),
];
