import { makeTool } from "./types";
const i = (s: string, n: string, k: string, summary: string, category: "conversiones" | "generadores" = "conversiones") => makeTool(s, n, category, k, summary);
export const MEDIA_TOOLS = [
  i("redimensionar-imagen", "Resize image", "image", "Change image dimensions locally."), i("comprimir-imagen", "Compress image", "image", "Reduce image size in the browser."), i("png-a-jpg", "PNG to JPG", "image", "Convert PNG images to JPG locally."), i("jpg-a-png", "JPG to PNG", "image", "Convert JPG images to PNG locally."), i("webp-a-jpg", "WebP to JPG", "image", "Convert WebP to JPG locally."), i("jpg-a-webp", "JPG to WebP", "image", "Convert JPG to WebP locally."), i("favicon", "Favicon generator", "image", "Create a favicon from a local image.", "generadores"), i("recortar-imagen", "Crop image", "image", "Crop images directly in the browser."), i("rotar-imagen", "Rotate image", "image", "Rotate images without uploading them to a server."), i("escala-grises", "Grayscale", "image", "Convert images to grayscale locally."), i("color-dominante", "Dominant color", "image", "Extract an approximate color from an image."),
  i("unir-pdf", "Merge PDF", "pdf", "Merge PDF documents locally when the browser allows it."), i("dividir-pdf", "Split PDF", "pdf", "Extract selected pages from a PDF."), i("imagenes-a-pdf", "Images to PDF", "pdf", "Combine images into a local PDF."), i("pdf-a-imagenes", "PDF to images", "pdf", "Render PDF pages as images in the browser."), i("rotar-pdf", "Rotate PDF", "pdf", "Rotate selected PDF pages."), i("reordenar-pdf", "Reorder PDF", "pdf", "Reorder pages of a PDF."), i("extraer-texto-pdf", "Extract text from PDF", "pdf", "Extract text when the document contains selectable text."),
  makeTool("inspector-metadatos-pdf", "PDF metadata inspector", "conversiones", "document", "Read pages, title, author, subject, and size of a local PDF.", ["pdf", "metadata", "documents"], { mode: "document", operation: "pdf-metadata" }),
  makeTool("comparador-de-textos", "Text comparator", "texto", "document", "Compare two versions line by line and show differences.", ["compare text", "diff", "documents"], { mode: "document", operation: "text-diff" }),
  makeTool("inspector-csv", "CSV inspector", "conversiones", "document", "Detect rows, columns, duplicate headers, and incomplete records.", ["csv", "data", "files"], { mode: "document", operation: "csv-inspector" }),
  makeTool("markdown-a-html-avanzado", "Advanced Markdown to HTML", "conversiones", "document", "Convert basic Markdown to escaped HTML ready to copy.", ["markdown", "html", "documents"], { mode: "document", operation: "markdown-html" }),
  makeTool("nombres-de-archivos-en-lote", "Batch file names", "texto", "document", "Normalize a list of titles and generate consistent numbered names.", ["files", "names", "organization"], { mode: "document", operation: "file-name-batch" }),
];
