import { makeTool } from "./types";
const g = (s: string, n: string, k: string, summary: string, category: string = "generadores") => makeTool(s, n, category, k, summary);
export const MISC_TOOLS = [
  g("generador-numeros", "Random number generator", "generator", "Generate random numbers within a range."), g("generador-dados", "Dice roller", "generator", "Simulate configurable dice rolls."), g("generador-nombres", "Name generator", "generator", "Generate random names from local lists."), g("generador-usuarios", "Username generator", "generator", "Generate usernames for projects and testing."), g("generador-pin", "PIN generator", "generator", "Generate random numeric codes."), g("generador-codigos", "Code generator", "generator", "Generate random alphanumeric codes."),
  g("generador-paleta", "Palette generator", "design", "Generate color palettes from a base color.", "diseno"), g("generador-gradiente", "CSS gradient generator", "design", "Generate CSS for linear gradients.", "diseno"), g("contraste-wcag", "WCAG contrast", "design", "Check contrast between two colors.", "diseno"), g("selector-color", "Color picker", "design", "Explore colors and their HEX, RGB, and HSL values.", "diseno"), g("generador-sombra-css", "Box-shadow generator", "design", "Generate CSS shadow properties.", "diseno"), g("generador-border-radius", "Border-radius generator", "design", "Generate CSS rounded corner values.", "diseno"), g("css-text-shadow", "CSS text-shadow", "design", "Generate a CSS text-shadow property.", "diseno"), g("css-filter", "CSS filter", "design", "Generate a CSS filter property for visual effects.", "diseno"), g("css-grid-generator", "CSS Grid generator", "design", "Generate a three-column CSS Grid structure.", "diseno"), g("escala-tipografica", "Typographic scale", "design", "Generate a type scale based on a modular ratio.", "diseno"),
  g("hash-sha256", "SHA-256", "security", "Compute SHA-256 locally with Web Crypto.", "seguridad"), g("hash-sha512", "SHA-512", "security", "Compute SHA-512 locally with Web Crypto.", "seguridad"), g("checksum", "Checksum", "security", "Compute a SHA-256 checksum for local text.", "seguridad"), g("password-strength", "Password strength analyzer", "security", "Evaluate length, diversity, and approximate entropy.", "seguridad"), g("passphrase", "Passphrase generator", "security", "Generate random phrases for memorable credentials.", "seguridad"), g("hash-sha384", "SHA-384", "security", "Compute SHA-384 locally with Web Crypto.", "seguridad"), g("hash-sha1", "SHA-1 for compatibility", "security", "Compute SHA-1 locally for compatibility uses.", "seguridad"), g("hmac-sha256", "HMAC-SHA-256", "security", "Compute an HMAC-SHA-256 signature with a locally entered key.", "seguridad"), g("token-seguro", "Random token generator", "security", "Generate a cryptographically random hexadecimal token.", "seguridad"), g("comparador-hashes", "Hash comparator", "security", "Compare hash values entered by the user.", "seguridad"),
  g("generador-claves-api", "API key generator", "security", "Generate random API keys with an identifiable prefix and high entropy.", "seguridad"), g("analizador-entropia", "Entropy analyzer", "security", "Estimate password entropy from length and character variety.", "seguridad"), g("verificador-hash-multi", "Multi-hash verifier", "security", "Compute multiple hashes of text to compare integrity locally.", "seguridad"),
  g("datos-prueba", "Test data", "generator", "Generate names, IDs, and fake values for development."), g("sorteo", "Random draw", "generator", "Pick a random item from a list."), g("lista-aleatoria", "Shuffle list", "generator", "Shuffle a list randomly."),
  g("paleta-monocromatica", "Monochrome palette", "design", "Generate light and dark shades of a base color.", "diseno"), g("generador-css-clamp", "CSS clamp generator", "design", "Generate a clamp function for fluid typography.", "diseno"), g("sistema-espaciado", "Spacing system", "design", "Generate a consistent CSS spacing scale.", "diseno"),
  g("mezclador-de-colores", "Color mixer", "design", "Calculate the intermediate color between two HEX colors.", "diseno"), g("hex-a-hsl-avanzado", "Advanced HEX to HSL", "design", "Convert a HEX color into HSL and RGB values.", "diseno"), g("paleta-complementaria", "Complementary palette", "design", "Generate the complementary color and a split pair.", "diseno"),
  g("propina-y-cuenta-compartida", "Tip and split bill", "formula", "Calculate total, tip, and amount per person.", "utilidades"), g("regla-50-30-20", "50/30/20 rule", "formula", "Split income across needs, wants, and savings.", "utilidades"), g("horas-decimales", "Hours to decimal", "formula", "Convert hours, minutes, and seconds to decimal hours.", "utilidades"),
];
