import { createFileRoute, notFound, Link } from "@tanstack/react-router";
import { FINANCIAL_UI } from "@/components/financial/registry";
import { FavoriteButton } from "@/components/FavoriteButton";
import { ShareAndExportActions } from "@/components/ShareAndExportActions";
import { financialToolBySlug } from "@/lib/financial-tools";
import { absoluteUrl, breadcrumbSchema, cleanDescription, ogImage, webApplicationSchema } from "@/lib/seo";

export const Route = createFileRoute("/finanzas/$slug")({
  loader: ({ params }) => { const tool = financialToolBySlug(params.slug); if (!tool) throw notFound(); return { tool }; },
  head: ({ loaderData }) => loaderData ? (() => { const title = `${loaderData.tool.name} | UtiliHub`; const description = cleanDescription(loaderData.tool.description); const url = absoluteUrl(`/finanzas/${loaderData.tool.slug}`); return { meta: [{ title }, { name: "description", content: description }, { name: "keywords", content: loaderData.tool.keywords.join(", ") }, { name: "robots", content: "index, follow, max-image-preview:large" }, { property: "og:title", content: title }, { property: "og:description", content: description }, { property: "og:type", content: "website" }, { property: "og:url", content: url }, { property: "og:site_name", content: "UtiliHub" }, { property: "og:image", content: ogImage() }, { name: "twitter:card", content: "summary_large_image" }, { name: "twitter:title", content: title }, { name: "twitter:description", content: description }, { name: "twitter:image", content: ogImage() }], links: [{ rel: "canonical", href: url }], scripts: [{ type: "application/ld+json", children: JSON.stringify({ "@context": "https://schema.org", "@graph": [webApplicationSchema({ ...loaderData.tool, description }), breadcrumbSchema([{ name: "Inicio", path: "/" }, { name: "Finanzas", path: "/finanzas" }, { name: loaderData.tool.name }])] }) }] }; })() : { meta: [{ title: "Calculadora financiera no encontrada | UtiliHub" }, { name: "robots", content: "noindex" }] },
  component: FinancialPage,
});

function FinancialPage() {
  const { tool } = Route.useLoaderData();
  const ui = FINANCIAL_UI[tool.slug];
  if (!ui) throw new Error(`Missing financial UI for catalog tool: ${tool.slug}`);
  return <main className="container-page py-10 sm:py-14"><Link to="/finanzas" className="inline-flex items-center gap-2 text-sm font-semibold text-muted-foreground hover:text-primary"><span aria-hidden="true">←</span> Todas las calculadoras financieras</Link><div className="mt-7 flex flex-wrap items-start justify-between gap-4"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.14em] text-primary">Calculadora financiera</p><h1 className="mt-1 text-3xl font-black tracking-tight sm:text-4xl">{tool.name}</h1><p className="mt-3 text-base leading-7 text-muted-foreground">{tool.description}</p></div><FavoriteButton slug={tool.slug} name={tool.name} /></div><section data-tool-surface className="surface-card mt-8 p-5 sm:p-7" aria-label={tool.name}>{ui()}<ShareAndExportActions title={tool.name} /></section><section className="mt-10 grid gap-8 border-t border-border/70 pt-8 lg:grid-cols-2" aria-labelledby="financial-guide"><div><h2 id="financial-guide" className="text-xl font-black">Sobre esta calculadora</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{tool.description} Esta herramienta funciona en el navegador y ofrece una estimación matemática a partir de los valores que introduzcas.</p></div><div><h2 className="text-xl font-black">Cómo utilizarla</h2><ol className="mt-3 space-y-3 text-sm leading-6 text-muted-foreground"><li className="flex gap-3"><span className="grid size-6 shrink-0 place-items-center rounded-full bg-accent text-xs font-bold text-primary">1</span><span>Introduce los valores del escenario que quieres analizar.</span></li><li className="flex gap-3"><span className="grid size-6 shrink-0 place-items-center rounded-full bg-accent text-xs font-bold text-primary">2</span><span>Ejecuta el cálculo y revisa cada resultado.</span></li><li className="flex gap-3"><span className="grid size-6 shrink-0 place-items-center rounded-full bg-accent text-xs font-bold text-primary">3</span><span>Compara escenarios y verifica las condiciones reales antes de decidir.</span></li></ol></div></section><p className="mt-8 max-w-3xl text-xs leading-5 text-muted-foreground">Los resultados son estimaciones matemáticas. Verifica las condiciones reales de cualquier producto financiero antes de tomar decisiones.</p></main>;
}
