import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Check, Compass, Sparkles } from "lucide-react";
import { ToolSearch } from "@/components/ToolSearch";
import { FavoriteToolsSection } from "@/components/FavoriteToolsSection";
import { RecentToolsSection } from "@/components/RecentToolsSection";
import { AdBanner } from "@/components/AdBanner";
import { ALL_CATEGORIES, ALL_TOOLS, allToolsByCategory } from "@/lib/all-tools";
import { englishToolSlug } from "@/lib/route-slugs";
import { absoluteUrl, cleanDescription, ogImage, SITE_NAME, websiteSchema } from "@/lib/seo";

const title = "UtiliHub · Free online tools to solve it fast";
const description = cleanDescription("500+ free online tools to calculate, convert, study, and handle everyday tasks. Find the tool you need with no signup.");
const QUICK_TOOL_SLUGS = ["calculadora", "calculadora-de-porcentajes", "regla-de-tres", "calculadora-de-fechas", "contador-de-palabras", "generador-de-contrasenas", "conversor-de-temperatura", "conversor-de-unidades"];

export const Route = createFileRoute("/")({
  head: () => ({ meta: [{ title }, { name: "description", content: description }, { name: "keywords", content: "online tools, online calculators, converters, free tools, UtiliHub" }, { name: "robots", content: "index, follow, max-image-preview:large" }, { property: "og:title", content: title }, { property: "og:description", content: description }, { property: "og:type", content: "website" }, { property: "og:url", content: absoluteUrl("/") }, { property: "og:site_name", content: SITE_NAME }, { property: "og:image", content: ogImage() }, { name: "twitter:card", content: "summary_large_image" }, { name: "twitter:title", content: title }, { name: "twitter:description", content: description }, { name: "twitter:image", content: ogImage() }], links: [{ rel: "canonical", href: absoluteUrl("/") }, { rel: "alternate", hrefLang: "en", href: absoluteUrl("/") }, { rel: "alternate", hrefLang: "es", href: absoluteUrl("/es") }, { rel: "alternate", hrefLang: "x-default", href: absoluteUrl("/") }], scripts: [{ type: "application/ld+json", children: JSON.stringify(websiteSchema()) }] }),
  component: Home,
});

function Home() {
  const featuredCategories = ALL_CATEGORIES.slice(0, 9);
  const quickTools = QUICK_TOOL_SLUGS.map((slug) => ALL_TOOLS.find((tool) => tool.slug === slug)).filter((tool): tool is (typeof ALL_TOOLS)[number] => Boolean(tool));
  return <main className="pb-12">
    <section className="hero-gradient border-b border-border/70">
      <div className="container-page grid gap-8 py-10 sm:py-16 lg:grid-cols-[1.1fr_.9fr] lg:items-center lg:gap-12 lg:py-20">
        <div><div className="mb-4 inline-flex items-center gap-2 rounded-full border border-primary/20 bg-card/75 px-3 py-1.5 text-xs font-bold uppercase tracking-[.14em] text-primary"><Sparkles className="size-3.5" /> Hassle-free utilities</div><h1 className="max-w-3xl text-4xl font-black tracking-tight sm:text-5xl lg:text-6xl">Solve what you need in seconds.</h1><p className="mt-5 max-w-2xl text-base leading-7 text-muted-foreground sm:text-lg">Calculate, convert, study, and organize everyday tasks with free tools that run right in your browser.</p><div className="mt-7 flex flex-wrap gap-3"><Link to="/tools" className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-primary px-5 py-3 text-sm font-bold text-primary-foreground shadow-lift hover:-translate-y-0.5 hover:opacity-95">Browse tools <ArrowRight className="size-4" /></Link><Link to="/finance" className="inline-flex min-h-12 items-center gap-2 rounded-xl border border-border bg-card px-5 py-3 text-sm font-bold hover:border-primary/40 hover:bg-accent">View financial calculators</Link></div><div className="mt-7 flex flex-wrap gap-x-5 gap-y-2 text-xs font-semibold text-muted-foreground"><span className="flex items-center gap-1.5"><Check className="size-3.5 text-primary" /> No signup</span><span className="flex items-center gap-1.5"><Check className="size-3.5 text-primary" /> Free</span><span className="flex items-center gap-1.5"><Check className="size-3.5 text-primary" /> Local privacy</span></div></div>
        <div className="surface-card bg-card/80 p-3 shadow-lift sm:p-4"><div className="rounded-xl border border-border/70 bg-background p-4 sm:p-5"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-primary">Quick access</p><h2 className="mt-1 text-xl font-black">What do you want to solve?</h2></div><span className="rounded-full bg-accent px-2.5 py-1 text-xs font-bold text-accent-foreground">{ALL_TOOLS.length} tools</span></div><div className="mt-4"><ToolSearch compactHome /></div><div className="mt-4 grid grid-cols-2 gap-2 text-xs font-semibold sm:grid-cols-3">{featuredCategories.slice(0, 6).map((category) => <Link key={category.slug} to="/category/$slug" params={{ slug: category.slug }} className="rounded-lg border border-border/70 bg-card px-3 py-2.5 hover:border-primary/40 hover:bg-accent">{category.name}</Link>)}</div></div></div>
      </div>
    </section>
    <AdBanner />
    <div className="container-page">
      <section className="py-10 sm:py-12" aria-labelledby="shortcuts-title"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-primary">Start here</p><h2 id="shortcuts-title" className="mt-1 text-2xl font-black sm:text-3xl">Quick links</h2><p className="mt-2 text-sm text-muted-foreground">The most practical tools to start without browsing the full catalog.</p></div><Link to="/tools" className="hidden min-h-11 items-center gap-1 rounded-lg px-3 text-sm font-bold text-primary hover:bg-accent sm:inline-flex">View catalog <ArrowRight className="size-4" /></Link></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{quickTools.map((tool) => <Link key={tool.slug} to="/tools/$slug" params={{ slug: englishToolSlug(tool) }} className="group rounded-xl border border-border/70 bg-card p-4 hover:-translate-y-0.5 hover:border-primary/45 hover:shadow-lift"><span className="text-xs font-bold uppercase tracking-wide text-primary">{tool.category}</span><h3 className="mt-2 font-bold group-hover:text-primary">{tool.name}</h3><p className="mt-1 line-clamp-2 text-xs leading-5 text-muted-foreground">{tool.summary}</p></Link>)}</div></section>
      <FavoriteToolsSection /><RecentToolsSection />
      <section className="mt-10 border-t border-border/70 py-10" aria-labelledby="explore-categories"><div className="flex items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-primary">Explore by goal</p><h2 id="explore-categories" className="mt-1 text-2xl font-black">All categories</h2><p className="mt-2 text-sm text-muted-foreground">Find a collection of tools organized by task.</p></div><Link to="/tools" className="inline-flex min-h-11 items-center gap-1 rounded-lg px-3 text-sm font-bold text-primary hover:bg-accent">View all <ArrowRight className="size-4" /></Link></div><div className="mt-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{ALL_CATEGORIES.map((category) => <Link key={category.slug} to="/category/$slug" params={{ slug: category.slug }} className="group flex min-h-16 items-center justify-between rounded-xl border border-border/70 bg-card px-4 py-3 hover:border-primary/40 hover:bg-accent"><span><span className="block font-bold group-hover:text-primary">{category.name}</span><span className="mt-0.5 block text-xs text-muted-foreground">{category.description}</span></span><span className="ml-3 shrink-0 rounded-full bg-surface px-2.5 py-1 text-xs font-bold text-muted-foreground">{allToolsByCategory(category.slug).length}</span></Link>)}</div></section>
      <section className="grid gap-4 rounded-2xl border border-border/70 bg-surface/55 p-5 sm:grid-cols-[auto_1fr_auto] sm:items-center sm:p-6" aria-labelledby="about-title"><div className="grid size-12 place-items-center rounded-xl bg-accent text-primary"><Compass className="size-6" /></div><div><h2 id="about-title" className="font-black">A collection for your daily tasks</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">UtiliHub brings together calculators, converters, text tools, study, science, and productivity in one place.</p></div><Link to="/tools" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-bold text-primary-foreground hover:opacity-90">Open catalog <ArrowRight className="size-4" /></Link></section>
      <section className="mt-4 grid gap-4 rounded-2xl border border-primary/20 bg-accent/50 p-5 sm:grid-cols-[1fr_auto] sm:items-center sm:p-6" aria-labelledby="kits-title"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-primary">New · useful paths</p><h2 id="kits-title" className="mt-1 text-2xl font-black">Start from your goal, not from a tool.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Explore kits for freelancers, SEO and content, documents, and students, and chain the recommended next steps.</p></div><Link to="/kits" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-bold text-primary-foreground hover:opacity-90">View kits <ArrowRight className="size-4" /></Link></section>
    </div>
  </main>;
}