import type { EducationDifficulty, EducationLevel } from "../education-engine";
type Q={text:string;options:string[];answer:string;levels?:EducationLevel[];difficulty?:EducationDifficulty};
const q=(text:string,options:string[],answer:string,levels:EducationLevel[],difficulty:EducationDifficulty):Q=>({text,options,answer,levels,difficulty});
export const ALGEBRA:Q[]=[
q("If x + 7 = 15, what is the value of x?",["8","7","9","22"],"8",["primaria"],"facil"),
q("If 4x = 28, what is the value of x?",["7","6","8","9"],"7",["primaria"],"facil"),
q("What is the value of 3x + 2 when x = 5?",["17","15","12","20"],"17",["primaria"],"facil"),
q("Simplify 5x + 3x.",["8x","15x","8","2x"],"8x",["primaria"],"facil"),
q("What is the factored form of x² − 9?",["(x−3)(x+3)","(x−9)(x+1)","(x−3)²","x(x−9)"],"(x−3)(x+3)",["primaria"],"media"),
q("Solve 2x + 5 = 17.",["6","5","7","11"],"6",["primaria"],"facil"),
q("What is the slope of y = 3x − 4?",["3","−4","4","1/3"],"3",["primaria"],"media"),
q("What is the y-intercept of y = −2x + 9?",["9","−2","2","−9"],"9",["secundaria"],"media"),
q("If 2(x + 3) = 14, what is the value of x?",["4","5","7","2"],"4",["secundaria"],"media"),
q("Which solution satisfies x² = 49?",["x = 7 or x = −7","x = 49","x = 14","x = −49"],"x = 7 or x = −7",["secundaria"],"media"),
q("Simplify 2a + 5 − a + 3.",["a + 8","a + 2","3a + 8","a − 8"],"a + 8",["secundaria"],"media"),
q("If x/4 = 6, what is the value of x?",["24","10","12","2"],"24",["secundaria"],"facil"),
q("What is the expansion of (x + 2)²?",["x² + 4x + 4","x² + 4","x² + 2x + 4","x² + 4x + 2"],"x² + 4x + 4",["secundaria"],"media"),
q("Solve 3(x − 2) = 2x + 5.",["11","1","7","−11"],"11",["secundaria"],"media"),
q("If f(x)=2x−1, what is f(4)?",["7","8","6","9"],"7",["secundaria"],"facil"),
q("Which equation represents a horizontal line through y = 5?",["y = 5","x = 5","y = x + 5","y = 5x"],"y = 5",["secundaria"],"media"),
q("Solve the system x+y=10 and x−y=2.",["x=6, y=4","x=4, y=6","x=8, y=2","x=5, y=5"],"x=6, y=4",["secundaria"],"dificil"),
q("What is the domain of f(x)=1/(x−2)?",["All reals except 2","All reals","Only x>2","Only x<2"],"All reals except 2",["universidad"],"dificil"),
q("If 3^x = 81, what is the value of x?",["4","3","9","27"],"4",["universidad"],"media"),
q("Solve 2^x = 1/8.",["−3","3","−2","8"],"−3",["universidad"],"dificil"),
q("If 7x−4=31, what is the value of x?",["5","4","6","7"],"5",["secundaria"],"facil"),
q("Simplify 4y−2y+9.",["2y+9","6y+9","2y−9","4y+7"],"2y+9",["secundaria"],"facil"),
q("What are the roots of x²−16=0?",["4 and −4","16 and −16","4 only","−4 only"],"4 and −4",["secundaria"],"media"),
q("What is the vertex of y=(x−2)²+3?",["(2,3)","(−2,3)","(2,−3)","(3,2)"],"(2,3)",["universidad"],"dificil"),
q("What value makes 2x+6 equal zero?",["−3","3","−6","6"],"−3",["secundaria"],"facil"),
q("Solve x−9≤2.",["x≤11","x≥11","x≤7","x≥7"],"x≤11",["secundaria"],"media"),
q("What is the slope between (1,2) and (3,8)?",["3","2","6","4"],"3",["universidad"],"dificil"),
q("If f(x)=x+4 and g(x)=2x, what is f(g(3))?",["10","7","14","6"],"10",["universidad"],"dificil"),
q("What is the result of x³·x²?",["x⁵","x⁶","2x⁵","x"],"x⁵",["universidad"],"media"),
q("Simplify x⁶/x², with x≠0.",["x⁴","x³","x⁸","1/x⁴"],"x⁴",["universidad"],"media"),
q("What is the solution of 2x−1=5x+8?",["−3","3","−9/2","9/2"],"−3",["universidad"],"dificil"),
q("Which expression is equivalent to 3(a−2)+2a?",["5a−6","5a−2","a−6","5a+6"],"5a−6",["secundaria"],"media"),
q("What is the notable product (x−5)(x+5)?",["x²−25","x²+25","x²−10x+25","x²+10x+25"],"x²−25",["universidad"],"media"),
q("If x+y=12 and y=7, what is x?",["5","19","7","4"],"5",["primaria"],"facil"),
q("What is the solution of x²+4x+4=0?",["−2","2","±2","4"],"−2",["universidad"],"dificil"),
q("If a=−2, what is a³?",["−8","8","−6","6"],"−8",["secundaria"],"media"),
q("What is the degree of the polynomial 4x⁵−x²+1?",["5","4","3","2"],"5",["universidad"],"media"),
q("Which value of x satisfies 5−2x=1?",["2","−2","3","−3"],"2",["secundaria"],"facil"),
q("If y is inversely proportional to x and x doubles, what happens to y?",["It is halved","It doubles","It does not change","It is quadrupled"],"It is halved",["universidad"],"dificil"),
q("What is the factored form of x²−9?",["(x−3)(x+3)","(x−9)(x+1)","(x−3)²","(x+9)(x−1)"],"(x−3)(x+3)",["secundaria"],"media")
];
