import type { EducationDifficulty, EducationLevel } from "../education-engine";
type Q={text:string;options:string[];answer:string;levels?:EducationLevel[];difficulty?:EducationDifficulty};
const q=(text:string,options:string[],answer:string,levels:EducationLevel[],difficulty:EducationDifficulty):Q=>({text,options,answer,levels,difficulty});
export const ALGEBRA:Q[]=[
q("Si x + 7 = 15, ¿cuánto vale x?",["8","7","9","22"],"8",["primaria","secundaria"],"facil"),
q("Si 4x = 28, ¿cuánto vale x?",["7","6","8","9"],"7",["primaria","secundaria"],"facil"),
q("¿Cuál es el valor de 3x + 2 cuando x = 5?",["17","15","12","20"],"17",["primaria","secundaria"],"facil"),
q("Simplifica 5x + 3x.",["8x","15x","8","2x"],"8x",["secundaria"],"facil"),
q("¿Cuál es la expresión factorizada de x² − 9?",["(x−3)(x+3)","(x−9)(x+1)","(x−3)²","x(x−9)"],"(x−3)(x+3)",["secundaria","universidad"],"media"),
q("Resuelve 2x + 5 = 17.",["6","5","7","11"],"6",["secundaria"],"facil"),
q("¿Cuál es la pendiente de y = 3x − 4?",["3","−4","4","1/3"],"3",["secundaria","universidad"],"media"),
q("¿Cuál es la ordenada al origen de y = −2x + 9?",["9","−2","2","−9"],"9",["secundaria"],"media"),
q("Si 2(x + 3) = 14, ¿cuánto vale x?",["4","5","7","2"],"4",["secundaria"],"media"),
q("¿Qué solución satisface x² = 49?",["x = 7 o x = −7","x = 49","x = 14","x = −49"],"x = 7 o x = −7",["secundaria","universidad"],"media"),
q("Simplifica 2a + 5 − a + 3.",["a + 8","a + 2","3a + 8","a − 8"],"a + 8",["secundaria"],"media"),
q("Si x/4 = 6, ¿cuánto vale x?",["24","10","12","2"],"24",["secundaria"],"facil"),
q("¿Cuál es el desarrollo de (x + 2)²?",["x² + 4x + 4","x² + 4","x² + 2x + 4","x² + 4x + 2"],"x² + 4x + 4",["secundaria","universidad"],"media"),
q("Resuelve 3(x − 2) = 2x + 5.",["11","1","7","−11"],"11",["secundaria","universidad"],"media"),
q("Si f(x)=2x−1, ¿cuál es f(4)?",["7","8","6","9"],"7",["secundaria"],"facil"),
q("¿Qué ecuación representa una recta horizontal que pasa por y = 5?",["y = 5","x = 5","y = x + 5","y = 5x"],"y = 5",["secundaria","universidad"],"media"),
q("Resuelve el sistema x+y=10 y x−y=2.",["x=6, y=4","x=4, y=6","x=8, y=2","x=5, y=5"],"x=6, y=4",["secundaria","universidad"],"dificil"),
q("¿Cuál es el dominio de f(x)=1/(x−2)?",["Todos los reales excepto 2","Todos los reales","Solo x>2","Solo x<2"],"Todos los reales excepto 2",["universidad"],"dificil"),
q("Si 3^x = 81, ¿cuánto vale x?",["4","3","9","27"],"4",["secundaria","universidad"],"media"),
q("Resuelve 2^x = 1/8.",["−3","3","−2","8"],"−3",["secundaria","universidad"],"dificil"),
q("Si 7x−4=31, ¿cuánto vale x?",["5","4","6","7"],"5",["secundaria"],"facil"),
q("Simplifica 4y−2y+9.",["2y+9","6y+9","2y−9","4y+7"],"2y+9",["secundaria"],"facil"),
q("¿Cuál es la raíz de x²−16=0?",["4 y −4","16 y −16","4 solamente","−4 solamente"],"4 y −4",["secundaria"],"media"),
q("¿Cuál es el vértice de y=(x−2)²+3?",["(2,3)","(−2,3)","(2,−3)","(3,2)"],"(2,3)",["universidad"],"dificil"),
q("¿Qué valor hace cero a 2x+6?",["−3","3","−6","6"],"−3",["secundaria"],"facil"),
q("Resuelve x−9≤2.",["x≤11","x≥11","x≤7","x≥7"],"x≤11",["secundaria"],"media"),
q("¿Cuál es la pendiente entre (1,2) y (3,8)?",["3","2","6","4"],"3",["secundaria","universidad"],"dificil"),
q("Si f(x)=x+4 y g(x)=2x, ¿cuánto vale f(g(3))?",["10","7","14","6"],"10",["universidad"],"dificil"),
q("¿Cuál es el resultado de x³·x²?",["x⁵","x⁶","2x⁵","x"],"x⁵",["secundaria","universidad"],"media"),
q("Simplifica x⁶/x², con x≠0.",["x⁴","x³","x⁸","1/x⁴"],"x⁴",["secundaria","universidad"],"media"),
q("¿Cuál es la solución de 2x−1=5x+8?",["−3","3","−9/2","9/2"],"−3",["secundaria","universidad"],"dificil"),
q("¿Qué expresión es equivalente a 3(a−2)+2a?",["5a−6","5a−2","a−6","5a+6"],"5a−6",["secundaria"],"media"),
q("¿Cuál es el producto notable (x−5)(x+5)?",["x²−25","x²+25","x²−10x+25","x²+10x+25"],"x²−25",["secundaria","universidad"],"media"),
q("Si x+y=12 y y=7, ¿cuánto vale x?",["5","19","7","4"],"5",["primaria","secundaria"],"facil"),
q("¿Cuál es la solución de x²+4x+4=0?",["−2","2","±2","4"],"−2",["universidad"],"dificil"),
q("Si a=−2, ¿cuánto vale a³?",["−8","8","−6","6"],"−8",["secundaria"],"media"),
q("¿Cuál es el grado del polinomio 4x⁵−x²+1?",["5","4","3","2"],"5",["secundaria","universidad"],"media"),
q("¿Qué valor de x satisface 5−2x=1?",["2","−2","3","−3"],"2",["secundaria"],"facil"),
q("Si y es inversamente proporcional a x y x se duplica, ¿qué ocurre con y?",["Se reduce a la mitad","Se duplica","No cambia","Se cuadruplica"],"Se reduce a la mitad",["universidad"],"dificil")
];
