import type { EducationDifficulty, EducationLevel } from "../education-engine";

type Q={text:string;options:string[];answer:string;levels?:EducationLevel[];difficulty?:EducationDifficulty};
const q=(text:string,options:string[],answer:string,levels?:EducationLevel[],difficulty?:EducationDifficulty):Q=>({text,options,answer,levels,difficulty});

export const CALCULO:Q[]=[
q("What is the derivative of x²?",["2x","x","x²","2"],"2x",["primaria"],"facil"),
q("What is the derivative of x³?",["3x²","x²","3x","x³"],"3x²",["primaria"],"facil"),
q("What is the derivative of a constant?",["0","1","The same constant","It does not exist"],"0",["primaria"],"facil"),
q("What is the derivative of 5x?",["5","x","5x","0"],"5",["primaria"],"facil"),
q("What is an antiderivative of 2x?",["x²","2x²","x","2"],"x²",["primaria"],"facil"),
q("What is an antiderivative of 6x²?",["2x³","6x³","3x²","x³"],"2x³",["secundaria"],"dificil"),
q("What is the derivative of sin(x)?",["cos(x)","−sin(x)","tan(x)","1"],"cos(x)",["secundaria"],"media"),
q("What is the derivative of cos(x)?",["−sin(x)","sin(x)","cos(x)","−cos(x)"],"−sin(x)",["secundaria"],"dificil"),
q("What is the derivative of eˣ?",["eˣ","xeˣ","1","ln(x)"],"eˣ",["secundaria"],"media"),
q("What is the derivative of ln(x)?",["1/x","ln(x)","x","eˣ"],"1/x",["secundaria"],"media"),
q("What is the integral of 1/x dx?",["ln|x|+C","1/x²+C","x+C","eˣ+C"],"ln|x|+C",["secundaria"],"media"),
q("What is the integral of cos(x) dx?",["sin(x)+C","−sin(x)+C","cos(x)+C","tan(x)+C"],"sin(x)+C",["secundaria"],"media"),
q("What is the integral of sin(x) dx?",["−cos(x)+C","cos(x)+C","sin(x)+C","−sin(x)+C"],"−cos(x)+C",["secundaria"],"media"),
q("What is the limit of x as x approaches 3?",["3","0","∞","Does not exist"],"3",["primaria"],"facil"),
q("What is the limit of 1/x as x approaches infinity?",["0","1","∞","−1"],"0",["primaria"],"facil"),
q("What is the limit of (x²−1)/(x−1) as x approaches 1?",["2","1","0","Does not exist"],"2",["universidad"],"dificil"),
q("What condition characterizes a function continuous at a point?",["The limit equals the function value","Its derivative is always zero","It has no domain","It is always linear"],"The limit equals the function value",["universidad"],"media"),
q("What does the derivative represent geometrically at a point?",["Slope of the tangent line","Total area","Arc length","Volume"],"Slope of the tangent line",["primaria"],"media"),
q("What does a definite integral of a non-negative function represent?",["Area under the curve","Slope","Root","Perimeter"],"Area under the curve",["universidad"],"media"),
q("What is ∫₀² x dx?",["2","1","4","3"],"2",["universidad"],"media"),
q("What is ∫₀¹ 3x² dx?",["1","3","1/3","2"],"1",["universidad"],"media"),
q("What is the derivative of 4x⁴−2x?",["16x³−2","4x³−2","16x⁴−2","x³−2"],"16x³−2",["universidad"],"media"),
q("What is the derivative of (x²+1)²?",["4x(x²+1)","2(x²+1)","4x²+1","2x(x²+1)"],"4x(x²+1)",["universidad"],"dificil"),
q("Which rule is used to differentiate a product of functions?",["Product rule","Chain rule","L'Hôpital's rule","Fundamental theorem"],"Product rule",["universidad"],"media"),
q("Which rule is used to differentiate a composition of functions?",["Chain rule","Product rule","Rule of three","Trapezoid rule"],"Chain rule",["universidad"],"media"),
q("If f'(x)>0 on an interval, what happens to f?",["It is increasing on that interval","It is decreasing","It is necessarily constant","It has no domain"],"It is increasing on that interval",["universidad"],"media"),
q("If f'(x)<0 on an interval, what happens to f?",["It is decreasing on that interval","It is increasing","It is necessarily constant","It is discontinuous"],"It is decreasing on that interval",["universidad"],"media"),
q("What indicates a critical point of a differentiable function?",["That the derivative is zero","That the function is always zero","That it has no limit","That its domain is empty"],"That the derivative is zero",["universidad"],"media"),
q("Which test can help classify a local extremum using the second derivative?",["Second derivative test","Pythagorean theorem","Cramer's rule","Euler's method"],"Second derivative test",["universidad"],"media"),
q("If f''(x)>0 on an interval, the function is…",["Concave up","Concave down","Constant","Periodic"],"Concave up",["universidad"],"media"),
q("If f''(x)<0 on an interval, the function is…",["Concave down","Concave up","Necessarily linear","Discontinuous"],"Concave down",["universidad"],"media"),
q("Which theorem relates differentiation and integration?",["Fundamental theorem of calculus","Bayes' theorem","Euclid's theorem","Gauss's theorem"],"Fundamental theorem of calculus",["universidad"],"media"),
q("What is the derivative of ln(x²) for x>0?",["2/x","1/x²","2x","ln(2x)"],"2/x",["universidad"],"dificil"),
q("What is the derivative of √x for x>0?",["1/(2√x)","2√x","√x/2","1/x"],"1/(2√x)",["universidad"],"dificil"),
q("What is the derivative of 1/x?",["−1/x²","1/x²","−x²","ln(x)"],"−1/x²",["universidad"],"media"),
q("What is ∫ 4x³ dx?",["x⁴+C","4x⁴+C","x³+C","12x²+C"],"x⁴+C",["universidad"],"media"),
q("What is ∫ 5 dx?",["5x+C","x⁵+C","5+C","0"],"5x+C",["universidad"],"facil"),
q("What is the limit of sin(x)/x as x approaches 0?",["1","0","∞","Does not exist"],"1",["universidad"],"dificil"),
q("Which tool helps evaluate certain 0/0 quotient limits?",["L'Hôpital's rule","Product rule","Pythagorean theorem","Linear substitution method"],"L'Hôpital's rule",["universidad"],"dificil"),
q("What describes the instantaneous rate of change of a function?",["Its derivative","Its integral","Its domain","Its range"],"Its derivative",["universidad"],"media")
];
