import type { EducationDifficulty, EducationLevel } from "../education-engine";

type Q={text:string;options:string[];answer:string;levels?:EducationLevel[];difficulty?:EducationDifficulty};
const q=(text:string,options:string[],answer:string,levels?:EducationLevel[],difficulty?:EducationDifficulty):Q=>({text,options,answer,levels,difficulty});

export const ESTADISTICA:Q[]=[
 q("What is the average of 4, 6 and 8?",["6","5","7","18"],"6",["primaria"],"facil"),
 q("What is the median of 2, 5 and 9?",["5","2","9","16"],"5",["primaria"],"facil"),
 q("What is the mode of 3, 4, 4, 7?",["4","3","7","18"],"4",["primaria"],"facil"),
 q("What is the range of 5, 8, 11 and 14?",["9","14","5","19"],"9",["primaria"],"facil"),
 q("Which measure divides ordered data into two halves?",["Median","Mean","Variance","Standard deviation"],"Median",["primaria"],"facil"),
 q("Which measure indicates the value that appears most often?",["Mode","Median","Range","Percentile"],"Mode",["primaria"],"facil"),
 q("If all values increase by 3, what happens to the mean?",["It increases by 3","It does not change","It triples","It decreases by 3"],"It increases by 3",["secundaria"],"media"),
 q("Which dispersion measure uses squared differences from the mean?",["Variance","Mode","Median","Range"],"Variance",["secundaria"],"media"),
 q("What does a small standard deviation indicate?",["The data are relatively concentrated","The data are always negative","The mean is zero","There are no data"],"The data are relatively concentrated",["secundaria"],"media"),
 q("In a perfectly symmetric unimodal distribution, which relationship usually holds?",["Mean = median = mode","Mean > median always","Mode = 0 always","Median = range"],"Mean = median = mode",["universidad"],"dificil"),
 q("What does the 90th percentile represent?",["The value below which about 90% of the data fall","90% of the mean","The sum of the data","Variance multiplied by 90"],"The value below which about 90% of the data fall",["secundaria"],"media"),
 q("Which chart is especially useful for showing the distribution of a quantitative variable by intervals?",["Histogram","Pie chart only","Political map","Flowchart"],"Histogram",["universidad"],"media"),
 q("What does relative frequency represent?",["Proportion of observations that belong to a category or interval","The maximum value","The sum of the variables","The difference between maximum and minimum"],"Proportion of observations that belong to a category or interval",["universidad"],"media"),
 q("If 20 of 50 students choose an option, what relative frequency does that represent?",["0.40","0.25","0.50","0.70"],"0.40",["secundaria"],"facil"),
 q("What type of variable is the number of siblings?",["Discrete quantitative","Continuous quantitative","Nominal qualitative","Ordinal qualitative"],"Discrete quantitative",["universidad"],"media"),
 q("What type of variable is temperature measured with decimals?",["Continuous quantitative","Discrete quantitative","Nominal","Binary"],"Continuous quantitative",["universidad"],"media"),
 q("What does the correlation between two variables measure?",["The strength and direction of their linear association","Causality with certainty","The average of both","The number of observations"],"The strength and direction of their linear association",["universidad"],"dificil"),
 q("A correlation close to −1 indicates a linear relationship that is…",["Negative and strong","Positive and strong","Zero","Perfectly quadratic"],"Negative and strong",["universidad"],"media"),
 q("What property does the probability of an event have?",["It is between 0 and 1 inclusive","It is always greater than 1","It is always negative","It can be any real number"],"It is between 0 and 1 inclusive",["universidad"],"facil"),
 q("If two events are mutually exclusive, what is their joint probability?",["0","1","The sum of their probabilities","Always 0.5"],"0",["universidad"],"media"),
 q("What is the mean of 12, 15, 18 and 19?",["16","15","17","64"],"16",["secundaria"],"facil"),
 q("What is the median of 4, 6, 9, 12 and 20?",["9","6","12","10.2"],"9",["secundaria"],"facil"),
 q("What is the range of 3, 17, 8, 12 and 21?",["18","14","21","24"],"18",["secundaria"],"facil"),
 q("In a group of 40 data points, a value appears 10 times. What is its relative frequency?",["0.25","0.10","0.40","4"],"0.25",["secundaria"],"facil"),
 q("If the mean of 6 numbers is 14, what is the sum of the numbers?",["84","20","42","98"],"84",["secundaria"],"facil"),
 q("Which measure is less sensitive to a single extreme value?",["Median","Mean","Sum","Variance"],"Median",["universidad"],"media"),
 q("If a distribution has mean 20 and all values are multiplied by 3, what is the new mean?",["60","23","20","6.67"],"60",["secundaria"],"media"),
 q("If 5 is added to each value in a set, what happens to its standard deviation?",["It does not change","It increases by 5","It is multiplied by 5","It decreases by 5"],"It does not change",["universidad"],"media"),
 q("Which chart compares categories using separate bars?",["Bar chart","Histogram","Scatter plot","Normal curve"],"Bar chart",["primaria"],"facil"),
 q("Which chart shows value pairs to study a possible association between two variables?",["Scatter plot","Pie chart","Histogram","Bar chart"],"Scatter plot",["universidad"],"media"),
 q("What does a correlation of +1 mean?",["Perfect positive linear relationship","Perfect negative linear relationship","Absence of linear relationship","Equality between the variables"],"Perfect positive linear relationship",["universidad"],"dificil"),
 q("What does a correlation of −1 mean?",["Perfect negative linear relationship","Perfect positive linear relationship","Absence of linear relationship","Variables necessarily independent"],"Perfect negative linear relationship",["universidad"],"dificil"),
 q("If a fair coin is flipped twice, what is the probability of getting two heads?",["1/4","1/2","3/4","1"],"1/4",["secundaria"],"media"),
 q("On a fair six-sided die, what is the probability of getting exactly a 6 on one roll?",["1/6","1/3","1/2","5/6"],"1/6",["primaria"],"facil"),
 q("If a sample has 30 observations and 9 belong to a category, what percentage do they represent?",["30%","9%","21%","39%"],"30%",["secundaria"],"media"),
 q("Which position measure divides ordered data into one hundred percentage parts?",["Percentile","Range","Variance","Mode"],"Percentile",["universidad"],"media"),
 q("What is the third quartile in a distribution?",["The 75th percentile","The 25th percentile","The 50th percentile","The 100th percentile"],"The 75th percentile",["universidad"],"dificil"),
 q("What is the first quartile in a distribution?",["The 25th percentile","The 50th percentile","The 75th percentile","The 10th percentile"],"The 25th percentile",["universidad"],"dificil"),
 q("What does the interquartile range represent?",["The difference between the third and first quartiles","The difference between mean and median","The sum of the quartiles","The maximum divided by the minimum"],"The difference between the third and first quartiles",["universidad"],"dificil"),
 q("What happens to the variance if all values are multiplied by 2?",["It is multiplied by 4","It is multiplied by 2","It does not change","It is divided by 2"],"It is multiplied by 4",["universidad"],"dificil")
];
