import type { EducationDifficulty, EducationLevel } from "../education-engine";

type Q={text:string;options:string[];answer:string;levels?:EducationLevel[];difficulty?:EducationDifficulty};
const q=(text:string,options:string[],answer:string,levels?:EducationLevel[],difficulty?:EducationDifficulty):Q=>({text,options,answer,levels,difficulty});

export const GEOMETRIA:Q[]=[
q("What is the perimeter of a square with side 6 cm?",["24 cm","12 cm","36 cm","18 cm"],"24 cm",["primaria"],"facil"),
q("What is the area of a square with side 7 cm?",["49 cm²","28 cm²","14 cm²","56 cm²"],"49 cm²",["primaria"],"facil"),
q("How many degrees do the interior angles of a triangle sum to?",["180°","90°","270°","360°"],"180°",["primaria"],"facil"),
q("What is the measure of each interior angle of an equilateral triangle?",["60°","45°","90°","120°"],"60°",["primaria"],"facil"),
q("What is the area of a rectangle 9 cm by 4 cm?",["36 cm²","26 cm²","18 cm²","40 cm²"],"36 cm²",["primaria"],"facil"),
q("What is the perimeter of a rectangle 8 cm by 3 cm?",["22 cm","24 cm","11 cm","16 cm"],"22 cm",["primaria"],"facil"),
q("How many sides does a hexagon have?",["6","5","7","8"],"6",["primaria"],"facil"),
q("How many sides does an octagon have?",["8","6","7","10"],"8",["primaria"],"facil"),
q("Which shape has all points at the same distance from the center?",["Circle","Triangle","Trapezoid","Rhombus"],"Circle",["primaria"],"facil"),
q("What is the diameter of a circle with radius 5 cm?",["10 cm","5 cm","15 cm","25 cm"],"10 cm",["primaria"],"facil"),
q("What is the formula for the area of a triangle?",["base × height ÷ 2","base + height","2 × base × height","base² + height²"],"base × height ÷ 2",["secundaria"],"media"),
q("What is the area of a triangle with base 10 cm and height 6 cm?",["30 cm²","60 cm²","16 cm²","36 cm²"],"30 cm²",["secundaria"],"media"),
q("What is the area of a parallelogram with base 12 cm and height 5 cm?",["60 cm²","34 cm²","17 cm²","120 cm²"],"60 cm²",["secundaria"],"media"),
q("What is the area of a trapezoid with bases 8 cm and 14 cm and height 5 cm?",["55 cm²","110 cm²","45 cm²","70 cm²"],"55 cm²",["secundaria"],"dificil"),
q("What is the circumference of a circle with radius 3 cm using π≈3.14?",["18.84 cm","9.42 cm","28.26 cm","6.28 cm"],"18.84 cm",["secundaria"],"media"),
q("What is the area of a circle with radius 4 cm using π≈3.14?",["50.24 cm²","25.12 cm²","12.56 cm²","100.48 cm²"],"50.24 cm²",["secundaria"],"media"),
q("What type of angle measures 90°?",["Right","Acute","Obtuse","Straight"],"Right",["secundaria"],"facil"),
q("What type of angle measures 120°?",["Obtuse","Acute","Right","Null"],"Obtuse",["secundaria"],"facil"),
q("What type of angle measures less than 90°?",["Acute","Obtuse","Straight","Complete"],"Acute",["secundaria"],"facil"),
q("What type of angle measures 180°?",["Straight","Right","Acute","Concave"],"Straight",["secundaria"],"facil"),
q("If two lines intersect forming four right angles, they are…",["Perpendicular","Parallel","Coincident","Oblique secants"],"Perpendicular",["secundaria"],"media"),
q("What property do two parallel lines in a plane have?",["They do not intersect","They always form 90°","They share exactly one point","They are necessarily perpendicular"],"They do not intersect",["secundaria"],"facil"),
q("What is the hypotenuse of a right triangle with legs 3 and 4?",["5","6","7","12"],"5",["secundaria"],"media"),
q("What is the Pythagorean theorem relationship?",["a²+b²=c²","a+b=c²","a²−b²=c","2a+2b=c"],"a²+b²=c²",["universidad"],"media"),
q("A right triangle has hypotenuse 13 and one leg 5. What is the other leg?",["12","8","10","18"],"12",["universidad"],"dificil"),
q("What is the diagonal of a square with side 5 cm?",["5√2 cm","10 cm","25 cm","√5 cm"],"5√2 cm",["universidad"],"dificil"),
q("How many diagonals does a pentagon have?",["5","10","3","7"],"5",["secundaria"],"media"),
q("How many diagonals does a hexagon have?",["9","6","12","15"],"9",["secundaria"],"media"),
q("What is the sum of the interior angles of a quadrilateral?",["360°","180°","540°","270°"],"360°",["secundaria"],"media"),
q("What is the sum of the interior angles of a pentagon?",["540°","360°","720°","450°"],"540°",["secundaria"],"media"),
q("What is the sum of the interior angles of a hexagon?",["720°","540°","900°","600°"],"720°",["secundaria"],"media"),
q("What is the measure of each interior angle of a square?",["90°","60°","120°","45°"],"90°",["secundaria"],"facil"),
q("What is the volume of a cube with side 3 cm?",["27 cm³","9 cm³","18 cm³","81 cm³"],"27 cm³",["secundaria"],"media"),
q("What is the volume of a rectangular prism 2×3×5 cm?",["30 cm³","10 cm³","25 cm³","60 cm³"],"30 cm³",["secundaria"],"media"),
q("What is the volume of a cylinder with radius 2 cm and height 5 cm using π≈3.14?",["62.8 cm³","31.4 cm³","20 cm³","125.6 cm³"],"62.8 cm³",["universidad"],"dificil"),
q("What is the total surface area of a cube with side 4 cm?",["96 cm²","64 cm²","24 cm²","48 cm²"],"96 cm²",["secundaria"],"media"),
q("Two similar figures have side ratio 2. What is the ratio of their areas?",["4","2","6","8"],"4",["universidad"],"dificil"),
q("Two similar figures have side ratio 3. What is the ratio of their volumes?",["27","9","6","12"],"27",["universidad"],"dificil"),
q("A map uses scale 1:100,000. How many real kilometers do 3 cm represent?",["3 km","0.3 km","30 km","300 km"],"3 km",["universidad"],"dificil"),
q("What is the distance between (0,0) and (3,4) in the Cartesian plane?",["5","7","4","3"],"5",["universidad"],"dificil")
];
