import type { EducationDifficulty, EducationLevel } from "../education-engine";

type Q={text:string;options:string[];answer:string;levels?:EducationLevel[];difficulty?:EducationDifficulty};
const q=(text:string,options:string[],answer:string,levels?:EducationLevel[],difficulty?:EducationDifficulty):Q=>({text,options,answer,levels,difficulty});

export const GEOMETRIA:Q[]=[
q("¿Cuál es el perímetro de un cuadrado de lado 6 cm?",["24 cm","12 cm","36 cm","18 cm"],"24 cm",["primaria","secundaria"],"facil"),
q("¿Cuál es el área de un cuadrado de lado 7 cm?",["49 cm²","28 cm²","14 cm²","56 cm²"],"49 cm²",["primaria","secundaria"],"facil"),
q("¿Cuántos grados suman los ángulos interiores de un triángulo?",["180°","90°","270°","360°"],"180°",["primaria","secundaria"],"facil"),
q("¿Cuánto mide cada ángulo interior de un triángulo equilátero?",["60°","45°","90°","120°"],"60°",["primaria","secundaria"],"facil"),
q("¿Cuál es el área de un rectángulo de 9 cm por 4 cm?",["36 cm²","26 cm²","18 cm²","40 cm²"],"36 cm²",["primaria","secundaria"],"facil"),
q("¿Cuál es el perímetro de un rectángulo de 8 cm por 3 cm?",["22 cm","24 cm","11 cm","16 cm"],"22 cm",["primaria","secundaria"],"facil"),
q("¿Cuántos lados tiene un hexágono?",["6","5","7","8"],"6",["primaria"],"facil"),
q("¿Cuántos lados tiene un octágono?",["8","6","7","10"],"8",["primaria"],"facil"),
q("¿Qué figura tiene todos sus puntos a la misma distancia del centro?",["Círculo","Triángulo","Trapecio","Rombo"],"Círculo",["primaria","secundaria"],"facil"),
q("¿Cuál es el diámetro de un círculo cuyo radio es 5 cm?",["10 cm","5 cm","15 cm","25 cm"],"10 cm",["primaria","secundaria"],"facil"),
q("¿Cuál es la fórmula del área de un triángulo?",["base × altura ÷ 2","base + altura","2 × base × altura","base² + altura²"],"base × altura ÷ 2",["secundaria"],"media"),
q("¿Cuál es el área de un triángulo de base 10 cm y altura 6 cm?",["30 cm²","60 cm²","16 cm²","36 cm²"],"30 cm²",["secundaria"],"media"),
q("¿Cuál es el área de un paralelogramo de base 12 cm y altura 5 cm?",["60 cm²","34 cm²","17 cm²","120 cm²"],"60 cm²",["secundaria"],"media"),
q("¿Cuál es el área de un trapecio con bases 8 cm y 14 cm y altura 5 cm?",["55 cm²","110 cm²","45 cm²","70 cm²"],"55 cm²",["secundaria","universidad"],"media"),
q("¿Cuál es la longitud de una circunferencia de radio 3 cm usando π≈3,14?",["18,84 cm","9,42 cm","28,26 cm","6,28 cm"],"18,84 cm",["secundaria"],"media"),
q("¿Cuál es el área de un círculo de radio 4 cm usando π≈3,14?",["50,24 cm²","25,12 cm²","12,56 cm²","100,48 cm²"],"50,24 cm²",["secundaria"],"media"),
q("¿Qué tipo de ángulo mide 90°?",["Recto","Agudo","Obtuso","Llano"],"Recto",["primaria","secundaria"],"facil"),
q("¿Qué tipo de ángulo mide 120°?",["Obtuso","Agudo","Recto","Nulo"],"Obtuso",["primaria","secundaria"],"facil"),
q("¿Qué tipo de ángulo mide menos de 90°?",["Agudo","Obtuso","Llano","Completo"],"Agudo",["primaria","secundaria"],"facil"),
q("¿Qué tipo de ángulo mide 180°?",["Llano","Recto","Agudo","Cóncavo"],"Llano",["primaria","secundaria"],"facil"),
q("Si dos rectas se cortan formando cuatro ángulos rectos, son…",["Perpendiculares","Paralelas","Coincidentes","Secantes oblicuas"],"Perpendiculares",["secundaria"],"media"),
q("¿Qué propiedad tienen dos rectas paralelas en un plano?",["No se intersectan","Forman siempre 90°","Tienen un único punto común","Son necesariamente perpendiculares"],"No se intersectan",["primaria","secundaria"],"facil"),
q("¿Cuánto mide la hipotenusa de un triángulo rectángulo con catetos 3 y 4?",["5","6","7","12"],"5",["secundaria","universidad"],"media"),
q("¿Cuál es la relación del teorema de Pitágoras?",["a²+b²=c²","a+b=c²","a²−b²=c","2a+2b=c"],"a²+b²=c²",["secundaria","universidad"],"media"),
q("Un triángulo rectángulo tiene hipotenusa 13 y un cateto 5. ¿Cuál es el otro cateto?",["12","8","10","18"],"12",["secundaria","universidad"],"dificil"),
q("¿Cuál es la diagonal de un cuadrado de lado 5 cm?",["5√2 cm","10 cm","25 cm","√5 cm"],"5√2 cm",["secundaria","universidad"],"dificil"),
q("¿Cuántas diagonales tiene un pentágono?",["5","10","3","7"],"5",["secundaria"],"media"),
q("¿Cuántas diagonales tiene un hexágono?",["9","6","12","15"],"9",["secundaria"],"media"),
q("¿Cuál es la suma de los ángulos interiores de un cuadrilátero?",["360°","180°","540°","270°"],"360°",["primaria","secundaria"],"media"),
q("¿Cuál es la suma de los ángulos interiores de un pentágono?",["540°","360°","720°","450°"],"540°",["secundaria"],"media"),
q("¿Cuál es la suma de los ángulos interiores de un hexágono?",["720°","540°","900°","600°"],"720°",["secundaria"],"media"),
q("¿Cuánto mide cada ángulo interior de un cuadrado?",["90°","60°","120°","45°"],"90°",["primaria","secundaria"],"facil"),
q("¿Cuál es el volumen de un cubo de lado 3 cm?",["27 cm³","9 cm³","18 cm³","81 cm³"],"27 cm³",["primaria","secundaria"],"media"),
q("¿Cuál es el volumen de un prisma rectangular de 2×3×5 cm?",["30 cm³","10 cm³","25 cm³","60 cm³"],"30 cm³",["secundaria"],"media"),
q("¿Cuál es el volumen de un cilindro de radio 2 cm y altura 5 cm usando π≈3,14?",["62,8 cm³","31,4 cm³","20 cm³","125,6 cm³"],"62,8 cm³",["secundaria","universidad"],"dificil"),
q("¿Cuál es el área total de un cubo de lado 4 cm?",["96 cm²","64 cm²","24 cm²","48 cm²"],"96 cm²",["secundaria"],"media"),
q("Dos figuras semejantes tienen razón de lados 2. ¿Cuál es la razón de sus áreas?",["4","2","6","8"],"4",["secundaria","universidad"],"dificil"),
q("Dos figuras semejantes tienen razón de lados 3. ¿Cuál es la razón de sus volúmenes?",["27","9","6","12"],"27",["secundaria","universidad"],"dificil"),
q("Un mapa usa escala 1:100 000. ¿Cuántos kilómetros reales representa 3 cm?",["3 km","0,3 km","30 km","300 km"],"3 km",["secundaria","universidad"],"dificil"),
q("¿Cuál es la distancia entre (0,0) y (3,4) en el plano cartesiano?",["5","7","4","3"],"5",["secundaria","universidad"],"media"),
q("¿Cuál es el punto medio entre (2,4) y (6,8)?",["(4,6)","(8,12)","(2,2)","(3,5)"],"(4,6)",["secundaria","universidad"],"media")
];
