import type { EducationDifficulty, EducationLevel } from "../education-engine";

type Q={text:string;options:string[];answer:string;levels:EducationLevel[];difficulty:EducationDifficulty};
const q=(text:string,options:string[],answer:string,levels:EducationLevel[],difficulty:EducationDifficulty):Q=>({text,options,answer,levels,difficulty});

export const GRAMATICA:Q[]=[
q("Which word is the noun in «La casa grande tiene ventanas»?",["casa","grande","tiene","ventanas"],"casa",["primaria"],"facil"),
q("Which word functions as an adjective in «El perro negro corre»?",["perro","negro","corre","el"],"negro",["primaria"],"facil"),
q("Which word is the verb in «María estudia matemáticas»?",["María","estudia","matemáticas","la"],"estudia",["primaria"],"facil"),
q("What is the subject in «Los alumnos resolvieron el ejercicio»?",["Los alumnos","resolvieron","el ejercicio","ejercicio"],"Los alumnos",["primaria"],"facil"),
q("What is the predicate in «El tren llegó temprano»?",["El tren","llegó temprano","tren","temprano"],"llegó temprano",["primaria"],"facil"),
q("Which word is a personal pronoun?",["nosotros","mesa","rápido","azul"],"nosotros",["primaria"],"facil"),
q("Which word is an adverb of place?",["aquí","ayer","mucho","rápidamente"],"aquí",["primaria"],"facil"),
q("Which word is a conjunction?",["pero","casa","verde","correr"],"pero",["primaria"],"facil"),
q("Which sentence is in the plural?",["Los pájaros vuelan","El pájaro vuela","La niña lee","Mi hermano estudia"],"Los pájaros vuelan",["primaria"],"facil"),
q("What is the head of the subject in «La pequeña bicicleta roja se rompió»?",["bicicleta","pequeña","roja","rompió"],"bicicleta",["primaria"],"media"),
q("What is the head of the predicate in «El profesor explicó la lección»?",["profesor","explicó","lección","la"],"explicó",["primaria"],"media"),
q("What function does «muy» serve in «Es muy alto»?",["Modify the intensity of the adjective","Name the subject","Indicate the verb tense","Join two clauses"],"Modify the intensity of the adjective",["secundaria"],"media"),
q("Which sentence contains a direct object?",["Ana compró un libro","Ana llegó temprano","Ana está cansada","Ana parece feliz"],"Ana compró un libro",["secundaria"],"media"),
q("In «Pedro entregó el trabajo a Laura», what function does «a Laura» serve?",["Indirect object","Subject","Attribute","Adverbial of place"],"Indirect object",["secundaria"],"media"),
q("Which sentence contains a subject complement (attribute)?",["El cielo está despejado","El cielo cubre la ciudad","El cielo cambió de color","El cielo apareció temprano"],"El cielo está despejado",["secundaria"],"media"),
q("Which sentence is compound?",["Juan estudia y María trabaja","Juan estudia","María trabaja","El libro nuevo"],"Juan estudia y María trabaja",["secundaria"],"media"),
q("What relationship does «porque» express in a sentence?",["Cause","Opposition","Condition","Purpose"],"Cause",["secundaria"],"media"),
q("What relationship does «aunque» express?",["Concession","Cause","Purpose","Time"],"Concession",["secundaria"],"media"),
q("Which is an adjectival subordinate clause?",["El libro que compré es interesante","Estudio porque tengo examen","Cuando llegues, avísame","Quiero que vengas"],"El libro que compré es interesante",["secundaria"],"dificil"),
q("Which is a nominal subordinate clause?",["Espero que vengas mañana","La casa que compré es grande","Saldré cuando termine","Estudio porque debo aprobar"],"Espero que vengas mañana",["secundaria"],"dificil"),
q("Which is a temporal adverbial subordinate clause?",["Te llamaré cuando llegue","Quiero que vengas","El alumno que estudia aprueba","Sé que vendrá"],"Te llamaré cuando llegue",["secundaria"],"dificil"),
q("In «Si estudias, aprobarás», what relationship does «si estudias» express?",["Condition","Cause","Concession","Consequence"],"Condition",["secundaria"],"media"),
q("What type of word is «lentamente»?",["Adverb","Adjective","Noun","Conjunction"],"Adverb",["secundaria"],"facil"),
q("What type of word is «aquellos» in «Aquellos libros son míos»?",["Demonstrative determiner","Adverb","Verb","Conjunction"],"Demonstrative determiner",["secundaria"],"media"),
q("Which sentence contains a linking verb?",["La tarde es tranquila","La tarde terminó pronto","La tarde cubrió el valle","La tarde comenzó ayer"],"La tarde es tranquila",["secundaria"],"media"),
q("What is the omitted subject in «Llegamos temprano»?",["Nosotros","Ellos","Ella","Tú"],"Nosotros",["secundaria"],"media"),
q("Which sentence has a time adverbial?",["Mañana viajaremos a Córdoba","Compré un libro","El niño está enfermo","Laura escribió una carta"],"Mañana viajaremos a Córdoba",["secundaria"],"facil"),
q("What type of coordination appears in «Estudia o trabaja»?",["Disjunctive","Copulative","Adversative","Explanatory"],"Disjunctive",["secundaria"],"media"),
q("What type of coordination appears in «Llegó, pero no entró»?",["Adversative","Disjunctive","Copulative","Distributive"],"Adversative",["secundaria"],"media"),
q("What type of coordination appears in «Lee y escribe»?",["Copulative","Adversative","Disjunctive","Explanatory"],"Copulative",["secundaria"],"facil"),
q("In «Se venden casas», what type of construction appears?",["Reflexive passive","Impersonal with se","Periphrastic passive","Active"],"Reflexive passive",["universidad"],"dificil"),
q("Which sentence is impersonal?",["Hay muchas personas afuera","Los alumnos llegaron temprano","María preparó la cena","El perro duerme"],"Hay muchas personas afuera",["universidad"],"media"),
q("In «El informe fue revisado por el equipo», which voice appears?",["Periphrastic passive","Active","Reflexive passive","Impersonal"],"Periphrastic passive",["universidad"],"dificil"),
q("What function does «por el equipo» serve in «El informe fue revisado por el equipo»?",["Agent complement","Direct object","Attribute","Indirect object"],"Agent complement",["universidad"],"dificil"),
q("Which sentence uses a gerund correctly?",["Salió corriendo hacia la estación","Salió corrido hacia la estación","Salió correr hacia la estación","Salió corrió hacia la estación"],"Salió corriendo hacia la estación",["universidad"],"media"),
q("Which verb form is an infinitive?",["resolver","resuelto","resolviendo","resolvió"],"resolver",["primaria"],"facil"),
q("Which verb form is a participle?",["escrito","escribir","escribiendo","escribe"],"escrito",["primaria"],"facil"),
q("In «Hubiera llegado antes», which mood expresses a hypothetical situation?",["Subjunctive","Indicative","Imperative","Infinitive"],"Subjunctive",["universidad"],"dificil"),
q("Which sentence uses the subjunctive correctly?",["Espero que vengas mañana","Espero que vienes mañana","Espero que vendrás mañana","Espero que ven mañana"],"Espero que vengas mañana",["universidad"],"media"),
q("What property allows a pronoun to replace a previously mentioned noun?",["Anaphoric reference","Tense agreement","Derivation","Verbal inflection"],"Anaphoric reference",["universidad"],"dificil"),
];
