import { useState } from "react";
import type { GeneralTool } from "@/lib/general/types";
const units: Record<string, Record<string, number>> = { area: { "m²": 1, "km²": 1e6, "ft²": 0.092903, acres: 4046.8564224, ha: 10000 }, volume: { L: 1, mL: .001, gal: 3.785411784, "m³": 1000 }, speed: { "km/h": 1, mph: 1.609344, "m/s": 3.6, kn: 1.852 }, energy: { J: 1, cal: 4.184, kWh: 3600000, BTU: 1055.05585262 }, power: { W: 1, kW: 1000, hp: 745.699872 }, pressure: { Pa: 1, bar: 100000, atm: 101325, psi: 6894.757293 }, frequency: { Hz: 1, kHz: 1000, MHz: 1e6, GHz: 1e9 }, data: { bit: 1, byte: 8, KB: 8000, MB: 8e6, GB: 8e9, TB: 8e12 } };
const sets: Record<string, string[]> = { area: ["m²", "km²", "ft²", "acres", "ha"], volume: ["L", "mL", "gal", "m³"], speed: ["km/h", "mph", "m/s", "kn"], energy: ["J", "cal", "kWh", "BTU"], power: ["W", "kW", "hp"], pressure: ["Pa", "bar", "atm", "psi"], frequency: ["Hz", "kHz", "MHz", "GHz"], data: ["bit", "byte", "KB", "MB", "GB", "TB"] };
const hexToRgb = (v: string) => { const h = v.replace(/^#/, ""); if (!/^[0-9a-f]{6}$/i.test(h)) return null; return { r: parseInt(h.slice(0, 2), 16), g: parseInt(h.slice(2, 4), 16), b: parseInt(h.slice(4, 6), 16) }; };
const rgbToHsl = (r: number, g: number, b: number) => { const [rr, gg, bb] = [r, g, b].map(v => v / 255); const max = Math.max(rr, gg, bb), min = Math.min(rr, gg, bb), l = (max + min) / 2; if (max === min) return `HSL: 0°, 0%, ${(l * 100).toFixed(2)}%`; const d = max - min, s = l > .5 ? d / (2 - max - min) : d / (max + min); let h = max === rr ? (gg - bb) / d + (gg < bb ? 6 : 0) : max === gg ? (bb - rr) / d + 2 : (rr - gg) / d + 4; h /= 6; return `HSL: ${(h * 360).toFixed(2)}°, ${(s * 100).toFixed(2)}%, ${(l * 100).toFixed(2)}%`; };
export function ConverterTool({ tool }: { tool: GeneralTool }) {
  const [value, setValue] = useState(""), [from, setFrom] = useState(""), [to, setTo] = useState(""), [out, setOut] = useState("");
  const base = tool.slug.replace("conversor-", ""), kind = base === "datos" ? "data" : base === "velocidad" ? "speed" : base === "energia" ? "energy" : base === "potencia" ? "power" : base === "presion" ? "pressure" : base === "frecuencia" ? "frequency" : base === "area" ? "area" : base === "volumen" ? "volume" : "";
  const options = sets[kind] ?? [];
  const convert = () => { try { const raw = value.trim(); if (tool.slug === "hexadecimal-decimal") { if (!/^(?:0x)?[0-9a-f]+$/i.test(raw)) throw new Error("Introduce un número hexadecimal válido."); setOut(String(parseInt(raw.replace(/^0x/i, ""), 16))); return; } if (tool.slug === "hex-rgb") { const rgb = hexToRgb(raw); if (!rgb) throw new Error("Introduce un HEX válido, por ejemplo #2563EB."); setOut(`RGB: ${rgb.r}, ${rgb.g}, ${rgb.b}`); return; } if (tool.slug === "rgb-hsl") { const p = raw.split(/[,; ]+/).filter(Boolean).map(Number); if (p.length !== 3 || p.some(x => !Number.isInteger(x) || x < 0 || x > 255)) throw new Error("Introduce R, G y B entre 0 y 255."); setOut(rgbToHsl(p[0], p[1], p[2])); return; } const n = Number(raw.replace(",", ".")); if (!Number.isFinite(n)) throw new Error("Introduce un número válido."); if (kind) { const a = from || options[0], b = to || options[1] || options[0]; setOut(`${n} ${a} = ${(n * units[kind][a] / units[kind][b]).toPrecision(10)} ${b}`); return; } if (tool.slug === "binario-decimal") { if (!/^[01]+$/.test(raw)) throw new Error("Introduce un número binario válido."); setOut(String(parseInt(raw, 2))); return; } if (tool.slug === "decimal-binario") { if (!Number.isInteger(n)) throw new Error("Introduce un entero decimal."); setOut(n.toString(2)); return; } if (tool.slug === "decimal-hexadecimal") { if (!Number.isInteger(n)) throw new Error("Introduce un entero decimal."); setOut(n.toString(16).toUpperCase()); return; } if (tool.slug === "grados-radianes" || tool.slug === "conversor-angulos") { setOut(`${n}° = ${(n * Math.PI / 180).toFixed(10)} rad`); return; } if (tool.slug === "rgb-hex") { const p = raw.split(/[,; ]+/).filter(Boolean).map(Number); if (p.length !== 3 || p.some(x => !Number.isInteger(x) || x < 0 || x > 255)) throw new Error("Introduce R, G y B entre 0 y 255."); setOut(`#${p.map(x => x.toString(16).padStart(2, "0")).join("").toUpperCase()}`); return; } throw new Error(`Conversor sin implementación específica: ${tool.slug}`); } catch (error) { setOut(error instanceof Error ? error.message : "No se pudo convertir el valor."); } };
  return <div className="space-y-4"><label className="block space-y-1"><span className="text-sm font-medium">Valor</span><input value={value} onChange={e => setValue(e.target.value)} className="h-11 w-full rounded-xl border bg-background px-3" placeholder={tool.slug.includes("rgb") ? "255, 99, 71" : "100"} /></label>{options.length > 1 && <div className="grid gap-4 sm:grid-cols-2"><label className="space-y-1 text-sm font-medium">Desde<select value={from} onChange={e => setFrom(e.target.value)} className="mt-1 h-11 w-full rounded-xl border bg-background px-3"><option value="">Predeterminado</option>{options.map(x => <option key={x}>{x}</option>)}</select></label><label className="space-y-1 text-sm font-medium">Hacia<select value={to} onChange={e => setTo(e.target.value)} className="mt-1 h-11 w-full rounded-xl border bg-background px-3"><option value="">Predeterminado</option>{options.map(x => <option key={x}>{x}</option>)}</select></label></div>}<button className="rounded-xl bg-primary px-4 py-2 font-bold text-primary-foreground" onClick={convert}>Convertir</button>{out && <output aria-live="polite" className="block break-all rounded-xl border bg-muted/30 p-4">{out}</output>}</div>;
}
