import {useState} from "react";
import type {GeneralTool} from "@/lib/general/types";

const pretty=(v:unknown)=>JSON.stringify(v,null,2);
const parseJson=(s:string)=>JSON.parse(s);
const escHtml=(s:string)=>s.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#39;");
const b64=(s:string)=>decodeURIComponent(atob(s.replace(/-/g,"+").replace(/_/g,"/").padEnd(Math.ceil(s.length/4)*4,"=")).split("").map(c=>`%${c.charCodeAt(0).toString(16).padStart(2,"0")}`).join(""));
const csvRows=(s:string)=>{const rows:string[][]=[];let row:string[]=[],cell="",q=false;for(let i=0;i<s.length;i++){const c=s[i];if(c==='"'){if(q&&s[i+1]==='"'){cell+='"';i++;}else q=!q;}else if(c===","&&!q){row.push(cell);cell="";}else if((c==="\n"||c==="\r")&&!q){if(c==="\r"&&s[i+1]==="\n")i++;row.push(cell);if(row.some(x=>x.length))rows.push(row);row=[];cell="";}else cell+=c;}row.push(cell);if(row.some(x=>x.length))rows.push(row);return rows;};
const csvToJson=(s:string)=>{const rows=csvRows(s);if(!rows.length)throw Error("No hay datos CSV.");const h=rows[0];if(h.some(x=>!x.trim()))throw Error("El CSV contiene un encabezado vacío.");return rows.slice(1).map((r,i)=>{if(r.length!==h.length)throw Error(`Fila ${i+2}: tiene ${r.length} columnas; se esperaban ${h.length}.`);return Object.fromEntries(h.map((k,j)=>[k,r[j]]));});};
const sortKeys=(v:unknown):unknown=>Array.isArray(v)?v.map(sortKeys):v&&typeof v==="object"?Object.fromEntries(Object.entries(v as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>[k,sortKeys(x)])):v;
const pathGet=(root:unknown,path:string)=>{let p=path.trim().replace(/^\$\.?/,"").replace(/\[(\d+)\]/g,".$1");if(!p)return root;return p.split(".").filter(Boolean).reduce((v,k)=>{if(v===null||v===undefined)throw Error(`No existe la ruta en ${k}.`);return (v as Record<string,unknown>)[k];},root);};
const diff=(a:unknown,b:unknown,path="$",out:string[]=[]):string[]=>{if(Object.is(a,b))return out;if(a&&b&&typeof a==="object"&&typeof b==="object"&&!Array.isArray(a)&&!Array.isArray(b)){const keys=new Set([...Object.keys(a as object),...Object.keys(b as object)]);for(const k of [...keys].sort()){const aa=(a as Record<string,unknown>)[k],bb=(b as Record<string,unknown>)[k];if(!(k in (a as object)))out.push(`+ ${path}.${k}: ${pretty(bb)}`);else if(!(k in (b as object)))out.push(`- ${path}.${k}: ${pretty(aa)}`);else diff(aa,bb,`${path}.${k}`,out);}return out;}out.push(`~ ${path}: ${pretty(a)} → ${pretty(b)}`);return out;};
const xmlPretty=(s:string)=>{const doc=new DOMParser().parseFromString(s,"application/xml");const err=doc.querySelector("parsererror");if(err)throw Error("XML inválido.");const walk=(n:Node,depth=0):string=>{const pad="  ".repeat(depth);if(n.nodeType===Node.TEXT_NODE)return n.textContent?.trim()?pad+escHtml(n.textContent.trim()):"";if(n.nodeType===Node.COMMENT_NODE)return `${pad}<!--${n.textContent??""}-->`;if(n.nodeType!==Node.ELEMENT_NODE)return"";const e=n as Element;const attrs=[...e.attributes].map(a=>` ${a.name}=\"${escHtml(a.value)}\"`).join("");const children=[...e.childNodes].filter(x=>x.nodeType!==Node.TEXT_NODE||x.textContent?.trim());if(!children.length)return `${pad}<${e.tagName}${attrs}/>`;const text=children.length===1&&children[0].nodeType===Node.TEXT_NODE;if(text)return `${pad}<${e.tagName}${attrs}>${escHtml(children[0].textContent??"")}</${e.tagName}>`;return `${pad}<${e.tagName}${attrs}>\n${children.map(x=>walk(x,depth+1)).filter(Boolean).join("\n")}\n${pad}</${e.tagName}>`;};return walk(doc.documentElement);};
const urlInfo=(s:string)=>{const u=new URL(s);return pretty({href:u.href,protocol:u.protocol,username:u.username,password:u.password,host:u.host,hostname:u.hostname,port:u.port,pathname:u.pathname,search:u.search,hash:u.hash,origin:u.origin});};
const queryParse=(s:string)=>{const p=new URLSearchParams(s.replace(/^\?/,""));const out:Array<{key:string;value:string}>=[];p.forEach((value,key)=>out.push({key,value}));return pretty(out);};
const queryBuild=(s:string)=>{const lines=s.split(/\r?\n/).filter(Boolean);const p=new URLSearchParams();for(const line of lines){const i=line.indexOf("=");if(i<1)throw Error(`Línea inválida: ${line}`);p.append(line.slice(0,i).trim(),line.slice(i+1));}return p.toString();};
const headers=(s:string)=>{const out:Record<string,string>={};for(const line of s.split(/\r?\n/).filter(Boolean)){const i=line.indexOf(":");if(i<1)throw Error(`Cabecera inválida: ${line}`);out[line.slice(0,i).trim()]=line.slice(i+1).trim();}return pretty(out);};
const jwtParts=(s:string)=>{const p=s.trim().split(".");if(p.length!==3)throw Error("Un JWT debe tener tres segmentos separados por puntos.");return {header:JSON.parse(b64(p[0])),payload:JSON.parse(b64(p[1])),signature:p[2]};};
const regexRun=(pattern:string,text:string,flags:string)=>{const f=flags.includes("g")?flags:flags+"g";const r=new RegExp(pattern,f);return [...text.matchAll(r)].map(m=>({match:m[0],index:m.index??-1,groups:m.slice(1)}));};
const unicode=(s:string)=>[...s].map((c,i)=>{const cp=c.codePointAt(0)!;return `${i+1}. ${c} · U+${cp.toString(16).toUpperCase().padStart(4,"0")} · UTF-16 ${[...c].map(x=>x.charCodeAt(0).toString(16).toUpperCase().padStart(4,"0")).join(" ")}`;}).join("\n");
const tableHtml=(s:string)=>{const rows=s.split(/\r?\n/).filter(Boolean).map(r=>r.split(r.includes("\t")?"\t":","));if(!rows.length)throw Error("Introduce datos tabulares.");const head=rows[0].map(x=>`<th>${escHtml(x.trim())}</th>`).join("");const body=rows.slice(1).map(r=>`<tr>${r.map(x=>`<td>${escHtml(x.trim())}</td>`).join("")}</tr>`).join("\n");return `<table>\n  <thead><tr>${head}</tr></thead>\n  <tbody>\n${body}\n  </tbody>\n</table>`;};

function run(slug:string,input:string,second:string,flags:string){switch(slug){case"json-sort-keys":return pretty(sortKeys(parseJson(input)));case"json-stringify":return JSON.stringify(input);case"json-unescape":return JSON.parse(input);case"json-path":return pretty(pathGet(parseJson(input),second));case"json-diff":return diff(parseJson(input),parseJson(second)).join("\n")||"Los documentos JSON son equivalentes.";case"csv-to-json":return pretty(csvToJson(input));case"csv-validator":{const r=csvRows(input);if(!r.length)return"No hay filas.";const n=r[0].length;const bad=r.map((x,i)=>x.length!==n?`Fila ${i+1}: ${x.length} columnas (esperadas ${n})`:"").filter(Boolean);return bad.length?bad.join("\n"):`CSV válido: ${r.length-1} filas de datos y ${n} columnas.`;}case"xml-formatter":return xmlPretty(input);case"xml-escape":return input.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&apos;");case"url-parser":return urlInfo(input);case"query-string-parser":return queryParse(input);case"query-string-builder":return queryBuild(input);case"http-header-builder":return headers(input);case"jwt-decoder":return pretty(jwtParts(input));case"jwt-header-inspector":return pretty(jwtParts(input).header);case"regex-match-extractor":return pretty(regexRun(input,second,flags));case"regex-replace":{const [pattern,repl]=input.split(/\n/,2);const r=new RegExp(pattern,flags.includes("g")?flags:flags+"g");const result=second.replace(r,repl??"");return pretty({result,matches:(second.match(r)||[]).length});}case"regex-split":return pretty(second.split(new RegExp(input,flags)));case"unicode-inspector":return unicode(input);case"html-table-generator":return tableHtml(input);default:return"Herramienta no implementada.";}}

export function DevAdvancedTool({tool}:{tool:GeneralTool}){const[input,setInput]=useState("");const[second,setSecond]=useState("");const[flags,setFlags]=useState("g");const[out,setOut]=useState("");const[error,setError]=useState("");const copy=()=>navigator.clipboard?.writeText(out);const execute=()=>{try{setError("");setOut(String(run(tool.slug,input,second,flags)));}catch(e){setOut("");setError(e instanceof Error?e.message:"Entrada inválida.");}};const two=["json-path","json-diff","regex-match-extractor","regex-replace","regex-split"].includes(tool.slug);const path=tool.slug==="json-path";return <div className="space-y-4"><div className="grid gap-4 md:grid-cols-2"><label className="space-y-1 md:col-span-2"><span className="text-sm font-medium">Entrada principal</span><textarea value={input} onChange={e=>setInput(e.target.value)} className="min-h-48 w-full rounded-xl border bg-background p-4 font-mono text-sm" placeholder={tool.slug.startsWith("json")?"Pega JSON válido…":"Pega o contenido que quieras procesar…"}/></label>{two&&<label className="space-y-1 md:col-span-2"><span className="text-sm font-medium">{path?"Ruta JSON (ej. $.usuario.nombre)":"Segunda entrada / texto"}</span><textarea value={second} onChange={e=>setSecond(e.target.value)} className="min-h-32 w-full rounded-xl border bg-background p-4 font-mono text-sm" placeholder={path?"$.usuario.nombre":"Pega aquí la segunda entrada…"}/></label>}{["regex-match-extractor","regex-replace","regex-split"].includes(tool.slug)&&<label className="space-y-1"><span className="text-sm font-medium">Flags Regex</span><input value={flags} onChange={e=>setFlags(e.target.value)} className="h-11 w-full rounded-xl border bg-background px-3 font-mono" placeholder="gim"/></label>}</div><div className="flex flex-wrap gap-2"><button onClick={execute} className="rounded-xl bg-primary px-4 py-2 font-bold text-primary-foreground">Procesar</button>{out&&<button onClick={copy} className="rounded-xl border px-4 py-2">Copiar resultado</button>}</div>{error&&<p role="alert" className="rounded-xl border p-4 text-sm">{error}</p>}{out&&<pre className="max-h-[32rem] overflow-auto rounded-xl border bg-muted/30 p-4 whitespace-pre-wrap break-words text-sm">{out}</pre>}<p className="text-xs text-muted-foreground">Procesamiento local: los datos introducidos no se envían a un servidor de UtiliHub.</p></div>}
