import { useState } from "react";
import type { GeneralTool } from "@/lib/general/types";

const HTTP_STATUS: Record<string, string> = {"200":"OK","201":"Created","204":"No Content","301":"Moved Permanently","302":"Found","304":"Not Modified","400":"Bad Request","401":"Unauthorized","403":"Forbidden","404":"Not Found","405":"Method Not Allowed","409":"Conflict","422":"Unprocessable Content","429":"Too Many Requests","500":"Internal Server Error","502":"Bad Gateway","503":"Service Unavailable","504":"Gateway Timeout"};
const MIME: Record<string, string> = {json:"application/json",html:"text/html",css:"text/css",js:"text/javascript",txt:"text/plain",csv:"text/csv",xml:"application/xml",pdf:"application/pdf",png:"image/png",jpg:"image/jpeg",jpeg:"image/jpeg",webp:"image/webp",svg:"image/svg+xml",zip:"application/zip"};
const escapeHtml=(s:string)=>s.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#39;");
const decodeHtml=(s:string)=>{const el=document.createElement("textarea");el.innerHTML=s;return el.value};
const minifyHtml=(s:string)=>s.replace(/<!--[\s\S]*?-->/g,"").replace(/>\s+</g,"><").replace(/\s{2,}/g," ").trim();
const minifyCss=(s:string)=>s.replace(/\/\*[\s\S]*?\*\//g,"").replace(/\s+/g," ").replace(/\s*([{}:;,>])\s*/g,"$1").trim();
const minifyJs=(s:string)=>s.replace(/\/\*[\s\S]*?\*\//g,"").replace(/(^|\s)\/\/.*$/gm,"$1").replace(/\s+/g," ").trim();
const jsonToYaml=(value:unknown,indent=0):string=>{const pad=" ".repeat(indent);if(Array.isArray(value))return value.map(v=>`${pad}- ${typeof v==="object"&&v!==null?`\n${jsonToYaml(v,indent+2)}`:String(v)}`).join("\n");if(value&&typeof value==="object")return Object.entries(value).map(([k,v])=>`${pad}${k}: ${typeof v==="object"&&v!==null?`\n${jsonToYaml(v,indent+2)}`:JSON.stringify(v)}`).join("\n");return JSON.stringify(value)};
const jsonToCsv=(value:unknown)=>{if(!Array.isArray(value)||!value.every(v=>v&&typeof v==="object"&&!Array.isArray(v)))throw new Error("El JSON debe ser un array de objetos.");const rows=value as Record<string,unknown>[];const keys=[...new Set(rows.flatMap(r=>Object.keys(r)))];const q=(v:unknown)=>`"${String(v??"").replace(/"/g,'""')}"`;return [keys.map(q).join(","),...rows.map(r=>keys.map(k=>q(r[k])).join(","))].join("\n")};
const csvDownload=(text:string)=>{const blob=new Blob([text],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);return url};
export function DevTool({tool}:{tool:GeneralTool}){
 const [input,setInput]=useState(""),[out,setOut]=useState(""),[error,setError]=useState("");
 const run=()=>{setError("");try{let result="";switch(tool.slug){case"json-formatter":result=JSON.stringify(JSON.parse(input),null,2);break;case"json-validator":JSON.parse(input);result="JSON válido.";break;case"json-minifier":result=JSON.stringify(JSON.parse(input));break;case"json-a-csv":result=jsonToCsv(JSON.parse(input));break;case"json-a-yaml":result=jsonToYaml(JSON.parse(input));break;case"base64-encode":result=btoa(unescape(encodeURIComponent(input)));break;case"base64-decode":result=decodeURIComponent(escape(atob(input.trim())));break;case"url-encode":result=encodeURIComponent(input);break;case"url-decode":result=decodeURIComponent(input);break;case"html-encode":result=escapeHtml(input);break;case"html-decode":result=decodeHtml(input);break;case"regex-tester":{const [pattern,...rest]=input.split(/\n/);if(!pattern)throw new Error("Introduce la expresión en la primera línea.");const text=rest.join("\n");const re=new RegExp(pattern,"g");const matches=[...text.matchAll(re)].map(m=>m[0]);result=matches.length?`Coincidencias (${matches.length}):\n${matches.join("\n")}`:"Sin coincidencias.";break}case"regex-escape":result=input.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");break;case"slug-generator":result=input.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");break;case"html-minifier":result=minifyHtml(input);break;case"css-minifier":result=minifyCss(input);break;case"javascript-minifier":result=minifyJs(input);break;case"timestamp-generator":result=String(new Date(input||Date.now()).getTime());break;case"timestamp-to-date":{const n=Number(input.trim());if(!Number.isFinite(n))throw new Error("Timestamp inválido.");result=new Date(Math.abs(n)<1e12?n*1000:n).toISOString();break}case"http-status":result=HTTP_STATUS[input.trim()]?`${input.trim()}: ${HTTP_STATUS[input.trim()]}`:"Código HTTP no encontrado en la tabla.";break;case"mime-types":{const ext=input.trim().toLowerCase().replace(/^.*\./,"");result=MIME[ext]??"Tipo MIME no encontrado.";break}default:throw new Error("Herramienta de desarrollo no implementada.")}setOut(result)}catch(e){setOut("");setError(e instanceof Error?e.message:"Entrada inválida.")}};
 return <div className="space-y-4"><label className="block text-sm font-medium">Entrada</label><textarea value={input} onChange={e=>setInput(e.target.value)} className="min-h-48 w-full rounded-xl border bg-background p-4 font-mono text-sm" placeholder={tool.slug.startsWith("json-")?"Pega JSON aquí…":"Introduce o pega los datos…"}/><div className="flex flex-wrap gap-2"><button onClick={run} className="rounded-xl bg-primary px-4 py-2 font-bold text-primary-foreground">Procesar</button><button onClick={()=>{setInput("");setOut("");setError("")}} className="rounded-xl border px-4 py-2">Limpiar</button></div>{error&&<p className="rounded-xl border border-destructive/50 bg-destructive/10 p-3 text-sm">{error}</p>}{out&&<div className="space-y-2"><pre className="max-h-96 overflow-auto whitespace-pre-wrap break-words rounded-xl border bg-muted/30 p-4 text-sm">{out}</pre>{tool.slug==="json-a-csv"&&<a href={csvDownload(out)} download="datos.csv" className="inline-block rounded-xl bg-primary px-4 py-2 text-sm font-bold text-primary-foreground">Descargar CSV</a>}</div>}</div>;
}
