import { useState } from "react";
import type { GeneralTool } from "@/lib/general/types";

type Operation = "pdf-metadata" | "text-diff" | "csv-inspector" | "markdown-html" | "file-name-batch";
const documentOperationMarkers: Record<Operation, () => true> = { "pdf-metadata": () => true, "text-diff": () => true, "csv-inspector": () => true, "markdown-html": () => true, "file-name-batch": () => true };
const escapeHtml = (value: string) => value.replace(/&/g, "&"+"amp;").replace(/</g, "&"+"lt;").replace(/>/g, "&"+"gt;").replace(/\"/g, "&"+"quot;");
const normalizeFileName = (value: string) => value.trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
export function DocumentTool({ tool, locale="en" }: { tool: GeneralTool; locale?: "en"|"es" }) {
  const es = locale === "es";
  const operation = String(tool.config?.operation ?? "") as Operation;
  const [first, setFirst] = useState(""); const [second, setSecond] = useState(""); const [file, setFile] = useState<File | null>(null); const [output, setOutput] = useState(""); const [error, setError] = useState("");
  const run = async () => { try { setError(""); if (!documentOperationMarkers[operation]?.()) throw Error(es ? "Operación de documento no disponible." : "Document operation not available.");
    if (operation === "pdf-metadata") { if (!file) throw Error(es ? "Selecciona un archivo PDF." : "Select a PDF file."); const { PDFDocument } = await import("pdf-lib"); const pdf = await PDFDocument.load(await file.arrayBuffer()); setOutput(es ? `Páginas: ${pdf.getPageCount()}\nTítulo: ${pdf.getTitle() || "Sin título"}\nAutor: ${pdf.getAuthor() || "Sin autor"}\nAsunto: ${pdf.getSubject() || "Sin asunto"}\nTamaño: ${(file.size / 1024).toFixed(1)} KB` : `Pages: ${pdf.getPageCount()}\nTitle: ${pdf.getTitle() || "Untitled"}\nAuthor: ${pdf.getAuthor() || "No author"}\nSubject: ${pdf.getSubject() || "No subject"}\nSize: ${(file.size / 1024).toFixed(1)} KB`); return; }
    if (operation === "text-diff") { if (!first.trim() && !second.trim()) throw Error(es ? "Introduce ambas versiones del texto." : "Enter both versions of the text."); const a = first.split(/\r?\n/); const b = second.split(/\r?\n/); const max = Math.max(a.length, b.length); const lines: string[] = []; for (let i = 0; i < max; i++) if (a[i] !== b[i]) lines.push(es ? `Línea ${i + 1}: ${a[i] ? `− ${a[i]}` : "− (vacía)"}\n${b[i] ? `+ ${b[i]}` : "+ (vacía)"}` : `Line ${i + 1}: ${a[i] ? `− ${a[i]}` : "− (empty)"}\n${b[i] ? `+ ${b[i]}` : "+ (empty)"}`); setOutput(lines.length ? (es ? `${lines.length} línea(s) diferente(s)\n\n${lines.join("\n\n")}` : `${lines.length} different line(s)\n\n${lines.join("\n\n")}`) : (es ? "Los textos son idénticos línea por línea." : "The texts are identical line by line.")); return; }
    if (operation === "csv-inspector") { const text = first.trim(); if (!text) throw Error(es ? "Pega el contenido CSV que quieres inspeccionar." : "Paste the CSV content you want to inspect."); const rows = text.split(/\r?\n/).filter(Boolean).map((row) => row.split(",")); const columns = Math.max(...rows.map((row) => row.length)); const headers = rows[0] ?? []; const duplicateHeaders = headers.filter((header, index) => headers.indexOf(header) !== index); setOutput(es ? `Filas: ${rows.length}\nMáximo de columnas: ${columns}\nEncabezados: ${headers.join(" | ") || "Sin encabezados"}\nEncabezados duplicados: ${duplicateHeaders.length ? [...new Set(duplicateHeaders)].join(", ") : "Ninguno"}\nFilas con columnas incompletas: ${rows.slice(1).filter((row) => row.length !== columns).length}` : `Rows: ${rows.length}\nMax columns: ${columns}\nHeaders: ${headers.join(" | ") || "No headers"}\nDuplicate headers: ${duplicateHeaders.length ? [...new Set(duplicateHeaders)].join(", ") : "None"}\nRows with incomplete columns: ${rows.slice(1).filter((row) => row.length !== columns).length}`); return; }
    if (operation === "markdown-html") { if (!first.trim()) throw Error(es ? "Introduce Markdown para convertir." : "Enter Markdown to convert."); const html = first.split(/\r?\n/).map((line) => { const safe = escapeHtml(line); if (safe.startsWith("### ")) return `<h3>${safe.slice(4)}</h3>`; if (safe.startsWith("## ")) return `<h2>${safe.slice(3)}</h2>`; if (safe.startsWith("# ")) return `<h1>${safe.slice(2)}</h1>`; if (!safe.trim()) return ""; return `<p>${safe.replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")}</p>`; }).join("\n"); setOutput(html); return; }
    if (operation === "file-name-batch") { const names = first.split(/\r?\n/).map(normalizeFileName).filter(Boolean); if (!names.length) throw Error(es ? "Introduce al menos un nombre o título, uno por línea." : "Enter at least one name or title, one per line."); setOutput(names.map((name, index) => `${String(index + 1).padStart(2, "0")}-${name}`).join("\n")); return; }
    throw Error(es ? "Operación de documento no disponible." : "Document operation not available."); } catch (e) { setOutput(""); setError(e instanceof Error ? e.message : (es ? "No se pudo procesar el archivo." : "Could not process the file.")); } };
  const isFile = operation === "pdf-metadata"; const isDual = operation === "text-diff"; const placeholder = operation === "csv-inspector" ? "nombre,email,estado\nAna,ana@example.com,activo" : operation === "markdown-html" ? "# Título\n\n**Importante** texto" : (es ? "Un nombre o texto por línea" : "One name or text per line");
  return <div className="space-y-4">{isFile ? <label className="block space-y-2"><span className="text-sm font-semibold">{es ? "Archivo PDF" : "PDF file"}</span><input type="file" accept="application/pdf,.pdf" onChange={(event) => setFile(event.target.files?.[0] ?? null)} className="block w-full rounded-xl border bg-background p-3 text-sm" /></label> : <div className={isDual ? "grid gap-4 sm:grid-cols-2" : ""}><label className="block space-y-2"><span className="text-sm font-semibold">{isDual ? (es ? "Versión A" : "Version A") : operation === "csv-inspector" ? (es ? "Contenido CSV" : "CSV content") : operation === "markdown-html" ? "Markdown" : (es ? "Títulos o nombres" : "Titles or names")}</span><textarea value={first} onChange={(event) => setFirst(event.target.value)} rows={isDual ? 8 : 10} placeholder={placeholder} className="w-full rounded-xl border bg-background p-3 font-mono text-sm" /></label>{isDual && <label className="block space-y-2"><span className="text-sm font-semibold">{es ? "Versión B" : "Version B"}</span><textarea value={second} onChange={(event) => setSecond(event.target.value)} rows={8} placeholder={es ? "Pega aquí la segunda versión" : "Paste the second version here"} className="w-full rounded-xl border bg-background p-3 font-mono text-sm" /></label>}</div>}
    <button type="button" onClick={run} className="rounded-xl bg-primary px-4 py-2 font-bold text-primary-foreground">{es ? "Procesar" : "Process"}</button>{error && <p role="alert" className="rounded-xl border border-destructive/40 bg-destructive/10 p-3 text-sm">{error}</p>}{output && <pre className="max-h-96 overflow-auto whitespace-pre-wrap rounded-xl border bg-muted/30 p-4 text-sm">{output}</pre>}
  </div>;
}
