import { useMemo, useState } from "react";
import type { GeneralTool } from "@/lib/general/types";

const values = (s: string) => s.split(/[\n,;]+/).map((x) => Number(x.trim().replace(",", "."))).filter(Number.isFinite);
const median = (xs: number[]) => { const a = [...xs].sort((x, y) => x - y); const m = Math.floor(a.length / 2); return a.length % 2 ? a[m] : (a[m - 1] + a[m]) / 2; };
function calculate(slug: string, raw: string, rawB: string, es: boolean): string {
  const xs = values(raw); if (!xs.length) throw new Error(es ? "Introduce uno o más números válidos." : "Enter one or more valid numbers.");
  const mean = xs.reduce((a, b) => a + b, 0) / xs.length;
  switch (slug) {
    case "promedio": return `${es ? "Promedio" : "Average"}: ${mean}`;
    case "mediana": return `${es ? "Mediana" : "Median"}: ${median(xs)}`;
    case "moda": { const counts = new Map<number, number>(); xs.forEach((x) => counts.set(x, (counts.get(x) ?? 0) + 1)); const max = Math.max(...counts.values()); return max === 1 ? (es ? "Moda: no hay valores repetidos." : "Mode: no repeated values.") : `${es ? "Moda" : "Mode"}: ${[...counts].filter(([, n]) => n === max).map(([x]) => x).join(", ")}`; }
    case "rango": { const a = [...xs].sort((x, y) => x - y); return `${es ? "Rango" : "Range"}: ${a[a.length - 1] - a[0]}`; }
    case "varianza": return `${es ? "Varianza poblacional" : "Population variance"}: ${xs.reduce((a, x) => a + (x - mean) ** 2, 0) / xs.length}`;
    case "desviacion-estandar": return `${es ? "Desviación estándar poblacional" : "Population standard deviation"}: ${Math.sqrt(xs.reduce((a, x) => a + (x - mean) ** 2, 0) / xs.length)}`;
    case "percentil": { const p = Number(rawB); if (!Number.isFinite(p) || p < 0 || p > 100) throw new Error(es ? "El percentil debe estar entre 0 y 100." : "Percentile must be between 0 and 100."); const a = [...xs].sort((x, y) => x - y); const pos = (p / 100) * (a.length - 1); const lo = Math.floor(pos); const hi = Math.ceil(pos); return `${es ? "Percentil" : "Percentile"} ${p}: ${a[lo] + (a[hi] - a[lo]) * (pos - lo)}`; }
    case "cuartiles": { const a = [...xs].sort((x, y) => x - y); const q2 = median(a); if (a.length === 1) return `Q1: ${a[0]}\n${es ? "Mediana (Q2)" : "Median (Q2)"}: ${a[0]}\nQ3: ${a[0]}`; const mid = Math.floor(a.length / 2); const q1 = median(a.slice(0, mid)); const q3 = median(a.slice(a.length % 2 ? mid + 1 : mid)); return `Q1: ${q1}\n${es ? "Mediana (Q2)" : "Median (Q2)"}: ${q2}\nQ3: ${q3}`; }
    case "z-score": { const x = Number(rawB); if (!Number.isFinite(x)) throw new Error(es ? "Introduce el valor a estandarizar en el segundo campo." : "Enter the value to standardize in the second field."); const sd = Math.sqrt(xs.reduce((a, v) => a + (v - mean) ** 2, 0) / xs.length); if (sd === 0) throw new Error(es ? "No se puede calcular un z-score con desviación estándar cero." : "Cannot compute a z-score with zero standard deviation."); return `Z-score: ${(x - mean) / sd}`; }
    case "correlacion":
    case "covarianza": { const ys = values(rawB); if (ys.length !== xs.length || ys.length < 2) throw new Error(es ? "Ambas series deben tener la misma cantidad de valores (al menos 2)." : "Both series must have the same number of values (at least 2)."); const meanY = ys.reduce((a, b) => a + b, 0) / ys.length; const cov = xs.reduce((s, x, i) => s + (x - mean) * (ys[i] - meanY), 0) / xs.length; if (slug === "covarianza") return `${es ? "Covarianza poblacional" : "Population covariance"}: ${cov}`; const sdX = Math.sqrt(xs.reduce((s, x) => s + (x - mean) ** 2, 0) / xs.length); const sdY = Math.sqrt(ys.reduce((s, y) => s + (y - meanY) ** 2, 0) / ys.length); if (sdX === 0 || sdY === 0) throw new Error(es ? "La correlación requiere variación en ambas series." : "Correlation requires variation in both series."); return `${es ? "Correlación de Pearson" : "Pearson correlation"}: ${cov / (sdX * sdY)}`; }
    default: throw new Error(es ? `Herramienta estadística no implementada: ${slug}` : `Statistical tool not implemented: ${slug}`);
  }
}
function MiniChart({ data, es }: { data: number[]; es: boolean }) { if (data.length < 2) return null; const visible = data.slice(0, 24); const min = Math.min(...visible); const max = Math.max(...visible); const span = max - min || 1; return <section className="rounded-xl border border-border bg-background p-4" aria-label={es ? "Gráfico de datos" : "Data chart"}><div className="mb-3 flex items-center justify-between"><h3 className="text-sm font-semibold">{es ? "Vista de datos" : "Data view"}</h3><span className="text-xs text-muted-foreground">{data.length} {es ? "valores" : "values"}{data.length > 24 ? (es ? " · primeros 24" : " · first 24") : ""}</span></div><div className="flex h-32 items-end gap-1 overflow-hidden" role="img" aria-label={es ? "Gráfico de barras de los valores introducidos" : "Bar chart of entered values"}>{visible.map((value, i) => <div key={`${i}-${value}`} className="min-w-1 flex-1 rounded-t-sm bg-primary/70" style={{ height: `${Math.max(4, ((value - min) / span) * 100)}%` }} title={`${value}`} />)}</div><div className="mt-2 flex justify-between text-[11px] text-muted-foreground"><span>{min}</span><span>{max}</span></div></section>; }
export function MathTool({ tool, locale = "en" }: { tool: GeneralTool; locale?: "en" | "es" }) {
  const es = locale === "es"; const [raw, setRaw] = useState(""); const [rawB, setRawB] = useState(""); const [out, setOut] = useState(""); const [error, setError] = useState(""); const needsSecond = ["percentil", "z-score", "correlacion", "covarianza"].includes(tool.slug); const chartData = useMemo(() => values(raw), [raw]); const calculateClick = () => { try { setError(""); setOut(calculate(tool.slug, raw, rawB, es)); } catch (e) { setOut(""); setError(e instanceof Error ? e.message : (es ? "No se pudo calcular el resultado." : "Could not calculate the result.")); } };
  return <div className="space-y-4"><div><label htmlFor={`stats-input-${tool.slug}`} className="mb-2 block text-sm font-semibold">{needsSecond && ["correlacion", "covarianza"].includes(tool.slug) ? (es ? "Primera serie de datos" : "First data series") : (es ? "Lista de números" : "Number list")}</label><textarea id={`stats-input-${tool.slug}`} value={raw} onChange={(e) => setRaw(e.target.value)} placeholder={es ? "p. ej., 5, 10, 15, 20" : "e.g. 5, 10, 15, 20"} className="min-h-28 w-full rounded-xl border border-border bg-background p-4"/><p className="mt-2 text-xs text-muted-foreground">{es ? "Separa los valores con comas, punto y coma o saltos de línea." : "Separate values with commas, semicolons, or line breaks."}</p></div>{needsSecond && <div><label htmlFor={`stats-second-${tool.slug}`} className="mb-2 block text-sm font-semibold">{["correlacion", "covarianza"].includes(tool.slug) ? (es ? "Segunda serie de datos" : "Second data series") : tool.slug === "percentil" ? (es ? "Percentil (0–100)" : "Percentile (0–100)") : (es ? "Valor a estandarizar" : "Value to standardize")}</label><textarea id={`stats-second-${tool.slug}`} value={rawB} onChange={(e) => setRawB(e.target.value)} placeholder={["correlacion", "covarianza"].includes(tool.slug) ? (es ? "p. ej., 2, 4, 6, 8" : "e.g. 2, 4, 6, 8") : tool.slug === "percentil" ? (es ? "p. ej., 75" : "e.g. 75") : (es ? "p. ej., 12" : "e.g. 12")} className="min-h-20 w-full rounded-xl border border-border bg-background p-4"/></div>}{chartData.length > 1 && <MiniChart data={chartData} es={es} />}<button type="button" onClick={calculateClick} className="rounded-xl bg-primary px-4 py-2 font-bold text-primary-foreground">{es ? "Calcular" : "Calculate"}</button>{error && <p role="alert" className="rounded-xl border border-destructive/40 bg-destructive/10 p-3 text-sm">{error}</p>}{out && <output aria-live="polite" className="block whitespace-pre-wrap rounded-xl border bg-muted/30 p-4 font-medium">{out}</output>}</div>;
}
