import { useEffect, useMemo, useState } from "react";
import type { GeneralTool } from "@/lib/general/types";
import { PDFDocument, degrees } from "pdf-lib";
import { jsPDF } from "jspdf";

const download=(blob:Blob,name:string)=>{const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
const readBytes=(file:File)=>file.arrayBuffer();
const loadImage=(file:File)=>new Promise<HTMLImageElement>((resolve,reject)=>{const url=URL.createObjectURL(file);const img=new Image();img.onload=()=>{URL.revokeObjectURL(url);resolve(img)};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error("No se pudo leer la imagen."))};img.src=url});
const canvasBlob=(canvas:HTMLCanvasElement,type:string,quality=0.9)=>new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error("No se pudo generar la imagen.")),type,quality));

export function MediaTool({tool}:{tool:GeneralTool}){
 const [files,setFiles]=useState<File[]>([]),[url,setUrl]=useState(""),[info,setInfo]=useState(""),[out,setOut]=useState(""),[error,setError]=useState(""),[quality,setQuality]=useState("0.8"),[width,setWidth]=useState(""),[height,setHeight]=useState(""),[page,setPage]=useState("1"),[angle,setAngle]=useState("90"),[order,setOrder]=useState("");
 const image=tool.kind==="image";
 const imagePdf=tool.slug==="imagenes-a-pdf";
 const multiple=tool.slug==="unir-pdf"||imagePdf;
 const accept=image||imagePdf?"image/*":"application/pdf";
 useEffect(()=>{if(!files.length){setUrl("");setInfo("");return}const file=files[0];const u=URL.createObjectURL(file);setUrl(u);if(file.type.startsWith("image/")){const img=new Image();img.onload=()=>setInfo(`${img.width} × ${img.height}px · ${(file.size/1024).toFixed(1)} KB`);img.src=u}else setInfo(`${(file.size/1024).toFixed(1)} KB · ${file.type||"PDF"}`);return()=>URL.revokeObjectURL(u)},[files]);
 const actionLabel=useMemo(()=>({"redimensionar-imagen":"Redimensionar","comprimir-imagen":"Comprimir","png-a-jpg":"Convertir a JPG","jpg-a-png":"Convertir a PNG","webp-a-jpg":"Convertir a JPG","jpg-a-webp":"Convertir a WebP","favicon":"Generar favicon","recortar-imagen":"Recortar","rotar-imagen":"Rotar","escala-grises":"Convertir a escala de grises","color-dominante":"Analizar color","unir-pdf":"Unir PDFs","dividir-pdf":"Extraer página","imagenes-a-pdf":"Crear PDF","pdf-a-imagenes":"Convertir a imágenes","rotar-pdf":"Rotar PDF","reordenar-pdf":"Reordenar páginas","extraer-texto-pdf":"Extraer texto"} as Record<string,string>)[tool.slug]??"Procesar",[tool.slug]);
 const process=async()=>{setError("");setOut("");try{if(!files.length)throw new Error("Selecciona al menos un archivo.");if(image){const file=files[0];const img=await loadImage(file);let w=img.width,h=img.height;if(tool.slug==="redimensionar-imagen"){w=Math.max(1,Math.round(Number(width)));h=Math.max(1,Math.round(Number(height)));if(!Number.isFinite(w)||!Number.isFinite(h))throw new Error("Introduce ancho y alto válidos.")}if(tool.slug==="recortar-imagen"){w=Math.min(img.width,Math.max(1,Math.round(Number(width)||img.width)));h=Math.min(img.height,Math.max(1,Math.round(Number(height)||img.height)))}if(tool.slug==="rotar-imagen"){const swap=Number(angle)%180!==0;w=swap?img.height:img.width;h=swap?img.width:img.height}const canvas=document.createElement("canvas");canvas.width=w;canvas.height=h;const ctx=canvas.getContext("2d");if(!ctx)throw new Error("Canvas no disponible.");if(tool.slug==="rotar-imagen"){ctx.translate(w/2,h/2);ctx.rotate(Number(angle)*Math.PI/180);ctx.drawImage(img,-img.width/2,-img.height/2);}else if(tool.slug==="recortar-imagen"){const sx=Math.max(0,(img.width-w)/2),sy=Math.max(0,(img.height-h)/2);ctx.drawImage(img,sx,sy,w,h,0,0,w,h)}else ctx.drawImage(img,0,0,w,h);if(tool.slug==="escala-grises"){const data=ctx.getImageData(0,0,w,h);for(let i=0;i<data.data.length;i+=4){const y=.299*data.data[i]+.587*data.data[i+1]+.114*data.data[i+2];data.data[i]=data.data[i+1]=data.data[i+2]=y}ctx.putImageData(data,0,0)}if(tool.slug==="color-dominante"){const data=ctx.getImageData(0,0,w,h).data;let r=0,g=0,b=0,n=0;for(let i=0;i<data.length;i+=40){r+=data[i];g+=data[i+1];b+=data[i+2];n++}const hex=`#${[r/n,g/n,b/n].map(v=>Math.round(v).toString(16).padStart(2,"0")).join("").toUpperCase()}`;setOut(`Color dominante aproximado: ${hex}`);return}if(tool.slug==="favicon"){const c=document.createElement("canvas");c.width=c.height=64;c.getContext("2d")!.drawImage(img,0,0,64,64);download(await canvasBlob(c,"image/png"),"favicon.png");setOut("Favicon creado correctamente.");return}const type=tool.slug.endsWith("-jpg")||tool.slug==="comprimir-imagen"?"image/jpeg":tool.slug.endsWith("-webp")?"image/webp":"image/png";const blob=await canvasBlob(canvas,type,Math.min(1,Math.max(.1,Number(quality)||.8)));download(blob,`${file.name.replace(/\.[^.]+$/,"")}.${type.split("/")[1]}`);setOut(`Procesado correctamente: ${(blob.size/1024).toFixed(1)} KB`);return}
 if(imagePdf){const pdf=new jsPDF({unit:"pt",format:"a4"});for(let i=0;i<files.length;i++){if(i)pdf.addPage();const img=await loadImage(files[i]);const margin=24,maxW=pdf.internal.pageSize.getWidth()-margin*2,maxH=pdf.internal.pageSize.getHeight()-margin*2,scale=Math.min(maxW/img.width,maxH/img.height);const w=img.width*scale,h=img.height*scale;const c=document.createElement("canvas");c.width=img.width;c.height=img.height;c.getContext("2d")!.drawImage(img,0,0);const data=c.toDataURL("image/jpeg",.92);pdf.addImage(data,"JPEG",(pdf.internal.pageSize.getWidth()-w)/2,(pdf.internal.pageSize.getHeight()-h)/2,w,h)}download(pdf.output("blob"),"imagenes.pdf");setOut("PDF creado correctamente.");return}
 const bytes=await readBytes(files[0]);const pdf=await PDFDocument.load(bytes);
 if(tool.slug==="unir-pdf"){if(files.length<2)throw new Error("Selecciona al menos dos PDFs.");const merged=await PDFDocument.create();for(const f of files){const src=await PDFDocument.load(await readBytes(f));const pages=await merged.copyPages(src,src.getPageIndices());pages.forEach(p=>merged.addPage(p))}download(new Blob([await merged.save()],{type:"application/pdf"}),"utilihub-unido.pdf");setOut("PDFs unidos correctamente.");return}
 if(tool.slug==="dividir-pdf"){const index=Math.trunc(Number(page))-1;if(!Number.isInteger(index)||index<0||index>=pdf.getPageCount())throw new Error(`La página debe estar entre 1 y ${pdf.getPageCount()}.`);const outPdf=await PDFDocument.create();const [p]=await outPdf.copyPages(pdf,[index]);outPdf.addPage(p);download(new Blob([await outPdf.save()],{type:"application/pdf"}),`pagina-${index+1}.pdf`);setOut("Página extraída correctamente.");return}
 if(tool.slug==="rotar-pdf"){const index=Math.trunc(Number(page))-1;if(index<0||index>=pdf.getPageCount())throw new Error("Página inválida.");pdf.getPage(index).setRotation(degrees(pdf.getPage(index).getRotation().angle+Number(angle)));download(new Blob([await pdf.save()],{type:"application/pdf"}),"pdf-rotado.pdf");setOut("PDF rotado correctamente.");return}
 if(tool.slug==="reordenar-pdf"){const indexes=order.split(/[,;\s]+/).filter(Boolean).map(x=>Number(x)-1);if(indexes.length!==pdf.getPageCount()||indexes.some(i=>!Number.isInteger(i)||i<0||i>=pdf.getPageCount())||new Set(indexes).size!==indexes.length)throw new Error(`Introduce exactamente ${pdf.getPageCount()} números de página, sin repetir.`);const reordered=await PDFDocument.create();const pages=await reordered.copyPages(pdf,indexes);pages.forEach(p=>reordered.addPage(p));download(new Blob([await reordered.save()],{type:"application/pdf"}),"pdf-reordenado.pdf");setOut("Páginas reordenadas correctamente.");return}
 if(tool.slug==="pdf-a-imagenes"||tool.slug==="extraer-texto-pdf"){const pdfjs=await import("pdfjs-dist/legacy/build/pdf.mjs");const doc=await pdfjs.getDocument({data:new Uint8Array(bytes),disableWorker:true}).promise;if(tool.slug==="extraer-texto-pdf"){let text="";for(let i=1;i<=doc.numPages;i++){const p=await doc.getPage(i);const content=await p.getTextContent();text+=`\n--- Página ${i} ---\n${content.items.map((x:any)=>x.str).join(" ")}\n`}setOut(text.trim()||"No se encontró texto seleccionable en el PDF.");return}for(let i=1;i<=doc.numPages;i++){const p=await doc.getPage(i);const viewport=p.getViewport({scale:1.5});const canvas=document.createElement("canvas");canvas.width=viewport.width;canvas.height=viewport.height;await p.render({canvasContext:canvas.getContext("2d")!,viewport}).promise;download(await canvasBlob(canvas,"image/png"),`pagina-${i}.png`)}setOut(`${doc.numPages} página(s) convertida(s) a PNG.`);return}throw new Error("Operación PDF no reconocida.");}catch(e){setError(e instanceof Error?e.message:"No se pudo procesar el archivo.")}};
 return <div className="space-y-4"><label className="block rounded-xl border-2 border-dashed border-border p-8 text-center cursor-pointer hover:border-primary/50"><input type="file" accept={accept} multiple={multiple} className="sr-only" onChange={e=>setFiles(Array.from(e.target.files??[]))}/><span className="font-semibold">Seleccionar {multiple?"archivos":"archivo"}</span><span className="mt-1 block text-sm text-muted-foreground">Todo el procesamiento compatible se realiza localmente en tu navegador.</span></label>{files.length>0&&<div className="rounded-xl border bg-muted/30 p-4 space-y-2"><p className="font-semibold">{files.length} archivo(s) seleccionado(s)</p><p className="text-sm text-muted-foreground">{files[0].name} · {info}</p>{(image||imagePdf)&&url&&<img src={url} alt="Vista previa" className="max-h-64 max-w-full rounded-lg object-contain"/>}</div>}{image&&(tool.slug==="redimensionar-imagen"||tool.slug==="recortar-imagen")&&<div className="grid gap-4 sm:grid-cols-2"><input type="number" min="1" value={width} onChange={e=>setWidth(e.target.value)} placeholder="Ancho (px)" className="h-11 rounded-xl border bg-background px-3"/><input type="number" min="1" value={height} onChange={e=>setHeight(e.target.value)} placeholder="Alto (px)" className="h-11 rounded-xl border bg-background px-3"/></div>}{image&&tool.slug==="comprimir-imagen"&&<label className="block text-sm">Calidad: <input type="number" min="0.1" max="1" step="0.05" value={quality} onChange={e=>setQuality(e.target.value)} className="ml-2 h-10 w-24 rounded-lg border px-2"/></label>}{(tool.slug==="rotar-imagen"||tool.slug==="rotar-pdf")&&<input type="number" value={angle} onChange={e=>setAngle(e.target.value)} placeholder="Grados" className="h-11 w-full rounded-xl border bg-background px-3"/>}{(tool.slug==="dividir-pdf"||tool.slug==="rotar-pdf")&&<input type="number" min="1" value={page} onChange={e=>setPage(e.target.value)} placeholder="Número de página" className="h-11 w-full rounded-xl border bg-background px-3"/>}{tool.slug==="reordenar-pdf"&&<input value={order} onChange={e=>setOrder(e.target.value)} placeholder="Orden, por ejemplo: 3,1,2" className="h-11 w-full rounded-xl border bg-background px-3"/>}<button disabled={!files.length} onClick={process} className="rounded-xl bg-primary px-4 py-2 font-bold text-primary-foreground disabled:opacity-50">{actionLabel}</button>{error&&<p className="rounded-xl border border-destructive/50 bg-destructive/10 p-3 text-sm">{error}</p>}{out&&<pre className="max-h-96 overflow-auto whitespace-pre-wrap rounded-xl border bg-muted/30 p-4 text-sm">{out}</pre>}</div>;
}
