import type {ReactNode} from "react";
import {GENERAL_TOOLS} from "@/lib/general";
import {GeneralTool} from "./GeneralTool";
import {MathTool} from "./MathTool";
import {DesignTool} from "./DesignTool";
import {SecurityTool} from "./SecurityTool";
import {TimeTool} from "./TimeTool";
import {ConverterTool} from "./ConverterTool";
import {ScienceTool} from "./ScienceTool";
const STATS=new Set(["promedio","mediana","rango","varianza","desviacion-estandar"]);
const TIMERS=new Set(["cronometro","cuenta-regresiva","pomodoro","temporizador","temporizador-cocina"]);
export const GENERAL_TOOL_UI:Record<string,()=>ReactNode>=Object.fromEntries(GENERAL_TOOLS.map(tool=>[tool.slug,()=>tool.category==="diseno"?<DesignTool tool={tool}/>:tool.category==="seguridad"?<SecurityTool tool={tool}/>:tool.category==="ciencia"?<ScienceTool tool={tool}/>:tool.category==="conversiones"?<ConverterTool tool={tool}/>:tool.category==="fechas"||TIMERS.has(tool.slug)?<TimeTool tool={tool}/>:STATS.has(tool.slug)?<MathTool tool={tool}/>:<GeneralTool tool={tool}/>]));
