import type {ReactNode} from "react";
import {GENERAL_TOOLS} from "@/lib/general";
import {GeneralTool} from "./GeneralTool";
import {MathTool} from "./MathTool";
import {DesignTool} from "./DesignTool";
import {SecurityTool} from "./SecurityTool";
import {TimeTool} from "./TimeTool";
import {ConverterTool} from "./ConverterTool";
import {ScienceTool} from "./ScienceTool";
import {FormulaTool} from "./FormulaTool";
import {EducationTool} from "./EducationTool";
const STATS=new Set(["promedio","mediana","rango","varianza","desviacion-estandar"]);
const FORMULAS=new Set(["porcentaje","regla-de-tres","probabilidad","combinaciones","permutaciones","factorial","potencias-y-raices","logaritmos","notacion-cientifica","mcd-mcm","secuencias","bases-numericas","porciones-receta","hidratacion-masa","coste-comida","propina-viaje","consumo-combustible","coste-km","divisor-gastos","propina","distancia-viaje","combustible-viaje","escalador-recetas","cafe","horno"]);
const TIMERS=new Set(["cronometro","cuenta-regresiva","pomodoro","temporizador","temporizador-cocina"]);
export const GENERAL_TOOL_UI:Record<string,()=>ReactNode>=Object.fromEntries(GENERAL_TOOLS.map(tool=>[tool.slug,()=>tool.category==="educacion"?<EducationTool tool={tool}/>:tool.category==="diseno"?<DesignTool tool={tool}/>:tool.category==="seguridad"?<SecurityTool tool={tool}/>:tool.category==="ciencia"?<ScienceTool tool={tool}/>:tool.category==="conversiones"?<ConverterTool tool={tool}/>:tool.category==="fechas"||TIMERS.has(tool.slug)?<TimeTool tool={tool}/>:STATS.has(tool.slug)?<MathTool tool={tool}/>:FORMULAS.has(tool.slug)?<FormulaTool tool={tool}/>:<GeneralTool tool={tool}/>]));
