import { useState } from "react";
import { Link } from "@tanstack/react-router";
import { Menu, X } from "lucide-react";
import { ALL_CATEGORIES } from "@/lib/all-tools";

export function SiteHeader() {
  const [open, setOpen] = useState(false);
  return <header className="site-header sticky top-0 z-50">
    <div className="container-page flex h-16 items-center justify-between gap-4">
      <Link to="/" className="brand-lockup flex min-h-11 items-center gap-2.5" aria-label="UtiliHub home"><img src="/utilihub-logo.svg" alt="" className="brand-mark size-9" /><span><span className="block text-base font-extrabold tracking-tight">UtiliHub</span><span className="hidden text-[10px] font-semibold uppercase tracking-[.14em] text-muted-foreground sm:block">Solve it in seconds</span></span></Link>
      <nav aria-label="Main" className="site-nav hidden items-center gap-0.5 lg:flex"><Link to="/tools" className="rounded-full px-3.5 py-2 text-sm font-semibold text-foreground hover:bg-accent" activeProps={{ className: "bg-accent text-primary ring-1 ring-primary/70" }}>Tools</Link><Link to="/kits" className="rounded-full px-3.5 py-2 text-sm font-semibold text-foreground hover:bg-accent" activeProps={{ className: "bg-accent text-primary ring-1 ring-primary/70" }}>Kits</Link><Link to="/hubs/documents-and-files" className="rounded-full px-3.5 py-2 text-sm font-semibold text-foreground hover:bg-accent" activeProps={{ className: "bg-accent text-primary ring-1 ring-primary/70" }}>Documents</Link><Link to="/finance" className="rounded-full px-3.5 py-2 text-sm font-semibold text-foreground hover:bg-accent" activeProps={{ className: "bg-accent text-primary ring-1 ring-primary/70" }}>Finance</Link>{ALL_CATEGORIES.filter(c => c.slug !== "finanzas").slice(0, 4).map(c => <Link key={c.slug} to="/category/$slug" params={{ slug: c.slug }} className="rounded-full px-3.5 py-2 text-sm text-muted-foreground hover:bg-accent hover:text-foreground" activeProps={{ className: "bg-accent text-primary ring-1 ring-primary/70" }}>{c.name}</Link>)}<Link to="/es" aria-label="Ver UtiliHub en español" className="ml-1 rounded-full border border-primary/40 bg-primary/10 px-3 py-2 text-sm font-bold text-primary hover:bg-primary/15">Español</Link></nav>
      <button type="button" className="grid size-11 place-items-center rounded-xl border border-border bg-card shadow-sm lg:hidden" aria-expanded={open} aria-label={open ? "Close menu" : "Open menu"} onClick={() => setOpen(v => !v)}>{open ? <X className="size-5" /> : <Menu className="size-5" />}</button>
    </div>
    {open && <nav aria-label="Mobile" className="border-t border-border bg-background lg:hidden"><div className="container-page grid gap-1 py-2"><Link to="/tools" onClick={() => setOpen(false)} className="min-h-11 rounded-lg px-3 py-2.5 text-sm font-bold hover:bg-accent" activeProps={{ className: "bg-accent text-primary" }}>Browse all tools</Link><Link to="/kits" onClick={() => setOpen(false)} className="min-h-11 rounded-lg px-3 py-2.5 text-sm font-bold hover:bg-accent" activeProps={{ className: "bg-accent text-primary" }}>Goal-based kits</Link><Link to="/hubs/documents-and-files" onClick={() => setOpen(false)} className="min-h-11 rounded-lg px-3 py-2.5 text-sm font-bold hover:bg-accent" activeProps={{ className: "bg-accent text-primary" }}>Documents & files</Link>{ALL_CATEGORIES.map(c => <Link key={c.slug} to="/category/$slug" params={{ slug: c.slug }} onClick={() => setOpen(false)} className="min-h-11 rounded-lg px-3 py-2.5 text-sm font-semibold hover:bg-accent" activeProps={{ className: "bg-accent text-primary" }}>{c.name}</Link>)}<Link to="/es" onClick={() => setOpen(false)} className="min-h-11 rounded-lg border border-primary/40 bg-primary/10 px-3 py-2.5 text-sm font-bold text-primary hover:bg-primary/15">Ver en español</Link></div></nav>}
  </header>;
}
