export type FinancialMeta={slug:string;name:string;description:string;summary:string;keywords:string[]};
const m=(slug:string,name:string,summary:string):FinancialMeta=>({slug,name,summary,description:`${summary} Calculadora financiera gratuita de UtiliHub.`,keywords:[name.toLowerCase(),"calculadora financiera","finanzas"]});
export const FINANCIAL_CATALOG:FinancialMeta[]=[
 m("interes-compuesto","Interés compuesto","Proyecta capital, aportes e intereses acumulados."),m("cuota-de-prestamo","Cuota de préstamo","Calcula cuota mensual, intereses y coste total."),m("rentabilidad-de-inversion","Rentabilidad de inversión","Calcula ROI, beneficio y rendimiento anualizado."),m("objetivo-de-ahorro","Objetivo de ahorro","Calcula el aporte mensual necesario para alcanzar una meta."),m("inflacion-y-poder-adquisitivo","Inflación y poder adquisitivo","Estima valor futuro y poder adquisitivo ajustado."),
 m("cagr","CAGR","Calcula la tasa de crecimiento anual compuesto."),m("roi","ROI","Calcula rentabilidad porcentual y beneficio neto."),m("rentabilidad-anualizada","Rentabilidad anualizada","Compara rendimientos con distintos períodos."),m("punto-equilibrio-inversion","Punto de equilibrio de inversión","Calcula el precio necesario para recuperar costes."),m("drawdown","Drawdown","Mide la caída desde un máximo hasta un mínimo."),m("precio-medio-de-compra","Precio medio de compra","Promedia varias compras de un mismo activo."),m("dca","DCA","Simula compras periódicas y capitalización."),m("riesgo-beneficio","Riesgo/beneficio","Calcula riesgo, beneficio potencial y ratio R/R."),m("tamano-de-posicion","Tamaño de posición","Calcula una posición según capital, riesgo y stop."),m("rebalanceo-de-cartera","Rebalanceo de cartera","Calcula cuánto ajustar una posición hacia su peso objetivo."),m("asignacion-de-cartera","Asignación de cartera","Comprueba la distribución porcentual de una cartera."),m("rentabilidad-real","Rentabilidad real","Descuenta inflación de la rentabilidad nominal."),m("comparador-de-inversiones","Comparador de inversiones","Compara rendimientos de dos inversiones."),
 m("amortizacion-de-prestamo","Amortización de préstamo","Calcula cuota, intereses y total pagado."),m("comparador-de-prestamos","Comparador de préstamos","Compara el coste total de dos préstamos."),m("pago-anticipado-de-prestamo","Pago anticipado de préstamo","Estima meses e intereses ahorrados con pagos extra."),m("cuota-con-capital-variable","Cuota con costes adicionales","Calcula el coste mensual incluyendo gastos adicionales."),m("payback-period","Periodo de recuperación","Calcula cuánto tarda una inversión en recuperar su coste."),
 m("ahorro-periodico","Ahorro periódico","Proyecta ahorro con aportes y rentabilidad."),m("ahorro-para-una-compra","Ahorro para una compra","Calcula cuánto ahorrar al mes para una compra futura."),m("fondo-de-emergencia","Fondo de emergencia","Estima el fondo necesario según tus gastos."),m("tasa-de-ahorro","Tasa de ahorro","Calcula qué porcentaje de tus ingresos ahorras."),m("meta-de-ahorro-con-rendimiento","Meta de ahorro con rendimiento","Calcula el aporte necesario considerando rentabilidad."),
 m("inflacion-acumulada","Inflación acumulada","Combina tasas de inflación de varios años correctamente."),m("inflacion-inversa","Inflación inversa","Estima el precio equivalente de una cantidad histórica."),m("poder-adquisitivo","Poder adquisitivo","Calcula cómo cambia el valor real de una cantidad."),m("salario-real","Salario real","Compara crecimiento salarial e inflación."),m("rentabilidad-vs-inflacion","Rentabilidad vs inflación","Compara crecimiento nominal y real a lo largo del tiempo."),
 m("conversor-de-divisas","Conversor de divisas","Convierte cantidades usando un tipo de cambio introducido."),m("dividendos","Calculadora de dividendos","Calcula dividendos anuales, mensuales y yield."),m("dividendos-reinvertidos","Dividendos reinvertidos","Simula crecimiento mediante reinversión de dividendos."),m("diversificacion-de-cartera","Diversificación de cartera","Analiza concentración y distribución de activos."),m("monte-carlo-inversion","Monte Carlo de inversión","Simula escenarios probabilísticos de crecimiento."),
 m("optimizacion-de-cartera","Optimización de cartera","Calcula el ajuste de una posición hacia un objetivo."),m("rebalanceo-multiple","Rebalanceo múltiple","Calcula valores objetivo para varios activos."),m("calculadora-de-drawdown-recuperacion","Drawdown y recuperación","Calcula caída y subida necesaria para recuperar un máximo."),m("concentracion-de-cartera","Concentración de cartera","Detecta concentraciones superiores a un umbral."),m("calculadora-de-comisiones","Calculadora de comisiones","Estima costes de compra, venta y otros gastos."),
 m("simulador-de-jubilacion","Simulador de jubilación","Proyecta patrimonio nominal y real hasta la jubilación."),m("fire-calculator","FIRE Calculator","Estima el tiempo para alcanzar independencia financiera."),m("capital-necesario-para-renta","Capital necesario para una renta","Calcula patrimonio necesario para una renta anual objetivo."),m("tasa-de-retiro","Tasa de retiro","Calcula qué porcentaje del patrimonio retiras cada año."),m("proyeccion-de-patrimonio","Proyección de patrimonio","Proyecta patrimonio a partir de aportes y rentabilidad."),
 m("calculadora-de-bonos","Calculadora de bonos","Estima el precio teórico de un bono."),m("rendimiento-de-bonos","Rendimiento de bonos","Calcula current yield y descuento o prima."),m("yield-to-maturity","Yield to Maturity","Estima la TIR de un bono comprado bajo o sobre par."),m("duracion-de-bonos","Duración de bonos","Calcula una aproximación de la duración de Macaulay."),m("valor-actual-neto","VAN / NPV","Calcula el valor actual neto de flujos futuros."),m("tasa-interna-de-retorno","TIR / IRR","Estima la tasa interna de retorno de un proyecto."),
 m("salario-neto","Salario neto","Estima salario después de impuestos y contribuciones."),m("calculadora-de-impuestos","Calculadora de impuestos","Estima impuestos con una tasa efectiva y deducciones."),
];
