export type FinancialMeta={slug:string;name:string;description:string;summary:string;keywords:string[]};
const m=(slug:string,name:string,summary:string):FinancialMeta=>({slug,name,summary,description:`${summary} Free UtiliHub financial calculator.`,keywords:[name.toLowerCase(),"financial calculator","finance"]});
export const FINANCIAL_CATALOG:FinancialMeta[]=[
 m("interes-compuesto","Compound interest","Project capital, contributions, and accumulated interest."),m("cuota-de-prestamo","Loan payment","Calculate monthly payment, interest, and total cost."),m("rentabilidad-de-inversion","Investment return","Calculate ROI, profit, and annualized return."),m("objetivo-de-ahorro","Savings goal","Calculate the monthly contribution needed to reach a goal."),m("inflacion-y-poder-adquisitivo","Inflation and purchasing power","Estimate future value and inflation-adjusted purchasing power."),
 m("cagr","CAGR","Calculate the compound annual growth rate."),m("roi","ROI","Calculate percentage return and net profit."),m("rentabilidad-anualizada","Annualized return","Compare returns over different periods."),m("punto-equilibrio-inversion","Investment break-even","Calculate the price needed to recover costs."),m("drawdown","Drawdown","Measure the drop from a peak to a trough."),m("precio-medio-de-compra","Average purchase price","Average multiple purchases of the same asset."),m("dca","DCA","Simulate periodic purchases and compounding."),m("riesgo-beneficio","Risk/reward","Calculate risk, potential reward, and R/R ratio."),m("tamano-de-posicion","Position size","Calculate a position based on capital, risk, and stop."),m("rebalanceo-de-cartera","Portfolio rebalancing","Calculate how much to adjust a position toward its target weight."),m("asignacion-de-cartera","Portfolio allocation","Check the percentage distribution of a portfolio."),m("rentabilidad-real","Real return","Subtract inflation from nominal return."),m("comparador-de-inversiones","Investment comparison","Compare returns of two investments."),
 m("amortizacion-de-prestamo","Loan amortization","Calculate payment, interest, and total paid."),m("comparador-de-prestamos","Loan comparison","Compare the total cost of two loans."),m("pago-anticipado-de-prestamo","Early loan repayment","Estimate months and interest saved with extra payments."),m("cuota-con-capital-variable","Payment with extra costs","Calculate monthly cost including additional expenses."),m("payback-period","Payback period","Calculate how long an investment takes to recover its cost."),
 m("ahorro-periodico","Periodic savings","Project savings with contributions and returns."),m("ahorro-para-una-compra","Savings for a purchase","Calculate how much to save per month for a future purchase."),m("fondo-de-emergencia","Emergency fund","Estimate the fund needed based on your expenses."),m("tasa-de-ahorro","Savings rate","Calculate what percentage of your income you save."),m("meta-de-ahorro-con-rendimiento","Savings goal with return","Calculate the contribution needed considering returns."),
 m("inflacion-acumulada","Cumulative inflation","Correctly combine inflation rates over several years."),m("inflacion-inversa","Reverse inflation","Estimate the equivalent price of a historical amount."),m("poder-adquisitivo","Purchasing power","Calculate how the real value of an amount changes."),m("salario-real","Real salary","Compare salary growth and inflation."),m("rentabilidad-vs-inflacion","Return vs inflation","Compare nominal and real growth over time."),
 m("conversor-de-divisas","Currency converter","Convert amounts using an entered exchange rate."),m("dividendos","Dividend calculator","Calculate annual and monthly dividends and yield."),m("dividendos-reinvertidos","Reinvested dividends","Simulate growth through dividend reinvestment."),m("diversificacion-de-cartera","Portfolio diversification","Analyze concentration and asset distribution."),m("monte-carlo-inversion","Investment Monte Carlo","Simulate probabilistic growth scenarios."),
 m("optimizacion-de-cartera","Portfolio optimization","Calculate the adjustment of a position toward a target."),m("rebalanceo-multiple","Multi-asset rebalancing","Calculate target values for multiple assets."),m("calculadora-de-drawdown-recuperacion","Drawdown and recovery","Calculate the drop and rise needed to recover a peak."),m("concentracion-de-cartera","Portfolio concentration","Detect concentrations above a threshold."),m("calculadora-de-comisiones","Fee calculator","Estimate buy, sell, and other costs."),
 m("simulador-de-jubilacion","Retirement simulator","Project nominal and real wealth until retirement."),m("fire-calculator","FIRE Calculator","Estimate the time to reach financial independence."),m("capital-necesario-para-renta","Capital needed for income","Calculate the wealth needed for a target annual income."),m("tasa-de-retiro","Withdrawal rate","Calculate what percentage of wealth you withdraw each year."),m("proyeccion-de-patrimonio","Wealth projection","Project wealth from contributions and returns."),
 m("calculadora-de-bonos","Bond calculator","Estimate the theoretical price of a bond."),m("rendimiento-de-bonos","Bond yield","Calculate current yield and discount or premium."),m("yield-to-maturity","Yield to Maturity","Estimate the YTM of a bond bought below or above par."),m("duracion-de-bonos","Bond duration","Calculate an approximation of Macaulay duration."),m("valor-actual-neto","NPV","Calculate the net present value of future cash flows."),m("tasa-interna-de-retorno","IRR","Estimate the internal rate of return of a project."),
 m("salario-neto","Net salary","Estimate salary after taxes and contributions."),m("calculadora-de-impuestos","Tax calculator","Estimate taxes with an effective rate and deductions."),m("calculadora-roic","ROIC calculator","Compare return on invested capital with WACC."),m("runway-y-burn-rate","Runway and burn rate","Estimate months of cash and monthly net burn."),m("apalancamiento-operativo","Operating leverage","Analyze fixed costs, break-even, and result sensitivity."),m("modelo-de-crecimiento-de-dividendos","Dividend growth model","Estimate a theoretical value with constant growth."),m("margen-de-seguridad","Margin of safety","Measure how far sales can fall before break-even."),
 m("valoracion-dcf","DCF valuation","Estimate enterprise value using discounted cash flows."),m("calculadora-wacc","WACC calculator","Calculate the weighted average cost of capital."),m("cobertura-del-servicio-de-la-deuda","Debt service coverage","Calculate DSCR and interest coverage."),m("ciclo-de-conversion-de-efectivo","Cash conversion cycle","Measure the days capital stays tied up in operations."),m("apalancamiento-neto","Net leverage","Analyze net debt, debt to EBITDA, and capital structure."),
];
