import type { FinancialDefinition } from "./types";
import { money, pct, financialValue } from "./types";
const f=(key:string,label:string,defaultValue:number,unit="")=>({key,label,defaultValue,unit});
const price=(face:number,coupon:number,yieldRate:number,years:number)=>{let p=0;for(let t=1;t<=years;t++)p+=face*coupon/100/Math.pow(1+yieldRate/100,t);return p+face/Math.pow(1+yieldRate/100,years);};
const solveYtm=(target:number,face:number,coupon:number,years:number)=>{let lo=-.99,hi=10;for(let i=0;i<100;i++){const mid=(lo+hi)/2,p=price(face,coupon,mid*100,years);if(p>target)lo=mid;else hi=mid;}return(lo+hi)/2*100;};
export const FIXED_INCOME_TOOLS:FinancialDefinition[]=[
{slug:"calculadora-de-bonos",fields:[f("face","Face value",1000,"$"),f("coupon","Annual coupon",5,"%"),f("yield","Yield",4,"%"),f("years","Years",5)],calculate:v=>[{label:"Theoretical price",value:money(price(financialValue(v, "face"),financialValue(v, "coupon"),financialValue(v, "yield"),financialValue(v, "years")))},{label:"Annual coupon",value:money(financialValue(v, "face")*financialValue(v, "coupon")/100)}]},
{slug:"rendimiento-de-bonos",fields:[f("price","Price paid",950,"$"),f("face","Face value",1000,"$"),f("coupon","Annual coupon",50,"$")],calculate:v=>[{label:"Current yield",value:pct(financialValue(v, "price")?financialValue(v, "coupon")/financialValue(v, "price")*100:0)},{label:"Discount/premium",value:money(financialValue(v, "face")-financialValue(v, "price"))}]},
{slug:"yield-to-maturity",fields:[f("price","Price",950,"$"),f("face","Face value",1000,"$"),f("coupon","Annual coupon",50,"$"),f("years","Years",5)],calculate:v=>[{label:"Approximate YTM",value:pct(solveYtm(financialValue(v, "price"),financialValue(v, "face"),financialValue(v, "coupon")/financialValue(v, "face")*100,financialValue(v, "years")))}],note:"Numerical estimate. Bonds with amortizations, options, or irregular cash flows need a specific method."},
{slug:"duracion-de-bonos",fields:[f("face","Face value",1000,"$"),f("coupon","Annual coupon",5,"%"),f("yield","Yield",4,"%"),f("years","Years",5)],calculate:v=>{const y=financialValue(v, "yield")/100,c=financialValue(v, "face")*financialValue(v, "coupon")/100,p=price(financialValue(v, "face"),financialValue(v, "coupon"),financialValue(v, "yield"),financialValue(v, "years"));let d=0;for(let t=1;t<=financialValue(v, "years");t++){const cf=t===financialValue(v, "years")?c+financialValue(v, "face"):c;d+=t*cf/Math.pow(1+y,t);}return[{label:"Macaulay duration",value:`${(d/p).toFixed(2)} years`},{label:"Price",value:money(p)}]}},
{slug:"valor-actual-neto",fields:[f("initial","Initial investment",10000,"$"),f("cashflow","Annual cash flow",3000,"$"),f("rate","Discount rate",8,"%"),f("years","Years",5)],calculate:v=>{let pv=-financialValue(v, "initial");for(let t=1;t<=financialValue(v, "years");t++)pv+=financialValue(v, "cashflow")/Math.pow(1+financialValue(v, "rate")/100,t);return[{label:"NPV",value:money(pv)},{label:"Indicative decision",value:pv>0?"Positive NPV":"Negative NPV"}]}},
{slug:"tasa-interna-de-retorno",fields:[f("initial","Initial investment",10000,"$"),f("cashflow","Annual cash flow",3000,"$"),f("years","Years",5)],calculate:v=>{let lo=-.99,hi=2;for(let i=0;i<80;i++){const r=(lo+hi)/2;let npv=-financialValue(v, "initial");for(let t=1;t<=financialValue(v, "years");t++)npv+=financialValue(v, "cashflow")/Math.pow(1+r,t);if(npv>0)lo=r;else hi=r;}return[{label:"IRR",value:pct(((lo+hi)/2)*100)}]}},
];
