import type { FinancialDefinition } from "./types";
import { money, pct } from "./types";
const f=(key:string,label:string,defaultValue:number,unit="")=>({key,label,defaultValue,unit});
const error=(value:string)=>[{label:"Error",value}];
const price=(face:number,coupon:number,yieldRate:number,years:number)=>{let p=0;for(let t=1;t<=years;t++)p+=face*coupon/100/Math.pow(1+yieldRate/100,t);return p+face/Math.pow(1+yieldRate/100,years)};
const solveYtm=(target:number,face:number,coupon:number,years:number)=>{let lo=-.99,hi=10;for(let i=0;i<100;i++){const mid=(lo+hi)/2,p=price(face,coupon,mid*100,years);if(p>target)lo=mid;else hi=mid}return(lo+hi)/2*100};
export const FIXED_INCOME_TOOLS:FinancialDefinition[]=[
{slug:"calculadora-de-bonos",fields:[f("face","Valor nominal",1000,"$"),f("coupon","Cupón anual",5,"%"),f("yield","Rendimiento",4,"%"),f("years","Años",5)],calculate:v=>{if(v.face<=0||v.years<=0||v.yield<=-100)return error("El valor nominal y los años deben ser mayores que 0 y el rendimiento debe ser mayor que -100 %.");return[{label:"Precio teórico",value:money(price(v.face,v.coupon,v.yield,v.years))},{label:"Cupón anual",value:money(v.face*v.coupon/100)}]}},
{slug:"rendimiento-de-bonos",fields:[f("price","Precio pagado",950,"$"),f("face","Valor nominal",1000,"$"),f("coupon","Cupón anual",50,"$")],calculate:v=>{if(v.price<=0||v.face<0||v.coupon<0)return error("El precio debe ser mayor que 0 y los demás valores no pueden ser negativos.");return[{label:"Current yield",value:pct(v.coupon/v.price*100)},{label:"Descuento/premium",value:money(v.face-v.price)}]}},
{slug:"yield-to-maturity",fields:[f("price","Precio",950,"$"),f("face","Valor nominal",1000,"$"),f("coupon","Cupón anual",50,"$"),f("years","Años",5)],calculate:v=>{if(v.price<=0||v.face<=0||v.coupon<0||v.years<=0)return error("Precio, valor nominal y años deben ser mayores que 0; el cupón no puede ser negativo.");return[{label:"YTM aproximada",value:pct(solveYtm(v.price,v.face,v.coupon/v.face*100,v.years))}]},note:"Estimación numérica. Para bonos con amortizaciones, opciones o flujos irregulares se necesita un método específico."},
{slug:"duracion-de-bonos",fields:[f("face","Valor nominal",1000,"$"),f("coupon","Cupón anual",5,"%"),f("yield","Rendimiento",4,"%"),f("years","Años",5)],calculate:v=>{if(v.face<=0||v.years<=0||v.yield<=-100)return error("El valor nominal y los años deben ser mayores que 0 y el rendimiento debe ser mayor que -100 %.");const y=v.yield/100,c=v.face*v.coupon/100,p=price(v.face,v.coupon,v.yield,v.years);let d=0;for(let t=1;t<=v.years;t++){const cf=t===v.years?c+v.face:c;d+=t*cf/Math.pow(1+y,t)}return[{label:"Duración de Macaulay",value:`${(d/p).toFixed(2)} años`},{label:"Precio",value:money(p)}]}},
{slug:"valor-actual-neto",fields:[f("initial","Inversión inicial",10000,"$"),f("cashflow","Flujo anual",3000,"$"),f("rate","Tasa de descuento",8,"%"),f("years","Años",5)],calculate:v=>{if(v.initial<0||v.years<=0||v.rate<=-100)return error("La inversión no puede ser negativa, los años deben ser > 0 y la tasa debe ser mayor que -100 %.");let pv=-v.initial;for(let t=1;t<=v.years;t++)pv+=v.cashflow/Math.pow(1+v.rate/100,t);return[{label:"VAN / NPV",value:money(pv)},{label:"Decisión orientativa",value:pv>0?"VAN positivo":"VAN negativo"}]}},
{slug:"tasa-interna-de-retorno",fields:[f("initial","Inversión inicial",10000,"$"),f("cashflow","Flujo anual",3000,"$"),f("years","Años",5)],calculate:v=>{if(v.initial<=0||v.cashflow<=0||v.years<=0)return error("La inversión, el flujo anual y los años deben ser mayores que 0.");let lo=-.99,hi=2;for(let i=0;i<80;i++){const r=(lo+hi)/2;let npv=-v.initial;for(let t=1;t<=v.years;t++)npv+=v.cashflow/Math.pow(1+r,t);if(npv>0)lo=r;else hi=r}return[{label:"TIR / IRR",value:pct(((lo+hi)/2)*100)}]}}
];
