import type { FinancialDefinition } from "./types";
import { money, pct } from "./types";
const f=(key:string,label:string,defaultValue:number,unit="")=>({key,label,defaultValue,unit});
const price=(face:number,coupon:number,yieldRate:number,years:number)=>{let p=0;for(let t=1;t<=years;t++)p+=face*coupon/100/Math.pow(1+yieldRate/100,t);return p+face/Math.pow(1+yieldRate/100,years);};
export const FIXED_INCOME_TOOLS:FinancialDefinition[]=[
{slug:"calculadora-de-bonos",fields:[f("face","Valor nominal",1000,"$"),f("coupon","Cupón anual",5,"%"),f("yield","Rendimiento",4,"%"),f("years","Años",5)],calculate:v=>[{label:"Precio teórico",value:money(price(v.face,v.coupon,v.yield,v.years))},{label:"Cupón anual",value:money(v.face*v.coupon/100)}]},
{slug:"rendimiento-de-bonos",fields:[f("price","Precio pagado",950,"$"),f("face","Valor nominal",1000,"$"),f("coupon","Cupón anual",50,"$")],calculate:v=>[{label:"Current yield",value:pct(v.price?v.coupon/v.price*100:0)},{label:"Descuento/premium",value:money(v.face-v.price)}]},
{slug:"yield-to-maturity",fields:[f("price","Precio",950,"$"),f("face","Valor nominal",1000,"$"),f("coupon","Cupón anual",50,"$"),f("years","Años",5)],calculate:v=>{let y=.05;for(let i=0;i<30;i++){const p=price(v.face,v.coupon/v.face*100,y*100,v.years);y*=1+(v.price-p)/(v.face*v.years+1);}return[{label:"YTM aproximada",value:pct(y*100)}]},note:"Estimación numérica aproximada; para bonos con estructuras complejas se necesita un método específico."},
{slug:"duracion-de-bonos",fields:[f("face","Valor nominal",1000,"$"),f("coupon","Cupón anual",5,"%"),f("yield","Rendimiento",4,"%"),f("years","Años",5)],calculate:v=>{const y=v.yield/100,c=v.face*v.coupon/100,p=price(v.face,v.coupon,v.yield,v.years);let d=0;for(let t=1;t<=v.years;t++){const cf=t===v.years?c+v.face:c;d+=t*cf/Math.pow(1+y,t);}return[{label:"Duración de Macaulay",value:`${(d/p).toFixed(2)} años`},{label:"Precio",value:money(p)}]}},
{slug:"valor-actual-neto",fields:[f("initial","Inversión inicial",10000,"$"),f("cashflow","Flujo anual",3000,"$"),f("rate","Tasa de descuento",8,"%"),f("years","Años",5)],calculate:v=>{let pv=-v.initial;for(let t=1;t<=v.years;t++)pv+=v.cashflow/Math.pow(1+v.rate/100,t);return[{label:"VAN / NPV",value:money(pv)},{label:"Decisión orientativa",value:pv>0?"VAN positivo":"VAN negativo"}]}},
{slug:"tasa-interna-de-retorno",fields:[f("initial","Inversión inicial",10000,"$"),f("cashflow","Flujo anual",3000,"$"),f("years","Años",5)],calculate:v=>{let lo=-.99,hi=2;for(let i=0;i<80;i++){const r=(lo+hi)/2;let npv=-v.initial;for(let t=1;t<=v.years;t++)npv+=v.cashflow/Math.pow(1+r,t);if(npv>0)lo=r;else hi=r;}return[{label:"TIR / IRR",value:pct(((lo+hi)/2)*100)}]}},
];
