import type { FinancialDefinition } from "./types";
import { money, pct, financialValue } from "./types";
const f=(key:string,label:string,defaultValue:number,unit="")=>({key,label,defaultValue,unit});
export const INFLATION_TOOLS:FinancialDefinition[]=[
{slug:"inflacion-acumulada",fields:[f("i1","Inflation year 1",10,"%"),f("i2","Inflation year 2",8,"%"),f("i3","Inflation year 3",6,"%")],calculate:v=>{const factor=(1+financialValue(v, "i1")/100)*(1+financialValue(v, "i2")/100)*(1+financialValue(v, "i3")/100);return[{label:"Cumulative inflation",value:pct((factor-1)*100)},{label:"Price multiplier",value:factor.toFixed(4)}]}},
{slug:"inflacion-inversa",fields:[f("past","Historical price",100,"$"),f("inflation","Average annual inflation",4,"%"),f("years","Years",10)],calculate:v=>{const future=financialValue(v, "past")*Math.pow(1+financialValue(v, "inflation")/100,financialValue(v, "years"));return[{label:"Equivalent price today",value:money(future)},{label:"Cumulative increase",value:pct((future/financialValue(v, "past")-1)*100)}]}},
{slug:"poder-adquisitivo",fields:[f("amount","Current amount",100000,"$"),f("inflation","Annual inflation",4,"%"),f("years","Years",10)],calculate:v=>[{label:"Equivalent future nominal value",value:money(financialValue(v, "amount")*Math.pow(1+financialValue(v, "inflation")/100,financialValue(v, "years")))},{label:"Remaining purchasing power",value:pct(100/Math.pow(1+financialValue(v, "inflation")/100,financialValue(v, "years")))}]},
{slug:"salario-real",fields:[f("salary","Current salary",100000,"$"),f("inflation","Cumulative inflation",30,"%"),f("raise","Salary increase",20,"%")],calculate:v=>{const real=financialValue(v, "salary")*(1+financialValue(v, "raise")/100)/(1+financialValue(v, "inflation")/100);return[{label:"Nominal salary",value:money(financialValue(v, "salary")*(1+financialValue(v, "raise")/100))},{label:"Salary in current purchasing power",value:money(real)},{label:"Real change",value:pct((real/financialValue(v, "salary")-1)*100)}]}},
{slug:"rentabilidad-vs-inflacion",fields:[f("return","Annual return",10,"%"),f("inflation","Annual inflation",5,"%"),f("years","Years",10)],calculate:v=>{const nominal=Math.pow(1+financialValue(v, "return")/100,financialValue(v, "years"))-1;const real=Math.pow((1+financialValue(v, "return")/100)/(1+financialValue(v, "inflation")/100),financialValue(v, "years"))-1;return[{label:"Nominal growth",value:pct(nominal*100)},{label:"Real growth",value:pct(real*100)}]}}
];
