import type { FinancialDefinition } from "./types";
import { money, num, pct } from "./types";
const f=(key:string,label:string,defaultValue:number,unit="")=>({key,label,defaultValue,unit});
const error=(value:string)=>[{label:"Error",value}];
export const INVESTMENT_TOOLS:FinancialDefinition[]=[
{slug:"cagr",fields:[f("start","Capital inicial",10000,"$"),f("end","Valor final",15000,"$"),f("years","Años",5)],calculate:v=>{if(v.start<=0||v.end<0||v.years<=0)return error("El capital inicial debe ser > 0 y los años deben ser > 0.");const r=Math.pow(v.end/v.start,1/v.years)-1;return[{label:"CAGR",value:pct(r*100)},{label:"Ganancia",value:money(v.end-v.start)}]}},
{slug:"roi",fields:[f("cost","Coste inicial",10000,"$"),f("end","Valor final",12500,"$"),f("fees","Costes adicionales",0,"$")],calculate:v=>{if(v.cost<=0)return error("El coste inicial debe ser mayor que 0.");const roi=((v.end-v.cost-v.fees)/v.cost)*100;return[{label:"ROI",value:pct(roi)},{label:"Beneficio neto",value:money(v.end-v.cost-v.fees)}]}},
{slug:"rentabilidad-anualizada",fields:[f("start","Capital inicial",10000,"$"),f("end","Capital final",12000,"$"),f("days","Días invertidos",365)],calculate:v=>{if(v.start<=0||v.end<0||v.days<=0)return error("Los capitales deben ser válidos y los días deben ser > 0.");const r=(Math.pow(v.end/v.start,365/v.days)-1)*100;return[{label:"Rentabilidad anualizada",value:pct(r)}]}},
{slug:"punto-equilibrio-inversion",fields:[f("cost","Capital invertido",10000,"$"),f("fees","Costes totales",100,"$"),f("price","Precio actual por unidad",50,"$"),f("units","Unidades",200)],calculate:v=>{if(v.units<=0||v.price<=0)return error("Las unidades y el precio actual deben ser mayores que 0.");const target=v.cost+v.fees,current=v.price*v.units;return[{label:"Valor necesario para recuperar costes",value:money(target)},{label:"Precio de equilibrio por unidad",value:money(target/v.units)},{label:"Subida necesaria",value:pct((target/current-1)*100)}]}},
{slug:"drawdown",fields:[f("peak","Máximo histórico",100,"$"),f("trough","Mínimo posterior",80,"$")],calculate:v=>{if(v.peak<=0||v.trough<0)return error("El máximo debe ser > 0 y el mínimo no puede ser negativo.");return[{label:"Drawdown",value:pct((v.trough/v.peak-1)*100)},{label:"Pérdida",value:money(v.peak-v.trough)}]}},
{slug:"precio-medio-de-compra",fields:[f("q1","Cantidad compra 1",100),f("p1","Precio compra 1",20,"$"),f("q2","Cantidad compra 2",50),f("p2","Precio compra 2",15,"$"),f("q3","Cantidad compra 3",0),f("p3","Precio compra 3",15,"$")],calculate:v=>{const q=v.q1+v.q2+v.q3,total=v.q1*v.p1+v.q2*v.p2+v.q3*v.p3;if(q<=0)return error("La cantidad total debe ser mayor que 0.");return[{label:"Cantidad total",value:num(q)},{label:"Coste total",value:money(total)},{label:"Precio medio",value:money(total/q)}]}},
{slug:"dca",fields:[f("initial","Capital inicial",1000,"$"),f("monthly","Aporte mensual",300,"$"),f("rate","Rentabilidad anual estimada",8,"%"),f("years","Años",10)],calculate:v=>{if(v.initial<0||v.monthly<0||v.years<0)return error("Capital, aportes y años no pueden ser negativos.");const m=v.rate/100/12,n=Math.round(v.years*12),fv=m===0?v.initial+v.monthly*n:v.initial*Math.pow(1+m,n)+v.monthly*((Math.pow(1+m,n)-1)/m),contributed=v.initial+v.monthly*n;return[{label:"Capital proyectado",value:money(fv)},{label:"Total aportado",value:money(contributed)},{label:"Crecimiento",value:money(fv-contributed)}]}},
{slug:"riesgo-beneficio",fields:[f("entry","Entrada",100,"$"),f("stop","Stop",95,"$"),f("target","Objetivo",115,"$")],calculate:v=>{const risk=v.entry-v.stop,reward=v.target-v.entry;if(risk<=0||reward<0)return error("El stop debe estar por debajo de la entrada y el objetivo no puede estar por debajo de ella.");return[{label:"Riesgo",value:money(risk)},{label:"Beneficio potencial",value:money(reward)},{label:"Ratio riesgo/beneficio",value:`1:${(reward/risk).toFixed(2)}`}]}},
{slug:"tamano-de-posicion",fields:[f("capital","Capital",10000,"$"),f("risk","Riesgo máximo",1,"%"),f("entry","Entrada",50,"$"),f("stop","Stop",47,"$")],calculate:v=>{const risk=v.capital*v.risk/100,per=v.entry-v.stop;if(v.capital<=0||v.risk<=0||per<=0)return error("Capital, riesgo y distancia entre entrada y stop deben ser mayores que 0.");return[{label:"Riesgo máximo",value:money(risk)},{label:"Riesgo por unidad",value:money(per)},{label:"Tamaño de posición",value:num(Math.floor(risk/per))}]}},
{slug:"rebalanceo-de-cartera",fields:[f("portfolio","Valor de cartera",10000,"$"),f("current","Peso actual",70,"%"),f("target","Peso objetivo",60,"%")],calculate:v=>{if(v.portfolio<0)return error("El valor de la cartera no puede ser negativo.");const current=v.portfolio*v.current/100,target=v.portfolio*v.target/100;return[{label:"Valor actual",value:money(current)},{label:"Valor objetivo",value:money(target)},{label:"Comprar/vender",value:money(target-current)}]}},
{slug:"asignacion-de-cartera",fields:[f("stocks","Acciones",60,"%"),f("bonds","Bonos",30,"%"),f("cash","Efectivo",10,"%")],calculate:v=>{const total=v.stocks+v.bonds+v.cash;return[{label:"Asignación total",value:pct(total)},{label:"Estado",value:Math.abs(total-100)<0.01?"Correcta":"Debe sumar 100 %"}]}},
{slug:"rentabilidad-real",fields:[f("nominal","Rentabilidad nominal",10,"%"),f("inflation","Inflación",4,"%")],calculate:v=>{if(v.inflation<=-100)return error("La inflación debe ser mayor que -100 %.");const r=((1+v.nominal/100)/(1+v.inflation/100)-1)*100;return[{label:"Rentabilidad real",value:pct(r)}]}},
{slug:"comparador-de-inversiones",fields:[f("a","Capital final A",12000,"$"),f("b","Capital final B",13500,"$"),f("initial","Capital inicial común",10000,"$")],calculate:v=>{if(v.initial<=0)return error("El capital inicial debe ser mayor que 0.");return[{label:"Rendimiento A",value:pct((v.a/v.initial-1)*100)},{label:"Rendimiento B",value:pct((v.b/v.initial-1)*100)},{label:"Mejor resultado",value:v.a>v.b?"Inversión A":v.b>v.a?"Inversión B":"Empate"}]}}
];
