import type { FinancialDefinition } from "./types";
import { money, financialValue } from "./types";
const f=(key:string,label:string,defaultValue:number,unit="")=>({key,label,defaultValue,unit});
const payment=(p:number,annual:number,years:number)=>{if(p<0||years<=0||annual<=-100)throw Error("Capital y plazo deben ser válidos y la tasa mayor que -100 %.");const r=annual/100/12,n=years*12;return r===0?p/n:p*r/(1-Math.pow(1+r,-n));};
export const LOAN_TOOLS:FinancialDefinition[]=[
{slug:"amortizacion-de-prestamo",fields:[f("principal","Capital",10000,"$"),f("rate","Tasa anual",8,"%"),f("years","Plazo",5)],calculate:v=>{const c=payment(financialValue(v, "principal"),financialValue(v, "rate"),financialValue(v, "years")),n=financialValue(v, "years")*12;return[{label:"Cuota mensual",value:money(c)},{label:"Total pagado",value:money(c*n)},{label:"Intereses",value:money(c*n-financialValue(v, "principal"))}]}},
{slug:"comparador-de-prestamos",fields:[f("principal","Capital",10000,"$"),f("rateA","Tasa A",8,"%"),f("yearsA","Plazo A",5),f("rateB","Tasa B",7,"%"),f("yearsB","Plazo B",6)],calculate:v=>{const a=payment(financialValue(v, "principal"),financialValue(v, "rateA"),financialValue(v, "yearsA"))*financialValue(v, "yearsA")*12,b=payment(financialValue(v, "principal"),financialValue(v, "rateB"),financialValue(v, "yearsB"))*financialValue(v, "yearsB")*12;return[{label:"Coste total A",value:money(a)},{label:"Coste total B",value:money(b)},{label:"Ahorro de la opción más barata",value:money(Math.abs(a-b))}]}},
{slug:"pago-anticipado-de-prestamo",fields:[f("principal","Capital",20000,"$"),f("rate","Tasa anual",8,"%"),f("years","Plazo restante",5),f("extra","Pago extra mensual",100,"$")],calculate:v=>{if(financialValue(v, "extra")<0)throw Error("El pago extra no puede ser negativo.");const r=financialValue(v, "rate")/100/12,base=payment(financialValue(v, "principal"),financialValue(v, "rate"),financialValue(v, "years")),scheduled=Math.floor(financialValue(v, "years")*12);let bal=financialValue(v, "principal"),months=0,interest=0;while(bal>0&&months<scheduled){const interestMonth=bal*r;interest+=interestMonth;const principalPaid=Math.min(bal,Math.max(0,base+financialValue(v, "extra")-interestMonth));if(principalPaid<=0)throw Error("La cuota no alcanza para amortizar el capital.");bal-=principalPaid;months++;}if(bal>0)throw Error("No se pudo amortizar el préstamo con esos valores.");const originalInterest=base*scheduled-financialValue(v, "principal");return[{label:"Cuota original",value:money(base)},{label:"Meses restantes con extra",value:months.toString()},{label:"Intereses evitados aproximados",value:money(Math.max(0,originalInterest-interest))}]}},
{slug:"cuota-con-capital-variable",fields:[f("principal","Capital",10000,"$"),f("rate","Tasa anual",8,"%"),f("years","Plazo",5),f("extra","Coste mensual adicional",20,"$")],calculate:v=>{if(financialValue(v, "extra")<0)throw Error("El coste adicional no puede ser negativo.");const c=payment(financialValue(v, "principal"),financialValue(v, "rate"),financialValue(v, "years"));return[{label:"Cuota base",value:money(c)},{label:"Cuota con coste adicional",value:money(c+financialValue(v, "extra"))}]}},
{slug:"payback-period",fields:[f("initial","Inversión inicial",10000,"$"),f("cashflow","Flujo neto anual",2500,"$")],calculate:v=>{if(financialValue(v, "initial")<0||financialValue(v, "cashflow")<=0)throw Error("La inversión debe ser no negativa y el flujo anual mayor que 0.");return[{label:"Periodo de recuperación",value:`${(financialValue(v, "initial")/financialValue(v, "cashflow")).toFixed(2)} años`},{label:"Flujo restante tras 5 años",value:money(financialValue(v, "cashflow")*5-financialValue(v, "initial"))}]}}
];
