import type { FinancialDefinition } from "./types";
import { money } from "./types";
const f=(key:string,label:string,defaultValue:number,unit="")=>({key,label,defaultValue,unit});
const payment=(p:number,annual:number,years:number)=>{const r=annual/100/12,n=years*12;return r===0?p/n:p*r/(1-Math.pow(1+r,-n));};
export const LOAN_TOOLS:FinancialDefinition[]=[
{slug:"amortizacion-de-prestamo",fields:[f("principal","Capital",10000,"$"),f("rate","Tasa anual",8,"%"),f("years","Plazo",5)],calculate:v=>{const c=payment(v.principal,v.rate,v.years),n=v.years*12;return[{label:"Cuota mensual",value:money(c)},{label:"Total pagado",value:money(c*n)},{label:"Intereses",value:money(c*n-v.principal)}]}},
{slug:"comparador-de-prestamos",fields:[f("principal","Capital",10000,"$"),f("rateA","Tasa A",8,"%"),f("yearsA","Plazo A",5),f("rateB","Tasa B",7,"%"),f("yearsB","Plazo B",6)],calculate:v=>{const a=payment(v.principal,v.rateA,v.years)*v.years*12,b=payment(v.principal,v.rateB,v.yearsB)*v.yearsB*12;return[{label:"Coste total A",value:money(a)},{label:"Coste total B",value:money(b)},{label:"Ahorro de la opción más barata",value:money(Math.abs(a-b))}]}},
{slug:"pago-anticipado-de-prestamo",fields:[f("principal","Capital",20000,"$"),f("rate","Tasa anual",8,"%"),f("years","Plazo restante",5),f("extra","Pago extra mensual",100,"$")],calculate:v=>{const r=v.rate/100/12,base=payment(v.principal,v.rate,v.years);let bal=v.principal,months=0;while(bal>0&&months<1200){bal=bal*(1+r)-base-v.extra;months++;}const originalInterest=base*v.years*12-v.principal;const newInterest=Math.max(0,(base+v.extra)*months-v.principal);return[{label:"Cuota original",value:money(base)},{label:"Meses restantes con extra",value:months.toString()},{label:"Intereses evitados aproximados",value:money(Math.max(0,originalInterest-newInterest))}]}},
{slug:"cuota-con-capital-variable",fields:[f("principal","Capital",10000,"$"),f("rate","Tasa anual",8,"%"),f("years","Plazo",5),f("extra","Coste mensual adicional",20,"$")],calculate:v=>{const c=payment(v.principal,v.rate,v.years);return[{label:"Cuota base",value:money(c)},{label:"Cuota con coste adicional",value:money(c+v.extra)}]}},
{slug:"payback-period",fields:[f("initial","Inversión inicial",10000,"$"),f("cashflow","Flujo neto anual",2500,"$")],calculate:v=>[{label:"Periodo de recuperación",value:`${(v.initial/v.cashflow).toFixed(2)} años`},{label:"Flujo restante tras 5 años",value:money(v.cashflow*5-v.initial)}]},
];
