import type { FinancialDefinition } from "./types";
import { money, pct, financialValue } from "./types";
const f=(key:string,label:string,defaultValue:number,unit="")=>({key,label,defaultValue,unit});
export const MARKET_TOOLS:FinancialDefinition[]=[
{slug:"conversor-de-divisas",fields:[f("amount","Amount",100,"from"),f("rate","Exchange rate",1.1,"to/from")],calculate:v=>[{label:"Result",value:money(financialValue(v, "amount")*financialValue(v, "rate"))}],note:"Enter the exchange rate you want to use. This version does not fetch real-time quotes."},
{slug:"dividendos",fields:[f("shares","Shares",100),f("dividend","Annual dividend per share",2,"$"),f("price","Price per share",50,"$")],calculate:v=>[{label:"Annual dividend",value:money(financialValue(v, "shares")*financialValue(v, "dividend"))},{label:"Average monthly dividend",value:money(financialValue(v, "shares")*financialValue(v, "dividend")/12)},{label:"Dividend yield",value:pct(financialValue(v, "price")?financialValue(v, "dividend")/financialValue(v, "price")*100:0)}]},
{slug:"dividendos-reinvertidos",fields:[f("initial","Initial capital",10000,"$"),f("yield","Dividend yield",4,"%"),f("growth","Annual dividend growth",5,"%"),f("years","Years",10)],calculate:v=>{let capital=financialValue(v, "initial"),annual=financialValue(v, "initial")*financialValue(v, "yield")/100;for(let i=0;i<financialValue(v, "years");i++){capital+=annual;annual*=1+financialValue(v, "growth")/100;}return[{label:"Approximate capital",value:money(capital)},{label:"Approximate final annual dividend",value:money(annual)}]}},
{slug:"diversificacion-de-cartera",fields:[f("a","Asset A",40,"%"),f("b","Asset B",30,"%"),f("c","Asset C",20,"%"),f("d","Asset D",10,"%")],calculate:v=>{const total=financialValue(v, "a")+financialValue(v, "b")+financialValue(v, "c")+financialValue(v, "d");const max=Math.max(financialValue(v, "a"),financialValue(v, "b"),financialValue(v, "c"),financialValue(v, "d"));return[{label:"Total allocation",value:pct(total)},{label:"Highest concentration",value:pct(max)},{label:"Status",value:Math.abs(total-100)<.01?"Sums to 100%":"Check the allocation"}]}},
{slug:"monte-carlo-inversion",fields:[f("initial","Initial capital",10000,"$"),f("monthly","Monthly contribution",300,"$"),f("return","Average annual return",8,"%"),f("volatility","Annual volatility",15,"%"),f("years","Years",10)],calculate:v=>{const paths=1000,n=financialValue(v, "years")*12,mu=financialValue(v, "return")/100/12,s=financialValue(v, "volatility")/100/Math.sqrt(12),out:number[]=[];for(let p=0;p<paths;p++){let x=financialValue(v, "initial");for(let i=0;i<n;i++){const z=Math.sqrt(-2*Math.log(Math.random()))*Math.cos(2*Math.PI*Math.random());x=x*(1+mu+s*z)+financialValue(v, "monthly");}out.push(x);}out.sort((a,b)=>a-b);return[{label:"10th percentile",value:money(out[100]??Number.NaN)},{label:"Median",value:money(out[500]??Number.NaN)},{label:"90th percentile",value:money(out[900]??Number.NaN)}]},note:"Illustrative random simulation; repeating it produces different results."},
];
