import type { FinancialDefinition } from "./types";
import { money, pct } from "./types";
const f=(key:string,label:string,defaultValue:number,unit="")=>({key,label,defaultValue,unit});
const error=(value:string)=>[{label:"Error",value}];
export const MARKET_TOOLS:FinancialDefinition[]=[
{slug:"conversor-de-divisas",fields:[f("amount","Cantidad",100,"moneda origen"),f("rate","Tipo de cambio",1.1,"destino/origen")],calculate:v=>v.rate<0||v.amount<0?error("La cantidad y el tipo de cambio no pueden ser negativos."):[{label:"Resultado",value:money(v.amount*v.rate)}],note:"Introduce el tipo de cambio que quieras utilizar. Esta versión no consulta cotizaciones en tiempo real."},
{slug:"dividendos",fields:[f("shares","Acciones",100),f("dividend","Dividendo por acción anual",2,"$"),f("price","Precio por acción",50,"$")],calculate:v=>v.shares<0||v.dividend<0||v.price<=0?error("Las acciones, el dividendo y el precio deben ser válidos; el precio debe ser > 0."):[{label:"Dividendo anual",value:money(v.shares*v.dividend)},{label:"Dividendo mensual medio",value:money(v.shares*v.dividend/12)},{label:"Dividend yield",value:pct(v.dividend/v.price*100)}]},
{slug:"dividendos-reinvertidos",fields:[f("initial","Capital inicial",10000,"$"),f("yield","Dividend yield",4,"%"),f("growth","Crecimiento anual del dividendo",5,"%"),f("years","Años",10)],calculate:v=>{if(v.initial<0||v.yield<0||v.years<0||v.growth<=-100)return error("Capital, yield y años no pueden ser negativos y el crecimiento debe ser mayor que -100 %.");let capital=v.initial,annual=capital*v.yield/100;for(let i=0;i<Math.round(v.years);i++){capital+=annual;annual*=1+v.growth/100;}return[{label:"Capital aproximado",value:money(capital)},{label:"Dividendo anual final aproximado",value:money(annual)}]}},
{slug:"diversificacion-de-cartera",fields:[f("a","Activo A",40,"%"),f("b","Activo B",30,"%"),f("c","Activo C",20,"%"),f("d","Activo D",10,"%")],calculate:v=>{const total=v.a+v.b+v.c+v.d,max=Math.max(v.a,v.b,v.c,v.d);if([v.a,v.b,v.c,v.d].some(value=>value<0))return error("Las ponderaciones no pueden ser negativas.");return[{label:"Asignación total",value:pct(total)},{label:"Mayor concentración",value:pct(max)},{label:"Estado",value:Math.abs(total-100)<.01?"Suma 100 %":"Revisa la asignación"}]}},
{slug:"monte-carlo-inversion",fields:[f("initial","Capital inicial",10000,"$"),f("monthly","Aporte mensual",300,"$"),f("return","Rentabilidad media anual",8,"%"),f("volatility","Volatilidad anual",15,"%"),f("years","Años",10)],calculate:v=>{if(v.initial<0||v.monthly<0||v.volatility<0||v.years<0||v.return<=-100)return error("Capital y aportes no pueden ser negativos, la volatilidad debe ser ≥ 0, los años ≥ 0 y la rentabilidad > -100 %.");const paths=1000,n=Math.round(v.years*12),mu=v.return/100/12,s=v.volatility/100/Math.sqrt(12),out:number[]=[];for(let p=0;p<paths;p++){let x=v.initial;for(let i=0;i<n;i++){const z=Math.sqrt(-2*Math.log(Math.random()))*Math.cos(2*Math.PI*Math.random());x*=Math.exp(mu-0.5*s*s+s*z);x+=v.monthly;}out.push(x)}out.sort((a,b)=>a-b);return[{label:"Escenario 10 %",value:money(out[Math.floor(paths*.1)])},{label:"Mediana",value:money(out[Math.floor(paths*.5)])},{label:"Escenario 90 %",value:money(out[Math.floor(paths*.9)])}]},note:"Simulación aleatoria orientativa; repetirla produce resultados diferentes."}
];
