import type { FinancialDefinition } from "./types";
import { money, pct, financialValue } from "./types";
const f=(key:string,label:string,defaultValue:number,unit="")=>({key,label,defaultValue,unit});
export const PORTFOLIO_TOOLS:FinancialDefinition[]=[
{slug:"optimizacion-de-cartera",fields:[f("value","Valor de cartera",10000,"$"),f("current","Peso actual del activo",70,"%"),f("target","Peso objetivo",50,"%")],calculate:v=>{const delta=financialValue(v, "value")*(financialValue(v, "target")-financialValue(v, "current"))/100;return[{label:"Valor objetivo",value:money(financialValue(v, "value")*financialValue(v, "target")/100)},{label:"Ajuste necesario",value:money(delta)},{label:"Acción",value:delta>0?"Comprar":"Reducir"}]}},
{slug:"rebalanceo-multiple",fields:[f("value","Valor total",50000,"$"),f("a","Activo A objetivo",50,"%"),f("b","Activo B objetivo",30,"%"),f("c","Activo C objetivo",20,"%")],calculate:v=>[{label:"Activo A",value:money(financialValue(v, "value")*financialValue(v, "a")/100)},{label:"Activo B",value:money(financialValue(v, "value")*financialValue(v, "b")/100)},{label:"Activo C",value:money(financialValue(v, "value")*financialValue(v, "c")/100)},{label:"Total",value:pct(financialValue(v, "a")+financialValue(v, "b")+financialValue(v, "c"))}]},
{slug:"calculadora-de-drawdown-recuperacion",fields:[f("peak","Máximo",100,"$"),f("current","Valor actual",70,"$")],calculate:v=>{const d=(financialValue(v, "current")/financialValue(v, "peak")-1)*100;return[{label:"Drawdown",value:pct(d)},{label:"Subida necesaria para recuperar",value:pct((financialValue(v, "peak")/financialValue(v, "current")-1)*100)}]}},
{slug:"concentracion-de-cartera",fields:[f("position","Posición principal",35,"%"),f("top3","Tres mayores posiciones",65,"%"),f("threshold","Umbral de concentración",25,"%")],calculate:v=>[{label:"Mayor posición",value:pct(financialValue(v, "position"))},{label:"Top 3",value:pct(financialValue(v, "top3"))},{label:"Advertencia",value:financialValue(v, "position")>financialValue(v, "threshold")?"Concentración elevada":"Por debajo del umbral indicado"}]},
{slug:"calculadora-de-comisiones",fields:[f("capital","Capital",10000,"$"),f("buy","Comisión compra",0.2,"%"),f("sell","Comisión venta",0.2,"%"),f("other","Otros costes",20,"$")],calculate:v=>{const fees=financialValue(v, "capital")*(financialValue(v, "buy")+financialValue(v, "sell"))/100+financialValue(v, "other");return[{label:"Costes totales",value:money(fees)},{label:"Coste sobre capital",value:pct(fees/financialValue(v, "capital")*100)},{label:"Capital neto",value:money(financialValue(v, "capital")-fees)}]}},
];
