import type { FinancialDefinition } from "./types";
import { money, pct, financialValue } from "./types";
const f=(key:string,label:string,defaultValue:number,unit="")=>({key,label,defaultValue,unit});
export const PORTFOLIO_TOOLS:FinancialDefinition[]=[
{slug:"optimizacion-de-cartera",fields:[f("value","Portfolio value",10000,"$"),f("current","Current asset weight",70,"%"),f("target","Target weight",50,"%")],calculate:v=>{const delta=financialValue(v, "value")*(financialValue(v, "target")-financialValue(v, "current"))/100;return[{label:"Target value",value:money(financialValue(v, "value")*financialValue(v, "target")/100)},{label:"Required adjustment",value:money(delta)},{label:"Action",value:delta>0?"Buy":"Reduce"}]}},
{slug:"rebalanceo-multiple",fields:[f("value","Total value",50000,"$"),f("a","Asset A target",50,"%"),f("b","Asset B target",30,"%"),f("c","Asset C target",20,"%")],calculate:v=>[{label:"Asset A",value:money(financialValue(v, "value")*financialValue(v, "a")/100)},{label:"Asset B",value:money(financialValue(v, "value")*financialValue(v, "b")/100)},{label:"Asset C",value:money(financialValue(v, "value")*financialValue(v, "c")/100)},{label:"Total",value:pct(financialValue(v, "a")+financialValue(v, "b")+financialValue(v, "c"))}]},
{slug:"calculadora-de-drawdown-recuperacion",fields:[f("peak","Maximum",100,"$"),f("current","Current value",70,"$")],calculate:v=>{const d=(financialValue(v, "current")/financialValue(v, "peak")-1)*100;return[{label:"Drawdown",value:pct(d)},{label:"Rise needed to recover",value:pct((financialValue(v, "peak")/financialValue(v, "current")-1)*100)}]}},
{slug:"concentracion-de-cartera",fields:[f("position","Main position",35,"%"),f("top3","Top 3 positions",65,"%"),f("threshold","Concentration threshold",25,"%")],calculate:v=>[{label:"Largest position",value:pct(financialValue(v, "position"))},{label:"Top 3",value:pct(financialValue(v, "top3"))},{label:"Warning",value:financialValue(v, "position")>financialValue(v, "threshold")?"High concentration":"Below the indicated threshold"}]},
{slug:"calculadora-de-comisiones",fields:[f("capital","Capital",10000,"$"),f("buy","Buy fee",0.2,"%"),f("sell","Sell fee",0.2,"%"),f("other","Other costs",20,"$")],calculate:v=>{const fees=financialValue(v, "capital")*(financialValue(v, "buy")+financialValue(v, "sell"))/100+financialValue(v, "other");return[{label:"Total costs",value:money(fees)},{label:"Cost as % of capital",value:pct(fees/financialValue(v, "capital")*100)},{label:"Net capital",value:money(financialValue(v, "capital")-fees)}]}}
];
