import type { FinancialDefinition } from "./types";
import { money, pct } from "./types";
const f=(key:string,label:string,defaultValue:number,unit="")=>({key,label,defaultValue,unit});
const futureValue=(principal:number,monthly:number,annualRate:number,months:number)=>{const r=annualRate/100/12;if(months<=0)return principal;if(r===0)return principal+monthly*months;const factor=Math.pow(1+r,months);return principal*factor+monthly*(factor-1)/r;};
export const RETIREMENT_TOOLS:FinancialDefinition[]=[
{slug:"simulador-de-jubilacion",fields:[f("current","Capital actual",10000,"$"),f("monthly","Aporte mensual",500,"$"),f("return","Rentabilidad anual",7,"%"),f("years","Años hasta jubilarte",25),f("inflation","Inflación anual",3,"%")],calculate:v=>{if(v.years<0||v.inflation<=-100)throw Error("Los años no pueden ser negativos y la inflación debe ser mayor que -100 %.");const n=Math.floor(v.years*12),nominal=futureValue(v.current,v.monthly,v.return,n),real=nominal/Math.pow(1+v.inflation/100,v.years);return[{label:"Capital nominal",value:money(nominal)},{label:"Capital en dinero de hoy",value:money(real)}]}},
{slug:"fire-calculator",fields:[f("capital","Patrimonio actual",20000,"$"),f("monthly","Ahorro mensual",1000,"$"),f("expenses","Gasto mensual objetivo",1500,"$"),f("return","Rentabilidad anual",7,"%")],calculate:v=>{if(v.expenses<0||v.return<=0)throw Error("El gasto debe ser no negativo y la tasa de retiro/rentabilidad debe ser mayor que 0 %.");const target=v.expenses*12/(v.return/100);let x=v.capital,months=0;while(x<target&&months<1200){x=x*(1+v.return/100/12)+v.monthly;months++;}if(x<target)throw Error("No se alcanza el patrimonio objetivo dentro de 100 años con esos valores.");return[{label:"Patrimonio objetivo",value:money(target)},{label:"Meses estimados",value:months.toString()},{label:"Años estimados",value:(months/12).toFixed(1)}]},note:"Estimación simplificada: patrimonio objetivo = gasto anual / tasa indicada. No sustituye un plan financiero personalizado."},
{slug:"capital-necesario-para-renta",fields:[f("income","Renta mensual deseada",1000,"$"),f("yield","Rendimiento anual",4,"%")],calculate:v=>{if(v.yield<=0)throw Error("El rendimiento anual debe ser mayor que 0 %.");return[{label:"Capital necesario",value:money(v.income*12/(v.yield/100))},{label:"Renta anual",value:money(v.income*12)}]}},
{slug:"tasa-de-retiro",fields:[f("capital","Patrimonio",500000,"$"),f("annual","Retiro anual",20000,"$")],calculate:v=>[{label:"Tasa de retiro",value:pct(v.capital>0?v.annual/v.capital*100:0)}]},
{slug:"proyeccion-de-patrimonio",fields:[f("current","Patrimonio actual",10000,"$"),f("monthly","Aporte mensual",500,"$"),f("return","Rentabilidad anual",7,"%"),f("years","Años",20)],calculate:v=>{if(v.years<0)throw Error("Los años no pueden ser negativos.");const n=Math.floor(v.years*12),future=futureValue(v.current,v.monthly,v.return,n);return[{label:"Patrimonio proyectado",value:money(future)},{label:"Aportes acumulados",value:money(v.current+v.monthly*n)}]}},
];
