import type { FinancialDefinition } from "./types";
import { money, pct } from "./types";
const f=(key:string,label:string,defaultValue:number,unit="")=>({key,label,defaultValue,unit});
export const RETIREMENT_TOOLS:FinancialDefinition[]=[
{slug:"simulador-de-jubilacion",fields:[f("current","Capital actual",10000,"$"),f("monthly","Aporte mensual",500,"$"),f("return","Rentabilidad anual",7,"%"),f("years","Años hasta jubilarte",25),f("inflation","Inflación anual",3,"%")],calculate:v=>{const r=v.return/100/12,n=v.years*12,f=v.current*Math.pow(1+r,n)+v.monthly*((Math.pow(1+r,n)-1)/(r||1));const real=f/Math.pow(1+v.inflation/100,v.years);return[{label:"Capital nominal",value:money(f)},{label:"Capital en dinero de hoy",value:money(real)}]}},
{slug:"fire-calculator",fields:[f("capital","Patrimonio actual",20000,"$"),f("monthly","Ahorro mensual",1000,"$"),f("expenses","Gasto mensual objetivo",1500,"$"),f("return","Rentabilidad anual",7,"%")],calculate:v=>{const target=v.expenses*12/(v.return/100);let x=v.capital,months=0;while(x<target&&months<1200){x=x*(1+v.return/100/12)+v.monthly;months++;}return[{label:"Patrimonio objetivo",value:money(target)},{label:"Meses estimados",value:months.toString()},{label:"Años estimados",value:(months/12).toFixed(1)}]},note:"La regla usada es patrimonio objetivo = gasto anual / tasa de retiro implícita, simplificada para orientación."},
{slug:"capital-necesario-para-renta",fields:[f("income","Renta mensual deseada",1000,"$"),f("yield","Rendimiento anual",4,"%")],calculate:v=>[{label:"Capital necesario",value:money(v.income*12/(v.yield/100))},{label:"Renta anual",value:money(v.income*12)}]},
{slug:"tasa-de-retiro",fields:[f("capital","Patrimonio",500000,"$"),f("annual","Retiro anual",20000,"$")],calculate:v=>[{label:"Tasa de retiro",value:pct(v.capital?v.annual/v.capital*100:0)}]},
{slug:"proyeccion-de-patrimonio",fields:[f("current","Patrimonio actual",10000,"$"),f("monthly","Aporte mensual",500,"$"),f("return","Rentabilidad anual",7,"%"),f("years","Años",20)],calculate:v=>{const r=v.return/100/12,n=v.years*12,f=v.current*Math.pow(1+r,n)+v.monthly*((Math.pow(1+r,n)-1)/(r||1));return[{label:"Patrimonio proyectado",value:money(f)},{label:"Aportes acumulados",value:money(v.current+v.monthly*n)}]}},
];
