import type { FinancialDefinition } from "./types";
import { money, pct } from "./types";
const f=(key:string,label:string,defaultValue:number,unit="")=>({key,label,defaultValue,unit});
const error=(value:string)=>[{label:"Error",value}];
const futureValue=(current:number,monthly:number,annual:number,years:number)=>{const r=annual/100/12,n=Math.round(years*12);return r===0?current+monthly*n:current*Math.pow(1+r,n)+monthly*((Math.pow(1+r,n)-1)/r)};
export const RETIREMENT_TOOLS:FinancialDefinition[]=[
{slug:"simulador-de-jubilacion",fields:[f("current","Capital actual",10000,"$"),f("monthly","Aporte mensual",500,"$"),f("return","Rentabilidad anual",7,"%"),f("years","Años hasta jubilarte",25),f("inflation","Inflación anual",3,"%")],calculate:v=>{if(v.current<0||v.monthly<0||v.years<0||v.return<=-100||v.inflation<=-100)return error("Capital, aportes y años no pueden ser negativos; las tasas deben ser mayores que -100 %.");const nominal=futureValue(v.current,v.monthly,v.return,v.years),real=nominal/Math.pow(1+v.inflation/100,v.years);return[{label:"Capital nominal",value:money(nominal)},{label:"Capital en dinero de hoy",value:money(real)}]}},
{slug:"fire-calculator",fields:[f("capital","Patrimonio actual",20000,"$"),f("monthly","Ahorro mensual",1000,"$"),f("expenses","Gasto mensual objetivo",1500,"$"),f("return","Rentabilidad anual",7,"%")],calculate:v=>{if(v.capital<0||v.monthly<0||v.expenses<=0||v.return<=0)return error("Patrimonio y ahorro no pueden ser negativos; el gasto y la rentabilidad deben ser mayores que 0.");const target=v.expenses*12/(v.return/100);let x=v.capital,months=0;while(x<target&&months<1200){x=x*(1+v.return/100/12)+v.monthly;months++;}return[{label:"Patrimonio objetivo",value:money(target)},{label:"Meses estimados",value:months>=1200?"> 100 años":String(months)},{label:"Años estimados",value:months>=1200?"> 100":(months/12).toFixed(1)}]},note:"La regla usada es patrimonio objetivo = gasto anual / tasa de retorno indicada, simplificada para orientación."},
{slug:"capital-necesario-para-renta",fields:[f("income","Renta mensual deseada",1000,"$"),f("yield","Rendimiento anual",4,"%")],calculate:v=>{if(v.income<0||v.yield<=0)return error("La renta no puede ser negativa y el rendimiento debe ser mayor que 0 %.");return[{label:"Capital necesario",value:money(v.income*12/(v.yield/100))},{label:"Renta anual",value:money(v.income*12)}]}},
{slug:"tasa-de-retiro",fields:[f("capital","Patrimonio",500000,"$"),f("annual","Retiro anual",20000,"$")],calculate:v=>{if(v.capital<=0||v.annual<0)return error("El patrimonio debe ser mayor que 0 y el retiro no puede ser negativo.");return[{label:"Tasa de retiro",value:pct(v.annual/v.capital*100)}]}},
{slug:"proyeccion-de-patrimonio",fields:[f("current","Patrimonio actual",10000,"$"),f("monthly","Aporte mensual",500,"$"),f("return","Rentabilidad anual",7,"%"),f("years","Años",20)],calculate:v=>{if(v.current<0||v.monthly<0||v.years<0||v.return<=-100)return error("Patrimonio, aportes y años no pueden ser negativos y la rentabilidad debe ser mayor que -100 %.");const projected=futureValue(v.current,v.monthly,v.return,v.years);return[{label:"Patrimonio proyectado",value:money(projected)},{label:"Aportes acumulados",value:money(v.current+v.monthly*Math.round(v.years*12))}]}}
];
