import type { FinancialDefinition } from "./types";
import { money, pct, financialValue } from "./types";
const f=(key:string,label:string,defaultValue:number,unit="")=>({key,label,defaultValue,unit});
const futureValue=(principal:number,monthly:number,annualRate:number,months:number)=>{const r=annualRate/100/12;if(months<=0) return principal;if(r===0) return principal+monthly*months;const factor=Math.pow(1+r,months);return principal*factor+monthly*(factor-1)/r;};
export const SAVINGS_TOOLS:FinancialDefinition[]=[
{slug:"ahorro-periodico",fields:[f("current","Current savings",1000,"$"),f("monthly","Monthly contribution",300,"$"),f("rate","Annual return",4,"%"),f("years","Years",5)],calculate:v=>{if(financialValue(v, "years")<0)throw Error("Years cannot be negative.");const n=Math.floor(financialValue(v, "years")*12),future=futureValue(financialValue(v, "current"),financialValue(v, "monthly"),financialValue(v, "rate"),n);return[{label:"Future capital",value:money(future)},{label:"Total contributed",value:money(financialValue(v, "current")+financialValue(v, "monthly")*n)},{label:"Growth",value:money(future-financialValue(v, "current")-financialValue(v, "monthly")*n)}]}},
{slug:"ahorro-para-una-compra",fields:[f("target","Goal",20000,"$"),f("current","Current savings",5000,"$"),f("months","Available months",18)],calculate:v=>[{label:"Required monthly contribution",value:money(Math.max(0,financialValue(v, "target")-financialValue(v, "current"))/Math.max(1,financialValue(v, "months")))},{label:"Amount still needed",value:money(Math.max(0,financialValue(v, "target")-financialValue(v, "current")))}]},
{slug:"fondo-de-emergencia",fields:[f("expenses","Monthly expenses",1500,"$"),f("months","Months of coverage",6),f("current","Current savings",4000,"$")],calculate:v=>{const target=financialValue(v, "expenses")*financialValue(v, "months");return[{label:"Target fund",value:money(target)},{label:"Current savings",value:money(financialValue(v, "current"))},{label:"Shortfall",value:money(Math.max(0,target-financialValue(v, "current")))}]}},
{slug:"tasa-de-ahorro",fields:[f("income","Monthly income",3000,"$"),f("saving","Monthly savings",900,"$")],calculate:v=>[{label:"Savings rate",value:pct(financialValue(v, "income")?financialValue(v, "saving")/financialValue(v, "income")*100:0)},{label:"Monthly spending",value:money(financialValue(v, "income")-financialValue(v, "saving"))}]},
{slug:"meta-de-ahorro-con-rendimiento",fields:[f("target","Goal",50000,"$"),f("current","Current capital",5000,"$"),f("rate","Annual return",5,"%"),f("months","Term (months)",36)],calculate:v=>{if(financialValue(v, "months")<=0)throw Error("Term must be greater than 0.");const r=financialValue(v, "rate")/100/12,n=financialValue(v, "months"),f=Math.pow(1+r,n);const monthly=r?(financialValue(v, "target")-financialValue(v, "current")*f)*r/(f-1):(financialValue(v, "target")-financialValue(v, "current"))/n;return[{label:"Required monthly contribution",value:money(Math.max(0,monthly))},{label:"Total contribution",value:money(Math.max(0,monthly)*n)}]}}
];
