import type { FinancialDefinition } from "./types";
import { money, pct } from "./types";
const f=(key:string,label:string,defaultValue:number,unit="")=>({key,label,defaultValue,unit});
const futureValue=(principal:number,monthly:number,annualRate:number,months:number)=>{const r=annualRate/100/12;if(months<=0) return principal;if(r===0) return principal+monthly*months;const factor=Math.pow(1+r,months);return principal*factor+monthly*(factor-1)/r;};
export const SAVINGS_TOOLS:FinancialDefinition[]=[
{slug:"ahorro-periodico",fields:[f("current","Ahorro actual",1000,"$"),f("monthly","Aporte mensual",300,"$"),f("rate","Rentabilidad anual",4,"%"),f("years","Años",5)],calculate:v=>{if(v.years<0)throw Error("Los años no pueden ser negativos.");const n=Math.floor(v.years*12),future=futureValue(v.current,v.monthly,v.rate,n);return[{label:"Capital futuro",value:money(future)},{label:"Total aportado",value:money(v.current+v.monthly*n)},{label:"Crecimiento",value:money(future-v.current-v.monthly*n)}]}},
{slug:"ahorro-para-una-compra",fields:[f("target","Objetivo",20000,"$"),f("current","Ahorro actual",5000,"$"),f("months","Meses disponibles",18)],calculate:v=>[{label:"Aporte mensual necesario",value:money(Math.max(0,v.target-v.current)/Math.max(1,v.months))},{label:"Falta ahorrar",value:money(Math.max(0,v.target-v.current))}]},
{slug:"fondo-de-emergencia",fields:[f("expenses","Gastos mensuales",1500,"$"),f("months","Meses de cobertura",6),f("current","Ahorros actuales",4000,"$")],calculate:v=>{const target=v.expenses*v.months;return[{label:"Fondo objetivo",value:money(target)},{label:"Ahorro actual",value:money(v.current)},{label:"Faltante",value:money(Math.max(0,target-v.current))}]}},
{slug:"tasa-de-ahorro",fields:[f("income","Ingresos mensuales",3000,"$"),f("saving","Ahorro mensual",900,"$")],calculate:v=>[{label:"Tasa de ahorro",value:pct(v.income?v.saving/v.income*100:0)},{label:"Gasto mensual",value:money(v.income-v.saving)}]},
{slug:"meta-de-ahorro-con-rendimiento",fields:[f("target","Objetivo",50000,"$"),f("current","Capital actual",5000,"$"),f("rate","Rentabilidad anual",5,"%"),f("months","Plazo",36)],calculate:v=>{if(v.months<=0)throw Error("El plazo debe ser mayor que 0.");const r=v.rate/100/12,n=v.months,f=Math.pow(1+r,n);const monthly=r?(v.target-v.current*f)*r/(f-1):(v.target-v.current)/n;return[{label:"Aporte mensual necesario",value:money(Math.max(0,monthly))},{label:"Aporte total",value:money(Math.max(0,monthly)*n)}]}},
];
