/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AvisoLegalRouteImport } from './routes/aviso-legal'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as FinanzasRouteImport } from './routes/finanzas'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as EducacionSubjectRouteImport } from './routes/educacion.$subject'
import { Route as FinanzasSlugRouteImport } from './routes/finanzas.$slug'
import { Route as HerramientasIndexRouteImport } from './routes/herramientas.index'
import { Route as HerramientasSlugRouteImport } from './routes/herramientas.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanzasRoute = FinanzasRouteImport.update({
  id: '/finanzas',
  path: '/finanzas',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EducacionSubjectRoute = EducacionSubjectRouteImport.update({
  id: '/educacion/$subject',
  path: '/educacion/$subject',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanzasSlugRoute = FinanzasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FinanzasRoute,
} as any)
const HerramientasIndexRoute = HerramientasIndexRouteImport.update({
  id: '/herramientas/',
  path: '/herramientas/',
  getParentRoute: () => rootRouteImport,
} as any)
const HerramientasSlugRoute = HerramientasSlugRouteImport.update({
  id: '/herramientas/$slug',
  path: '/herramientas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/contacto': typeof ContactoRoute
  '/finanzas': typeof FinanzasRouteWithChildren
  '/privacidad': typeof PrivacidadRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/educacion/$subject': typeof EducacionSubjectRoute
  '/finanzas/$slug': typeof FinanzasSlugRoute
  '/herramientas/$slug': typeof HerramientasSlugRoute
  '/herramientas/': typeof HerramientasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/contacto': typeof ContactoRoute
  '/finanzas': typeof FinanzasRouteWithChildren
  '/privacidad': typeof PrivacidadRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/educacion/$subject': typeof EducacionSubjectRoute
  '/finanzas/$slug': typeof FinanzasSlugRoute
  '/herramientas/$slug': typeof HerramientasSlugRoute
  '/herramientas': typeof HerramientasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/contacto': typeof ContactoRoute
  '/finanzas': typeof FinanzasRouteWithChildren
  '/privacidad': typeof PrivacidadRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/educacion/$subject': typeof EducacionSubjectRoute
  '/finanzas/$slug': typeof FinanzasSlugRoute
  '/herramientas/$slug': typeof HerramientasSlugRoute
  '/herramientas/': typeof HerramientasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aviso-legal'
    | '/contacto'
    | '/finanzas'
    | '/privacidad'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/categoria/$slug'
    | '/educacion/$subject'
    | '/finanzas/$slug'
    | '/herramientas/$slug'
    | '/herramientas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aviso-legal'
    | '/contacto'
    | '/finanzas'
    | '/privacidad'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/categoria/$slug'
    | '/educacion/$subject'
    | '/finanzas/$slug'
    | '/herramientas/$slug'
    | '/herramientas'
  id:
    | '__root__'
    | '/'
    | '/aviso-legal'
    | '/contacto'
    | '/finanzas'
    | '/privacidad'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/categoria/$slug'
    | '/educacion/$subject'
    | '/finanzas/$slug'
    | '/herramientas/$slug'
    | '/herramientas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvisoLegalRoute: typeof AvisoLegalRoute
  ContactoRoute: typeof ContactoRoute
  FinanzasRoute: typeof FinanzasRouteWithChildren
  PrivacidadRoute: typeof PrivacidadRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  EducacionSubjectRoute: typeof EducacionSubjectRoute
  HerramientasSlugRoute: typeof HerramientasSlugRoute
  HerramientasIndexRoute: typeof HerramientasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-legal': {
      id: '/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/aviso-legal'
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finanzas': {
      id: '/finanzas'
      path: '/finanzas'
      fullPath: '/finanzas'
      preLoaderRoute: typeof FinanzasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/educacion/$subject': {
      id: '/educacion/$subject'
      path: '/educacion/$subject'
      fullPath: '/educacion/$subject'
      preLoaderRoute: typeof EducacionSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finanzas/$slug': {
      id: '/finanzas/$slug'
      path: '/$slug'
      fullPath: '/finanzas/$slug'
      preLoaderRoute: typeof FinanzasSlugRouteImport
      parentRoute: typeof FinanzasRoute
    }
    '/herramientas/': {
      id: '/herramientas/'
      path: '/herramientas'
      fullPath: '/herramientas/'
      preLoaderRoute: typeof HerramientasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/herramientas/$slug': {
      id: '/herramientas/$slug'
      path: '/herramientas/$slug'
      fullPath: '/herramientas/$slug'
      preLoaderRoute: typeof HerramientasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FinanzasRouteChildren {
  FinanzasSlugRoute: typeof FinanzasSlugRoute
}

const FinanzasRouteChildren: FinanzasRouteChildren = {
  FinanzasSlugRoute: FinanzasSlugRoute,
}

const FinanzasRouteWithChildren = FinanzasRoute._addFileChildren(
  FinanzasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvisoLegalRoute: AvisoLegalRoute,
  ContactoRoute: ContactoRoute,
  FinanzasRoute: FinanzasRouteWithChildren,
  PrivacidadRoute: PrivacidadRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  EducacionSubjectRoute: EducacionSubjectRoute,
  HerramientasSlugRoute: HerramientasSlugRoute,
  HerramientasIndexRoute: HerramientasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
